---
sidebar: sidebar 
permalink: concept_searching_assets.html 
summary: Las técnicas de búsqueda avanzada pueden ayudarle a localizar los activos que está buscando. 
keywords: asset page, objects, search, advanced, alerts 
---
= Consejos y sugerencias para buscar activos y alertas
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Se pueden utilizar múltiples técnicas de búsqueda para buscar datos u objetos en su entorno monitoreado.

* *Búsqueda con comodines*
+
Puede realizar una búsqueda de varios caracteres comodín utilizando el carácter *.  Por ejemplo, _applic*n_ devolvería _application_.

* *Frases utilizadas en la búsqueda*
+
Una frase es un grupo de palabras rodeadas por comillas dobles; por ejemplo, "VNX LUN 5".  Puede utilizar comillas dobles para buscar documentos que contengan espacios en sus nombres o atributos.

* *Operadores booleanos*
+
Utilizando los operadores booleanos OR, AND y NOT, puede combinar varios términos para formar una consulta más compleja.

+
O

+
El operador OR es el operador de conjunción predeterminado.

+
Si no hay un operador booleano entre dos términos, se utiliza el operador OR.

+
El operador OR vincula dos términos y encuentra un documento coincidente si alguno de los términos existe en un documento.

+
Por ejemplo, _storage OR netapp_ busca documentos que contengan _storage_ o _netapp_.

+
Se otorgan puntuaciones altas a los documentos que coinciden con la mayoría de los términos.

+
Y

+
Puede utilizar el operador AND para buscar documentos en los que ambos términos de búsqueda existan en un solo documento.  Por ejemplo, _storage AND netapp_ busca documentos que contengan _storage_ y _netapp_.

+
Puede utilizar el símbolo *&&* en lugar de la palabra AND.

+
NO

+
Cuando se utiliza el operador NOT, todos los documentos que contengan el término después de NOT se excluyen de los resultados de la búsqueda.  Por ejemplo, _storage NOT netapp_ busca documentos que contengan solo _storage_ y no _netapp_.

+
Puedes utilizar el símbolo *!* en lugar de la palabra NOT.



La búsqueda no distingue entre mayúsculas y minúsculas.



== Búsqueda mediante términos indexados

Las búsquedas que coinciden con más términos indexados dan como resultado puntuaciones más altas.

La cadena de búsqueda se divide en términos de búsqueda separados por espacio.  Por ejemplo, la cadena de búsqueda "almacenamiento aurora netapp" se divide en tres palabras clave: "almacenamiento", "aurora" y "netapp".  La búsqueda se realiza utilizando los tres términos.  Los documentos que coincidan con la mayoría de estos términos tendrán la puntuación más alta.  Cuanto más información proporcione, mejores serán los resultados de la búsqueda.  Por ejemplo, puedes buscar un almacenamiento por su nombre y modelo.

La interfaz de usuario muestra los resultados de la búsqueda en todas las categorías, con los tres resultados principales por categoría.  Si no encontró el objeto que esperaba, puede incluir más términos en la cadena de búsqueda para mejorar los resultados de la búsqueda.

La siguiente tabla proporciona una lista de términos indexados que se pueden agregar a la cadena de búsqueda.

|===
| Categoría | Términos indexados 


| Almacenamiento | Modelo de proveedor de nombre de "almacenamiento" 


| Grupo de almacenamiento | "storagepool" nombre nombre del almacenamiento direcciones IP del almacenamiento número de serie del almacenamiento proveedor de almacenamiento modelo de almacenamiento nombres de todos los volúmenes internos asociados nombres de todos los discos asociados 


| Volumen interno | "internalvolume" nombre nombre del almacenamiento direcciones IP del almacenamiento número de serie del almacenamiento proveedor de almacenamiento modelo de almacenamiento nombre del grupo de almacenamiento nombres de todos los recursos compartidos asociados nombres de todas las aplicaciones asociadas 


| Volumen | Nombre del "volumen" Etiqueta Nombres de todos los volúmenes internos Nombre del grupo de almacenamiento Nombre del almacenamiento Direcciones IP del almacenamiento Número de serie del almacenamiento Proveedor de almacenamiento Modelo de almacenamiento 


| Nodo de almacenamiento | Nombre "storagenode" Nombre del almacenamiento Direcciones IP del almacenamiento Número de serie del almacenamiento Proveedor de almacenamiento Modelo de almacenamiento 


| Host | Nombre "host" Direcciones IP Nombres de todas las aplicaciones asociadas 


| Almacén de datos | Nombre del "almacén de datos" Nombres IP del centro virtual Nombres de todos los volúmenes Nombres de todos los volúmenes internos 


| Máquinas virtuales | "virtualmachine" nombre Nombre DNS Direcciones IP nombre del host Direcciones IP del host nombres de todos los almacenes de datos nombres de todas las aplicaciones asociadas 


| Interruptores (regulares y VPN) | "switch" Dirección IP wwn Nombre Número de serie Modelo ID de dominio Nombre de la estructura wwn de la estructura 


| Aplicación | Nombre de la "aplicación" Inquilino Línea de negocio Unidad de negocio Proyecto 


| Cinta | "cinta" nombre de la dirección IP número de serie proveedor 


| Puerto | nombre wwn del "puerto" 


| Tela | "tela" nombre wwn 


| Máquina virtual de almacenamiento (SVM) | UUID del nombre de la "máquina virtual de almacenamiento" 
|===