---
sidebar: sidebar 
permalink: concept_about_applications.html 
keywords: applications, asset, cost 
summary: Comprender las aplicaciones utilizadas en el entorno de su empresa le ayudará a realizar un seguimiento del uso y los costos de los activos. 
---
= Seguimiento del uso de activos por aplicación
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Comprender las aplicaciones utilizadas en el entorno de su empresa le ayudará a realizar un seguimiento del uso y el costo de los activos.

Antes de poder rastrear los datos asociados con las aplicaciones que se ejecutan en su inquilino, primero debe definir esas aplicaciones y asociarlas con los activos adecuados.  Puede asociar aplicaciones con los siguientes activos: hosts, máquinas virtuales, volúmenes, volúmenes internos, qtrees, recursos compartidos e hipervisores.

Este tema proporciona un ejemplo de seguimiento del uso de máquinas virtuales que el equipo de marketing utiliza para su correo electrónico de Exchange.

Es posible que desee crear una tabla similar a la siguiente para identificar las aplicaciones utilizadas en su inquilino y anotar el grupo o la unidad de negocio que utiliza cada aplicación.

[cols="5*"]
|===


| Arrendatario | Línea de negocio | Unidad de negocio | Proyecto | Aplicaciones 


| NetApp | Almacenamiento de datos | Legal | Patentes | Administrador de identidad de Oracle, Oracle On Demand, PatentWiz 


| NetApp | Almacenamiento de datos | Marketing | Eventos de ventas | Exchange, Oracle Shared DataBase, Planificador de eventos BlastOff 
|===
La tabla muestra que el equipo de marketing utiliza la aplicación Exchange.  Queremos realizar un seguimiento del uso de sus máquinas virtuales para Exchange, de modo que podamos predecir cuándo necesitaremos agregar más almacenamiento.  Podemos asociar la aplicación Exchange con todas las máquinas virtuales de Marketing:

. Crea una aplicación llamada _Exchange_
. Vaya a *Consultas > +Nueva consulta* para crear una nueva consulta para máquinas virtuales (o seleccione una consulta de VM existente, si corresponde).
+
Suponiendo que todas las máquinas virtuales del equipo de marketing tienen un nombre que contiene la cadena “*mkt*”, cree su consulta para filtrar el nombre de la máquina virtual para “mkt”.

. Seleccione las máquinas virtuales.
. Asocie las máquinas virtuales con la aplicación _Exchange_ mediante *Acciones masivas > Agregar aplicaciones*.
. Seleccione la aplicación deseada y haga clic en *Guardar*.
. Cuando haya terminado, *Guarde* la consulta.

