---
sidebar: sidebar 
permalink: concept_telegraf_display_options.html 
keywords: telegraf, data, display, 
summary: Opciones de visualización de datos de Telegraf 
---
= Transformando las métricas
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Información sobre la infraestructura de datos proporciona diferentes opciones de *transformación* para ciertas métricas en widgets (específicamente, aquellas métricas llamadas “personalizadas” o métricas de integración, como de Kubernetes, datos avanzados de ONTAP, plugins de Telegraf, etc.), lo que le permite mostrar los datos de varias maneras. Al añadir medidas transformables a un widget, se presenta con una lista desplegable dando las siguientes opciones de transformación:

Ninguno: Los datos se muestran tal cual, sin manipulación.

Tasa: Valor actual dividido por el rango de tiempo desde la observación anterior.

Acumulativo: La acumulación de la suma de los valores anteriores y el valor actual.

Delta: La diferencia entre el valor de observación anterior y el valor actual.

Delta rate: Valor Delta dividido por el rango de tiempo desde la observación anterior.

Tasa Acumulada: Valor acumulativo dividido por el rango de tiempo desde la observación anterior.

Tenga en cuenta que la transformación de las métricas no cambia los datos subyacentes en sí, sino sólo la forma en que se muestran los datos.
