---
sidebar: sidebar 
permalink: concept_cs_api.html 
keywords: api, access, token, swagger 
summary: Workload Security incluye una potente API para la integración con otras aplicaciones, como CMDB. 
---
= API de seguridad de cargas de trabajo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La API de seguridad de carga de trabajo permite a los clientes y proveedores independientes de software (ISV) de NetApp integrar la seguridad de la carga de trabajo con otras aplicaciones, como CMDB u otros sistemas de emisión de boletos.

Requisitos para el acceso a API:

* Se utiliza un modelo de token de acceso de API para conceder acceso.
* La gestión de token de API la realizan los usuarios de Workload Security con la función de administrador.




== Documentación de API (Swagger)

La información más reciente de la API se encuentra iniciando sesión en Workload Security y navegando a *Admin > API Access*. Haga clic en el enlace *Documentación de API*. La documentación de la API se basa en Swagger, lo que proporciona una breve descripción e información de uso para la API y le permite probarla en su inquilino.


NOTE: Si llama a la API de actividad de Forensics, use la API cloudsecure_forensics.activities.*v2*. Si realiza varias llamadas a esta API, asegúrese de que las llamadas se realicen secuencialmente, no en paralelo. Varias llamadas paralelas pueden hacer que la API se agote.



== Tokens de acceso API

Antes de utilizar la API de seguridad de carga de trabajo, debe crear uno o más * tokens de acceso de API*. Los tokens de acceso conceden permisos de lectura. También puede establecer la caducidad de cada token de acceso.

Para crear un token de acceso:

* Haga clic en *Admin > API Access*
* Haga clic en *+símbolo de acceso de API*
* Introduzca *Nombre de símbolo*
* Especifique *caducidad de token*



NOTE: El token sólo estará disponible para copiar en el portapapeles y guardar durante el proceso de creación. Los tokens no se pueden recuperar una vez creados, por lo que se recomienda encarecidamente copiar el token y guardarlo en una ubicación segura. Se le pedirá que haga clic en el botón Copiar clave de acceso de API antes de cerrar la pantalla de creación de token.

Puede desactivar, activar y revocar tokens. Se pueden activar los tokens desactivados.

Los tokens conceden acceso a las API de propósito general desde la perspectiva del cliente, gestionando el acceso a las API en el ámbito de su propio inquilino.

La aplicación recibe un token de acceso después de que un usuario autentica correctamente y autoriza el acceso, a continuación, pasa el token de acceso como credencial cuando llama a la API de destino. El token pasado informa a la API de que el portador del token ha sido autorizado para acceder a la API y realizar acciones específicas en función del ámbito que se haya concedido durante la autorización.

El encabezado HTTP donde se pasa el token de acceso es *X-CloudInsights-ApiKey:*

Por ejemplo, utilice lo siguiente para recuperar activos de almacenamientos:

 curl https://<tenant_host_name>/rest/v1/cloudsecure/activities -H 'X-CloudInsights-ApiKey: <API_Access_Token>'
Donde _<API_Access_Token>_ es el token que ha guardado durante la creación de la clave de acceso de API.

Puede encontrar información detallada en el enlace _API Documentation_ en *Admin > API Access*.



== Script para extraer datos a través de la API

Los agentes de seguridad de carga de trabajo incluyen un script de exportación para facilitar las llamadas paralelas a la API de v2 dividiendo el rango de tiempo solicitado en lotes más pequeños.

El script está ubicado en _/opt/NetApp/cloudsecure/agent/export-script_. Un archivo README en el mismo directorio proporciona instrucciones de uso.

A continuación se muestra un comando de ejemplo para invocar el script:

[source]
----
python3 data-export.py --tenant_url <tenant id>.cs01.cloudinsights.netapp.com --access_key %ACCESS_KEY% --path_filter "<dir path>" --user_name "<user>" --from_time "01-08-2024 00:00:00" --to_time "31-08-2024 23:59:59" --iteration_interval 12 --num_workers 3
----
Parámetros Clave: - `--iteration_interval 12`: Divide el rango de tiempo solicitado en intervalos de 12 horas.  `--num_workers 3`- : Fetches estos intervalos en paralelo usando 3 hilos.
