---
sidebar: sidebar 
permalink: concept_telegraf_display_options.html 
keywords: telegraf, data, display, 
summary: Opciones de visualización de datos de Telegraf 
---
= Transformando métricas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Data Infrastructure Insights ofrece diferentes opciones de *transformación* para ciertas métricas en widgets (específicamente, aquellas métricas llamadas "Personalizadas" o Métricas de integración, como las de Kubernetes, ONTAP Advanced Data, complementos de Telegraf, etc.), lo que le permite mostrar los datos de varias maneras.  Al agregar métricas transformables a un widget, se le presenta un menú desplegable que ofrece las siguientes opciones de transformación:

Ninguno: Los datos se muestran tal como están, sin manipulación.

Tasa: Valor actual dividido por el rango de tiempo desde la observación anterior.

Acumulativo: La acumulación de la suma de los valores anteriores y el valor actual.

Delta: La diferencia entre el valor de observación anterior y el valor actual.

Tasa delta: valor delta dividido por el rango de tiempo desde la observación anterior.

Tasa acumulada: valor acumulado dividido por el rango de tiempo desde la observación anterior.

Tenga en cuenta que la transformación de métricas no cambia los datos subyacentes en sí, sino solo la forma en que se muestran los datos.
