---
sidebar: sidebar 
permalink: concept_cs_api.html 
keywords: api, access, token, swagger 
summary: Workload Security incluye una potente API para la integración con otras aplicaciones como CMDB. 
---
= API de seguridad de carga de trabajo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La API de seguridad de carga de trabajo permite a los clientes de NetApp y a los proveedores de software independientes (ISV) integrar la seguridad de carga de trabajo con otras aplicaciones, como CMDB u otros sistemas de tickets.

Requisitos para el acceso a la API:

* Se utiliza un modelo de token de acceso API para otorgar acceso.
* La gestión del token API la realizan los usuarios de Workload Security con el rol de administrador.




== Documentación de la API (Swagger)

La información más reciente sobre la API se puede encontrar iniciando sesión en Workload Security y navegando a *Admin > Acceso a API*.  Haga clic en el enlace *Documentación de API*.  La documentación de la API está basada en Swagger, lo que proporciona una breve descripción e información de uso de la API y le permite probarla en su inquilino.


NOTE: Si llama a la API de actividad forense, utilice la API cloudsecure_forensics.activities.*v2*.  Si realiza varias llamadas a esta API, asegúrese de que las llamadas se realicen secuencialmente, no en paralelo.  Varias llamadas paralelas pueden provocar que se agote el tiempo de espera de la API.



== Tokens de acceso a la API

Antes de utilizar la API de seguridad de carga de trabajo, debe crear uno o más *Tokens de acceso a API*.  Los tokens de acceso otorgan permisos de lectura.  También puede establecer la fecha de vencimiento para cada token de acceso.

Para crear un token de acceso:

* Haga clic en *Administrador > Acceso API*
* Haga clic en *+Token de acceso a la API*
* Ingrese *Nombre del token*
* Especifique *Expiración del token*



NOTE: Su token solo estará disponible para copiarlo al portapapeles y guardarlo durante el proceso de creación.  Los tokens no se pueden recuperar una vez creados, por lo que se recomienda copiar el token y guardarlo en una ubicación segura.  Se le pedirá que haga clic en el botón Copiar token de acceso a API antes de poder cerrar la pantalla de creación de token.

Puede deshabilitar, habilitar y revocar tokens.  Los tokens que están deshabilitados se pueden habilitar.

Los tokens otorgan acceso de propósito general a las API desde la perspectiva del cliente, administrando el acceso a las API en el alcance de su propio inquilino.

La aplicación recibe un token de acceso después de que un usuario se autentica y autoriza el acceso con éxito, luego pasa el token de acceso como credencial cuando llama a la API de destino.  El token pasado informa a la API que el portador del token ha sido autorizado a acceder a la API y realizar acciones específicas según el alcance que se le otorgó durante la autorización.

El encabezado HTTP donde se pasa el token de acceso es *X-CloudInsights-ApiKey:*

Por ejemplo, utilice lo siguiente para recuperar activos de almacenamiento:

 curl https://<Workload Security tenant>/rest/v1/cloudsecure/activities -H 'X-CloudInsights-ApiKey: <API_Access_Token>'
Donde _<API_Access_Token>_ es el token que guardó durante la creación de la clave de acceso a la API y _<Workload Security Tenant>_ es la URL del inquilino de su entorno de Workload Security.

Puede encontrar información detallada en el enlace _Documentación de API_ en *Admin > Acceso API*.



== Script para extraer datos a través de la API

Los agentes de seguridad de carga de trabajo incluyen un script de exportación para facilitar las llamadas paralelas a la API v2 al dividir el rango de tiempo solicitado en lotes más pequeños.

El script se encuentra en _/opt/netapp/cloudsecure/agent/export-script_.  Un archivo README en el mismo directorio proporciona instrucciones de uso.

A continuación se muestra un ejemplo de comando para invocar el script:

[source]
----
python3 data-export.py --tenant_url <Workload Security tenant> --access_key %ACCESS_KEY% --path_filter "<dir path>" --user_name "<user>" --from_time "01-08-2024 00:00:00" --to_time "31-08-2024 23:59:59" --iteration_interval 12 --num_workers 3
----
Parámetros clave: - `--iteration_interval 12` :Divide el rango de tiempo solicitado en intervalos de 12 horas.  - `--num_workers 3` :Obtiene estos intervalos en paralelo utilizando 3 subprocesos.
