---
sidebar: sidebar 
permalink: concept_import_from_dashboard_gallery.html 
summary: Puede importar paneles recomendados para ayudarle a responder preguntas de información empresarial. 
keywords: dashboard, gallery, import 
---
= Importando desde la galería de paneles
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Data Infrastructure Insights proporciona una serie de consolas recomendadas para proporcionar información empresarial sobre sus datos. Cada panel de control contiene widgets diseñados para ayudar a responder una pregunta en particular o resolver un problema particular relevante para los datos que se recopilan actualmente en su inquilino.

Para importar un panel desde la galería, haga lo siguiente:

. Seleccione *Paneles > Paneles*
. Haga clic en *+from Gallery*
+
Aparecerá una lista de *Paneles recomendados*. Cada panel tiene un nombre con una pregunta concreta que el panel puede ayudarle a resolver. Las consolas están disponibles para ofrecer respuesta a las preguntas sobre diferentes tipos de objetos, incluidos AWS, NetApp, almacenamiento, VMware, y otros

. Seleccione uno o más paneles de la lista y haga clic en *Agregar paneles*. Estos paneles ahora aparecen en su lista de paneles.


Además de los paneles recomendados, también puede elegir importar *Paneles adicionales* que no sean relevantes para los datos actuales. Por ejemplo, si no tiene actualmente ningún recopilador de datos de almacenamiento instalado pero está planeando configurar algunos en el futuro, puede que decida importar los paneles relevantes para el almacenamiento. Estos paneles estarán disponibles para su visualización, pero es posible que no muestren ningún dato relevante hasta que se configure al menos un recopilador de datos de almacenamiento.

La importación desde la galería de paneles está disponible para los usuarios con la función Administrador o propietario de cuenta.
