---
sidebar: sidebar 
permalink: concept_cs_event_rate_checker.html 
summary: Este script se puede ejecutar para verificar la tasa de eventos en el SVM antes de instalar un DSC ONTAP SVM 
keywords: event, checker, rate, sizing, cloud secure 
---
= Comprobador de tasa de eventos de SVM (Guía de dimensionamiento de agentes)
:hardbreaks:
:allow-uri-read: 


[role="lead"]
El verificador de tasa de eventos se utiliza para verificar la tasa de eventos combinados NFS/SMB en el SVM antes de instalar un recopilador de datos SVM de ONTAP , para ver cuántos SVM podrá monitorear una máquina agente.  Utilice el Comprobador de tasa de eventos como guía de tamaño para ayudar a planificar su entorno de seguridad.

Un agente puede admitir hasta un máximo de 50 recopiladores de datos.



== Requisitos:

* IP del clúster
* Nombre de usuario y contraseña del administrador del clúster



NOTE: Al ejecutar este script, no debe ejecutarse ningún recopilador de datos ONTAP SVM para el SVM para el cual se está determinando la tasa de eventos.

Pasos:

. Instale el agente siguiendo las instrucciones de CloudSecure.
. Una vez instalado el agente, ejecute el script _server_data_rate_checker.sh_ como usuario sudo:
+
 /opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh
. Este script requiere que _sshpass_ esté instalado en la máquina Linux.  Hay dos formas de instalarlo:
+
.. Ejecute el siguiente comando:
+
 linux_prompt> yum install sshpass
.. Si eso no funciona, descargue _sshpass_ a la máquina Linux desde la web y ejecute el siguiente comando:
+
 linux_prompt> rpm -i sshpass


. Proporcione los valores correctos cuando se le solicite.  Vea un ejemplo a continuación.
. El script tardará aproximadamente 5 minutos en ejecutarse.
. Una vez completada la ejecución, el script imprimirá la tasa de eventos desde el SVM.  Puede verificar la tasa de eventos por SVM en la salida de la consola:
+
 “Svm svm_rate is generating 100 events/sec”.


Cada recopilador de datos SVM de Ontap se puede asociar con un único SVM, lo que significa que cada recopilador de datos podrá recibir la cantidad de eventos que genera un único SVM.

Tenga en cuenta lo siguiente:

A) Utilice esta tabla como guía general de tallas.  Puede aumentar la cantidad de núcleos y/o memoria para aumentar la cantidad de recopiladores de datos admitidos, hasta un máximo de 50 recopiladores de datos:

|===


| Configuración de la máquina del agente | Número de recopiladores de datos de SVM | Tasa máxima de eventos que la máquina del agente puede manejar 


| 4 núcleos, 16 GB | 10 recopiladores de datos | 20K eventos/seg 


| 4 núcleos, 32 GB | 20 recopiladores de datos | 20K eventos/seg 
|===
B) Para calcular el total de eventos, agregue los eventos generados para todos los SVM para ese agente.

C) Si el script no se ejecuta durante las horas pico o si el tráfico pico es difícil de predecir, mantenga un margen de tasa de eventos del 30 %.

B + C debe ser menor que A, de lo contrario, la máquina del Agente no podrá realizar el monitoreo.

En otras palabras, la cantidad de recopiladores de datos que se pueden agregar a una sola máquina agente debe cumplir con la siguiente fórmula:

 Sum of all Event rate of all Data Source Collectors + Buffer Event rate of 30% < 20000 events/second
Ver ellink:concept_cs_agent_requirements.html["Requisitos del agente"] Página para requisitos previos y requisitos adicionales.



== Ejemplo

Digamos que tenemos tres SVMS que generan tasas de eventos de 100, 200 y 300 eventos por segundo, respectivamente.

Aplicamos la fórmula:

....
 (100+200+300) + [(100+200+300)*30%] = 600+180 = 780events/sec
780 events/second is < 20000 events/second, so the 3 SVMs can be monitored via one agent box.
....
La salida de la consola está disponible en la máquina del Agente en el nombre de archivo __fpolicy_stat_<SVM Name>.log__ en el directorio de trabajo actual.

El script puede dar resultados erróneos en los siguientes casos:

* Se proporcionaron credenciales, IP o nombre SVM incorrectos.
* Una fpolicy ya existente con el mismo nombre, número de secuencia, etc. generará un error.
* El script se detiene abruptamente mientras se ejecuta.


A continuación se muestra un ejemplo de ejecución de script:

 [root@ci-cs-data agent]# /opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh
....
Enter the cluster ip: 10.192.139.166
Enter the username to SSH: admin
Enter the password:
Getting event rate for NFS and SMB events.
Available SVMs in the Cluster
-----------------------------
QA_SVM
Stage_SVM
Qa-fas8020
Qa-fas8020-01
Qa-fas8020-02
audit_svm
svm_rate
vs_new
vs_new2
....
....
-----------------------------
Enter [1/5] SVM name to check (press enter to skip): svm_rate
Enter [2/5] SVM name to check (press enter to skip): audit_svm
Enter [3/5] SVM name to check (press enter to skip):
Enter [4/5] SVM name to check (press enter to skip):
Enter [5/5] SVM name to check (press enter to skip):
Running check for svm svm_rate...
Running check for svm audit_svm...
Waiting 5 minutes for stat collection
Stopping sample svm_rate_sample
Stopping sample audit_svm_sample
fpolicy stats of svm svm_rate is saved in fpolicy_stat_svm_rate.log
Svm svm_rate is generating 100 SMB events/sec and 100 NFS events/sec
Overall svm svm_rate is generating 200 events/sec
fpolicy stats of svm audit_svm is saved in fpolicy_stat_audit_svm.log
Svm audit_svm is generating 200 SMB events/sec and 100 NFS events/sec
Overall svm audit_svm is generating 300 events/sec
....
 [root@ci-cs-data agent]#


== Solución de problemas

|===


| Pregunta | Respuesta 


| Si ejecuto este script en una SVM que ya está configurada para Seguridad de carga de trabajo, ¿solo utiliza la configuración fpolicy existente en la SVM o configura una temporal y ejecuta el proceso? | El verificador de tasa de eventos puede funcionar correctamente incluso para una SVM ya configurada para seguridad de carga de trabajo.  No debería haber ningún impacto. 


| ¿Puedo aumentar la cantidad de SVM en las que se puede ejecutar el script? | Sí. Simplemente edite el script y cambie el número máximo de SVM de 5 a cualquier número deseado. 


| Si aumento la cantidad de SVM, ¿aumentará el tiempo de ejecución del script? | No. El script se ejecutará durante un máximo de 5 minutos, incluso si se aumenta el número de SVM. 


| ¿Puedo aumentar la cantidad de SVM en las que se puede ejecutar el script? | Sí. Debes editar el script y cambiar el número máximo de SVM de 5 a cualquier número deseado. 


| Si aumento la cantidad de SVM, ¿aumentará el tiempo de ejecución del script? | No. El script se ejecutará durante un máximo de 5 minutos, incluso si se aumenta la cantidad de SVM. 


| ¿Qué sucede si ejecuto el Verificador de tasa de eventos con un agente existente? | Ejecutar el verificador de tasa de eventos en un agente ya existente puede provocar un aumento en la latencia en la SVM.  Este aumento será de naturaleza temporal mientras se ejecuta el Comprobador de tasa de eventos. 
|===