---
sidebar: sidebar 
permalink: concept_import_from_dashboard_gallery.html 
summary: Importa paneles preconstruidos desde la galería para obtener rápidamente información empresarial, o importa paneles personalizados que hayas exportado para compartir configuraciones entre distintos tenants. 
keywords: dashboard, gallery, import, export 
---
= Importación de paneles
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Accede a los paneles predefinidos de la galería para obtener rápidamente información sobre tu infraestructura, o importa paneles personalizados que hayas exportado desde otros tenants. Los paneles de la galería están adaptados a los recopiladores de datos de tu entorno y diseñados para responder a preguntas empresariales específicas, mientras que los paneles exportados te permiten compartir configuraciones útiles entre varios tenants.



[[importing-from-the-dashboard-gallery]]
== Importar desde la Galería del Panel de Control

Para importar un panel desde la galería, haga lo siguiente:

. Seleccione *Observabilidad > Explorar > Todos los paneles*
. Haga clic en *+Importar panel* y seleccione _Importar desde galería_.
+
Se muestra una lista de *Paneles recomendados*, según los recopiladores de datos de su entorno. Hay paneles disponibles para ayudar a responder preguntas sobre diferentes tipos de objetos, incluidos AWS, NetApp, almacenamiento, VMware y otros.

. Seleccione uno o más paneles de la lista y haga clic en *Agregar paneles*. Estos paneles se mostrarán en su lista de paneles.


Además de los paneles recomendados, también puede optar por importar *Paneles adicionales* que no sean relevantes para sus datos actuales.  Por ejemplo, si no tiene recopiladores de datos de almacenamiento instalados actualmente pero planea configurar algunos en el futuro, aún puede optar por importar los paneles relevantes para el almacenamiento.  Estos paneles estarán disponibles para su visualización, pero es posible que no muestren ningún dato relevante hasta que se configure al menos un recopilador de datos de almacenamiento.

La importación desde la galería del panel está disponible para usuarios con rol de Administrador o Propietario de cuenta.



[[importing-an-exported-dashboard]]
== Importar un panel exportado

Para *exportar* un panel, en la página *Observabilidad > Explorar > Todos los paneles*, haga clic en el menú a la derecha del panel y seleccione _Exportar_. También puede seleccionar varios paneles y elegir _Exportar_ en el menú desplegable _Acciones masivas_. Los paneles se guardan en un archivo .ZIP en su sistema local.

Para *importar* el panel, navegue hasta el inquilino deseado y haga lo siguiente:

. Seleccione *Observabilidad > Explorar > Todos los paneles*
. Haga clic en *+Importar panel* y seleccione _Importar desde archivo_. Seleccione el .ZIP del archivo que exportó anteriormente. Los paneles se importarán y se mostrarán en su lista de paneles. Tenga en cuenta que si está importando un panel con el mismo nombre que un panel existente, se agregará un "(2)" al nombre del panel.

