---
sidebar: sidebar 
permalink: cs_intro.html 
keywords: CloudSecure, Cloud Secure 
summary: Descripción general 
---
= Acerca de la seguridad de carga de trabajo de almacenamiento
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Información de la infraestructura de datos Seguridad de cargas de trabajo del almacenamiento (anteriormente Cloud Secure) ayuda a proteger sus datos con inteligencia procesable sobre amenazas internas. Proporciona control y visibilidad centralizados de todos los accesos a datos corporativos en los entornos de cloud híbrido para garantizar la consecución de los objetivos de seguridad y cumplimiento de normativas.



== Visibilidad

Obtenga una visibilidad y control centralizados del acceso del usuario a los datos corporativos más importantes almacenados en sus instalaciones o en el cloud.

Sustituye herramientas y procesos manuales que no ofrecen una visibilidad precisa y puntual del acceso a los datos y el control. Workload Security funciona de forma única en sistemas de almacenamiento en la nube y en las instalaciones para proporcionar alertas en tiempo real sobre el comportamiento de los usuarios malintencionados.



== Protección

Proteja los datos de su organización frente a un uso inadecuado por parte de usuarios malintencionados o en riesgo mediante el aprendizaje automático avanzado y la detección de anomalías.

Le avisa de cualquier acceso anormal a los datos mediante el aprendizaje automático avanzado y la detección de anomalías en el comportamiento del usuario.



== Cumplimiento de normativas

Garantice el cumplimiento de normativas de la empresa mediante la auditoría del acceso de los usuarios a los datos confidenciales de la empresa almacenados en las instalaciones o en el cloud.
