---
sidebar: sidebar 
permalink: cs_intro.html 
keywords: CloudSecure, Cloud Secure 
summary: Descripción general 
---
= Acerca de la seguridad de la carga de trabajo de almacenamiento
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights Storage Workload Security (anteriormente Cloud Secure) ayuda a proteger sus datos con inteligencia práctica sobre amenazas internas.  Proporciona visibilidad y control centralizados de todo el acceso a datos corporativos en entornos de nube híbrida para garantizar que se cumplan los objetivos de seguridad y cumplimiento.



== Visibilidad

Obtenga visibilidad y control centralizados del acceso de los usuarios a sus datos corporativos críticos almacenados localmente o en la nube.

Reemplace las herramientas y los procesos manuales que no brindan visibilidad oportuna y precisa del acceso y control de los datos.  Workload Security funciona únicamente en sistemas de almacenamiento locales y en la nube para brindarle alertas en tiempo real sobre comportamientos maliciosos de usuarios.



== Protection

Proteja los datos de la organización contra el uso indebido por parte de usuarios maliciosos o comprometidos mediante aprendizaje automático avanzado y detección de anomalías.

Le alerta sobre cualquier acceso anormal a los datos a través del aprendizaje automático avanzado y la detección de anomalías en el comportamiento del usuario.



== Cumplimiento

Garantice el cumplimiento corporativo auditando el acceso de los usuarios a sus datos corporativos críticos almacenados localmente o en la nube.
