---
sidebar: sidebar 
permalink: cs_notifications_email.html 
summary: Configure notificaciones por correo electrónico para recibir alertas sobre posibles ataques, advertencias de seguridad y el estado del agente/recopilador de datos en tiempo real. 
keywords: email, notifications, alerts, warnings, attacks 
---
= Configuración de notificaciones por correo electrónico para alertas, advertencias y el estado del recopilador de origen de datos/agente
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las notificaciones por correo electrónico le permiten mantenerse informado sobre posibles ataques, advertencias de seguridad y problemas de estado de la infraestructura a medida que ocurren. Configure las direcciones de correo electrónico de los destinatarios en la configuración de Administración > Notificaciones para recibir alertas en tiempo real adaptadas a las responsabilidades de cada destinatario.



== Alertas y advertencias de posibles ataques

Para enviar notificaciones de alerta de _Ataque potencial_, ingrese las direcciones de correo electrónico de los destinatarios en la sección _Enviar alertas de ataque potencial_.  Se envían notificaciones por correo electrónico a la lista de destinatarios de la alerta para cada acción relacionada con la alerta.

Para enviar notificaciones de _Advertencia_, ingrese las direcciones de correo electrónico de los destinatarios en la sección _Enviar alertas de advertencia_.



== Monitoreo del estado del agente y del recopilador de datos

Puede supervisar la salud de los agentes y las fuentes de datos a través de notificaciones.

Para recibir notificaciones en caso de que un agente o recopilador de fuente de datos no esté funcionando, ingrese las direcciones de correo electrónico de los destinatarios en la sección _Alertas de estado de recopilación de datos_.

Tenga en cuenta lo siguiente:

* Las alertas de salud se enviarán solo después de que el agente/recaudador deje de informar durante al menos una hora.
* Solo se envía una notificación por correo electrónico a los destinatarios previstos en un período determinado de 24 horas, incluso si el agente o el recopilador de datos está desconectado durante un período más prolongado.
* En caso de falla del Agente, se enviará una alerta (no una por recolector).  El correo electrónico incluirá una lista de todos los SVM afectados.
* La falla de recopilación de Active Directory se informa como una advertencia; no afecta la detección de amenazas.
* La lista de configuración de Primeros pasos ahora incluye una nueva fase _Configurar notificaciones por correo electrónico_.




== Notificaciones de actualización del agente receptor y del recopilador de datos

* Ingrese el/los ID de correo electrónico en “Alertas de salud de recopilación de datos”.
* Se habilita la casilla de verificación “Habilitar notificaciones de actualización”.
* Las notificaciones por correo electrónico de actualización del agente y del recopilador de datos se envían a las direcciones de correo electrónico un día antes de la actualización planificada.




== Solución de problemas

|===
| *Problema:* | *Prueba esto:* 


| Las direcciones de correo electrónico están presentes en las “Alertas de salud del recopilador de datos”, sin embargo, no recibo notificaciones. | Los correos electrónicos de notificación se envían desde el dominio de NetApp Data Infrastructure Insights , es decir, desde _accounts@service.cloudinsights.netapp.com_.  Algunas empresas bloquean los correos electrónicos entrantes si provienen de un dominio externo.  Asegúrese de que las notificaciones externas de los dominios de NetApp Data Infrastructure Insights estén en la lista blanca. 
|===