---
sidebar: sidebar 
permalink: faq-config-support.html 
keywords: FAQ, Frequently asked questions, questions, configuration, 
summary:  
---
= Configuración y dispositivos compatibles
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Estas preguntas frecuentes responden preguntas comunes sobre la configuración de Data Infrastructure Insights y los dispositivos compatibles.



== ¿ Data Infrastructure Insights realiza cambios en mi entorno?

No. Data Infrastructure Insights es una herramienta de solo lectura que recopila información sobre su entorno.  Data Infrastructure Insights nunca realiza cambios en sus activos o configuraciones.



== ¿Qué nivel de permiso de acceso necesita Data Infrastructure Insights para mis dispositivos?

En la mayoría de los casos donde el dispositivo lo admite, todo lo que se requiere es un acceso de solo lectura.  Hay algunas soluciones que no permiten acceso de solo lectura y, por lo tanto, requerirían los permisos elevados adecuados.



== ¿Con qué frecuencia Data Infrastructure Insights recopila información?

Data Infrastructure Insights normalmente recopila datos de rendimiento cada 5 minutos y descubre construcciones lógicas y físicas cada media hora.  Data Infrastructure Insights establece los intervalos de sondeo predeterminados de acuerdo con las mejores prácticas sugeridas y la escalabilidad, pero permite al usuario un control total sobre estos intervalos.



== ¿Cuál es el impacto de Data Infrastructure Insights en mi entorno?

Las comunicaciones IP pasivas, fuera de banda y sin agente de Data Infrastructure Insights ayudan a minimizar la configuración, el mantenimiento y el impacto en el ecosistema del centro de datos.  El equipo de desarrollo de rendimiento de Data Infrastructure Insights toma grandes medidas para minimizar cualquier impacto en el rendimiento del centro de datos en las actividades de monitoreo del rendimiento en sí.  El impacto se considera insignificante en entornos operativos normales y puede relajarse o reducirse en plataformas tecnológicas muy utilizadas o de bajo rendimiento.  Consulte la Guía de instalación de Data Infrastructure Insights para obtener más información.



== ¿Cómo puedo enumerar todos los hosts/VM en Data Infrastructure Insights?

El conjunto de widgets y posibilidades de listado de consultas de Data Infrastructure Insights se puede utilizar para proporcionar listados de estilo de inventario para los activos del centro de datos.  Los listados de máquinas virtuales hasta los ejes y numerosas construcciones intermedias se pueden poner a disposición de consultas, widgets, paneles e informes de almacenamiento de datos, y se puede acceder a ellos a través de la API RESTful.



== ¿ Data Infrastructure Insights proporciona el mismo tipo de soporte para hosts no hipervisores relacionados (es decir, servidores físicos)?

Los hipervisores como VMware proporcionan información detallada sobre los hosts ESXI y sus máquinas virtuales (VM).  Para los servidores físicos, Data Infrastructure Insights recopila métricas hasta el HBA del host.  Data Infrastructure Insights emplea un método único en el que descubre servidores físicos utilizando una tecnología pendiente de patente.  Una vez que se descubren el almacenamiento y/o los conmutadores, los nombres de host de los servidores físicos se incluyen dentro de la información de alias de la estructura.  Data Infrastructure Insights selecciona estos nombres de host, los compara en DNS y los lleva automáticamente a Data Infrastructure Insights.  Esta técnica minimiza en gran medida la necesidad de actualizaciones de entradas manuales y mantenimiento del inventario de herramientas.



== ¿ Data Infrastructure Insights proporciona la misma profundidad de métricas de dispositivos (paridad) en entornos heterogéneos?

Existen distintos grados de estandarización, puntos en común y nomenclatura entre plataformas de terceros y tecnologías de proveedores.  Data Infrastructure Insights intenta normalizar la información sobre capacidad y rendimiento en un marco consistente.  Algunas métricas de capacidad y rendimiento se proporcionan de forma nativa desde los contadores del dispositivo, como IOP, latencia y capacidad bruta.  Cuando no se proporcionan contadores, Data Infrastructure Insights puede intentar resumir los valores (por ejemplo, totalizando las IOP o las capacidades de los volúmenes subyacentes) y, en los casos en que ninguno esté disponible, Data Infrastructure Insights intentará derivar los valores de las métricas a través de varios algoritmos computacionales.  Data Infrastructure Insights proporciona una capacidad de integración SNMP genérica para incorporar métricas adicionales que Data Infrastructure Insights actualmente no recopila.



== ¿ Data Infrastructure Insights admite conmutadores de canal de fibra?

Sí, además de recopilar datos de sus activos de almacenamiento, Data Infrastructure Insights también adquiere datos de inventario y rendimiento de los conmutadores Cisco, Brocade y QLogic en su inquilino.



== ¿Están disponibles vistas de topología de toda la infraestructura?  ¿ Data Infrastructure Insights muestra “visibilidad de extremo a extremo”?

Sí, Data Infrastructure Insights descubre y mapea dinámicamente las construcciones lógicas y físicas, brindando una vista topológica interactiva de extremo a extremo de computación, estructuras, virtualizadores y almacenamiento back-end.  Los íconos de topología permiten una navegación rápida hacia los recursos afectados y ayudan en la identificación de cargas de trabajo y violaciones en entornos de almacenamiento compartido.
