---
sidebar: sidebar 
permalink: forensic_user_overview.html 
keywords: Forensic, user, user, activity 
summary: detalle del usuario forense 
---
= Descripción general del usuario forense
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La información de cada usuario se proporciona en la Descripción general del usuario.  Utilice estas vistas para comprender las características del usuario, las entidades asociadas y las actividades recientes.



== Perfil de usuario

La información del perfil de usuario incluye información de contacto y ubicación del usuario.  El perfil proporciona la siguiente información:

* Nombre del usuario
* Dirección de correo electrónico del usuario
* Administrador de usuarios
* Contacto telefónico del usuario
* Ubicación del usuario




== Comportamiento del usuario

La información sobre el comportamiento del usuario identifica las actividades y operaciones recientes realizadas por el usuario.  Esta información incluye:

* Actividad reciente
+
** Última ubicación de acceso
** Gráfico de actividad
** Alertas




* Operaciones de los últimos siete días
+
** Número de operaciones






== Intervalo de actualización

La lista de usuarios se actualiza cada 12 horas.



== Política de retención

Si no se actualiza nuevamente, la lista de usuarios se conserva durante 13 meses.  Después de 13 meses, los datos serán eliminados.  Si se elimina su entorno de seguridad de carga de trabajo, se eliminarán todos los datos asociados con el entorno.
