---
sidebar: sidebar 
permalink: index.html 
summary: Bienvenido al portal de documentación de Data Infrastructure Insights. 
keywords:  
---
= Documentación de Data Infrastructure Insights
:hardbreaks:
:allow-uri-read: 


[role="lead"]
NetApp Data Infrastructure Insights (anteriormente Cloud Insights) es una herramienta de monitoreo de infraestructura en la nube que le brinda visibilidad de su infraestructura completa. Con Data Infrastructure Insights, puede supervisar, solucionar problemas y optimizar todos sus recursos, incluidas sus nubes públicas y sus centros de datos privados.



== ¿Qué puede hacer Data Infrastructure Insights por mí?

Data Infrastructure Insights proporciona monitoreo multicloud híbrido, lo que le brinda capacidad de observación completa de la infraestructura y las cargas de trabajo.

* Recopiladores de datos para infraestructuras y cargas de trabajo heterogéneas, incluido Kubernetes
* Recopilador Telegraf abierto y API abiertas para una fácil integración
* Alertas y notificaciones completas
* Aprendizaje automático para obtener información inteligente
* Optimizar la utilización de recursos
* Paneles de control integrados o personalizables con filtros avanzados para minimizar el ruido de la pantalla y responder preguntas
* Descubra la salud de sus operaciones de almacenamiento de ONTAP 
* Proteja su activo empresarial más valioso, los datos, del ransomware o ataques de destrucción de datos.


'''


== Empezando

* ¿Cómo hago?link:task_cloud_insights_onboarding_1.html["*Comienza*"] ¿con Data Infrastructure Insights?
* Estoy registrado  ¿Y ahora qué hago?link:task_getting_started_with_cloud_insights.html["Adquisición de datos"] link:concept_user_roles.html["Configuración de usuarios"]
* ¡Impresionante!  ¿Que sigue?link:task_defining_annotations.html["Preparación de activos: Anotaciones"] link:concept_querying_assets.html["Cómo encontrar los activos que desea: consulta"] link:concept_dashboards_overview.html["Ver los datos que desea: Paneles de control"] link:task_create_monitor.html["Monitoreo y alertas"] link:task_cs_getting_started.html["Protección de datos"]
* ¡Esto es una cosa fantástica!  Estoy listo paralink:concept_subscribing_to_cloud_insights.html["*suscribir*"] .

