---
sidebar: sidebar 
permalink: insights_overview.html 
keywords: insight, greedy, degraded, impacted, impacting, impactful, impact, resources, consuming, workload, ttf, time to full, k8s, kubernetes, namespace 
summary: Insights le brinda una visión del uso y las tendencias de los recursos. 
---
= Perspectivas
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Los conocimientos le permiten analizar aspectos como el uso de recursos y cómo afecta a otros recursos, o bien, realizar análisis de tiempo hasta completar el trabajo.

Hay una serie de información disponible.  Vaya a *Paneles > Insights* para comenzar a explorar. Puede ver los Insights activos (Insights que se están produciendo actualmente) en la pestaña principal, o los Insights inactivos en la pestaña _Insights inactivos_.  Las perspectivas inactivas son aquellas que anteriormente estaban activas pero que ya no ocurren.



== Tipos de información



=== Recursos compartidos bajo presión

Las cargas de trabajo de alto impacto pueden reducir el rendimiento de otras cargas de trabajo en un recurso compartido.  Esto pone bajo presión el recurso compartido.  Data Infrastructure Insights proporciona herramientas para ayudarlo a investigar la saturación de recursos y el impacto en su inquilino.link:insights_shared_resources_under_stress.html["Más información"]



=== Los espacios de nombres de Kubernetes se están quedando sin espacio

La información sobre espacios de nombres de Kubernetes que se quedan sin espacio le brinda una visión de las cargas de trabajo en sus espacios de nombres de Kubernetes que corren el riesgo de quedarse sin espacio, con una estimación de la cantidad de días restantes antes de que cada espacio se llene.link:insights_k8s_namespaces_running_out_of_space.html["Más información"]



=== Recupere el almacenamiento en frío de ONTAP

La información _Reclaim ONTAP Cold Storage_ proporciona datos sobre la capacidad de frío, los posibles ahorros de costos y energía y las acciones recomendadas para los volúmenes en los sistemas ONTAP .link:insights_reclaim_ontap_cold_storage.html["Más información"]


NOTE: Esta es una función de _vista previa_ y puede cambiar con el tiempo a medida que se realicen mejoras. link:/concept_preview_features.html["Más información"] Acerca de las funciones de vista previa de Data Infrastructure Insights .
