---
permalink: legal-notices.html 
sidebar: sidebar 
keywords:  
summary:  
---
= Avisos legales
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Los avisos legales proporcionan acceso a las declaraciones de copyright, marcas comerciales, patentes y mucho más.



== Copyright

link:https://www.netapp.com/company/legal/copyright/["https://www.netapp.com/company/legal/copyright/"^]



== Marcas comerciales

NETAPP, el logotipo de NETAPP y las marcas enumeradas en la página de marcas comerciales de NetApp son marcas comerciales de NetApp, Inc. Los demás nombres de empresas y productos son marcas comerciales de sus respectivos propietarios.

link:https://www.netapp.com/company/legal/trademarks/["https://www.netapp.com/company/legal/trademarks/"^]



== Estadounidenses

Puede encontrar una lista actual de las patentes propiedad de NetApp en:

link:https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf["https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf"^]



== Política de privacidad

link:https://www.netapp.com/company/legal/privacy-policy/["https://www.netapp.com/company/legal/privacy-policy/"^]



== Código abierto

Los archivos de aviso proporcionan información sobre derechos de autor y licencias de terceros utilizados en el software de NetApp .

link:media/DII_Notice-Sept_2025.pdf["Aviso para información sobre la infraestructura de datos (antes Cloud Insights)"]

link:media/WS_Notice-Sept_2025.pdf["Aviso de seguridad de carga de trabajo (anteriormente Cloud Secure)"]
