---
sidebar: sidebar 
permalink: reporting_creating_custom_reports.html 
summary: 'Uso de herramientas de creación de informes para crear informes personalizados ("ad-hoc")' 
keywords: reporting, cognos, data warehouse, dwh, ad-hoc, custom 
---
= Creación de informes personalizados
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Puede utilizar las herramientas de creación de informes para crear informes personalizados.  Después de crear informes, puede guardarlos y ejecutarlos según una programación regular.  Los resultados de los informes se pueden enviar automáticamente por correo electrónico a usted y a otras personas.


NOTE: La función de informes está disponible en Data Infrastructure Insightslink:concept_subscribing_to_cloud_insights.html["Edición Premium"] .

Los ejemplos de esta sección muestran el siguiente proceso, que se puede utilizar para cualquiera de los modelos de datos de informes de Data Infrastructure Insights :

* Identificar una pregunta que se responderá con un informe
* Determinar los datos necesarios para respaldar los resultados
* Selección de elementos de datos para el informe


Antes de diseñar su informe personalizado, deberá completar algunas tareas previas.  Si no completa estos, los informes podrían ser inexactos o incompletos.

Por ejemplo, si no finaliza el proceso de identificación del dispositivo, sus informes de capacidad no serán precisos.  O bien, si no termina de configurar las anotaciones (como niveles, unidades de negocio y centros de datos), sus informes personalizados podrían no informar con precisión los datos de su dominio o podrían mostrar "N/D" para algunos puntos de datos.

Antes de diseñar sus informes, complete las siguientes tareas:

* Configurar todolink:task_configure_data_collectors.html["recopiladores de datos"] adecuadamente.
* Ingrese anotaciones (como niveles, centros de datos y unidades de negocio) en los dispositivos y recursos de su inquilino.  Es beneficioso tener anotaciones estables antes de generar informes, porque Data Infrastructure Insights Reporting recopila información histórica.




== Proceso de creación de informes

El proceso de creación de informes personalizados (también llamados "ad hoc") implica varias tareas:

* Planifique los resultados de su informe.
* Identifique datos que respalden sus resultados.
* Seleccione el modelo de datos (por ejemplo, modelo de datos de devolución de cargo, modelo de datos de inventario, etc.) que contiene los datos.
* Seleccionar elementos de datos para el informe.
* Opcionalmente, formatea, ordena y filtra los resultados del informe.




=== Planificación de los resultados de su informe personalizado

Antes de abrir las herramientas de creación de informes, es posible que desee planificar los resultados que desea obtener del informe.  Con las herramientas de creación de informes, puede crear informes fácilmente y es posible que no necesite mucha planificación; sin embargo, es una buena idea obtener una idea del solicitante del informe sobre los requisitos del mismo.

* Identifique la pregunta exacta que desea responder. Por ejemplo:
+
** ¿Cuánta capacidad me queda?
** ¿Cuáles son los costos de devolución de cargo por unidad de negocio?
** ¿Cuál es la capacidad por nivel para garantizar que las unidades de negocio estén alineadas en el nivel de almacenamiento adecuado?
** ¿Cómo puedo prever los requisitos de energía y refrigeración?  (Agregue metadatos personalizados agregando anotaciones a los recursos).


* Identifique los elementos de datos que necesita para respaldar la respuesta.
* Identifique las relaciones entre los datos que desea ver en la respuesta.  No incluya relaciones ilógicas en su pregunta, por ejemplo, "Quiero ver los puertos relacionados con la capacidad".
* Identifique cualquier cálculo necesario sobre los datos.
* Determinar qué tipos de filtrado son necesarios para limitar los resultados.
* Determinar si necesita utilizar datos actuales o históricos.
* Determine si necesita establecer privilegios de acceso a los informes para limitar los datos a audiencias específicas.
* Identifique cómo se distribuirá el informe.  Por ejemplo, ¿debería enviarse por correo electrónico según un cronograma establecido o incluirse en el área de carpeta de contenido del equipo?
* Determinar quién mantendrá el informe.  Esto podría afectar la complejidad del diseño.
* Crear una maqueta del informe.




=== Consejos para diseñar informes

Hay varios consejos que pueden resultar útiles al diseñar informes.

* Determinar si necesita utilizar datos actuales o históricos.
+
La mayoría de los informes solo necesitan informar sobre los últimos datos disponibles en Data Infrastructure Insights.

* Los informes de Data Infrastructure Insights proporcionan información histórica sobre la capacidad y el rendimiento, pero no sobre el inventario.
* Todo el mundo ve todos los datos; sin embargo, es posible que sea necesario limitar los datos a audiencias específicas.
+
Para segmentar la información para diferentes usuarios, puede crear informes y establecer permisos de acceso para ellos.





== Modelos de datos de informes

Data Infrastructure Insights incluye varios modelos de datos entre los que puede seleccionar informes predefinidos o crear su propio informe personalizado.

Cada modelo de datos contiene un almacén de datos simple y un almacén de datos avanzado:

* El almacén de datos simple proporciona acceso rápido a los elementos de datos más utilizados e incluye solo la última instantánea de los datos del almacén de datos; no incluye datos históricos.
* El almacén de datos avanzado proporciona todos los valores y detalles disponibles en el almacén de datos simple e incluye acceso a valores de datos históricos.




=== Modelos de datos de capacidad

Le permite responder preguntas sobre la capacidad de almacenamiento, la utilización del sistema de archivos, la capacidad del volumen interno, la capacidad del puerto, la capacidad de qtree y la capacidad de la máquina virtual (VM).  El modelo de datos de capacidad es un contenedor para varios modelos de datos de capacidad.  Puede crear informes que respondan varios tipos de preguntas utilizando este modelo de datos:



==== Modelo de datos de capacidad de almacenamiento y pool de almacenamiento

Le permite responder preguntas sobre la planificación de recursos de capacidad de almacenamiento, incluido el almacenamiento y los grupos de almacenamiento, e incluye datos de grupos de almacenamiento físicos y virtuales.  Este modelo de datos simple puede ayudarlo a responder preguntas relacionadas con la capacidad en el piso y el uso de la capacidad de los grupos de almacenamiento por nivel y centro de datos a lo largo del tiempo.  Si no tiene experiencia en informes de capacidad, debería comenzar con este modelo de datos porque es un modelo de datos más simple y específico.  Puede responder preguntas similares a las siguientes utilizando este modelo de datos:

* ¿Cuál es la fecha proyectada para alcanzar el umbral de capacidad del 80% de mi almacenamiento físico?
* ¿Cuál es la capacidad de almacenamiento físico en una matriz para un nivel determinado?
* ¿Cuál es mi capacidad de almacenamiento por fabricante y familia así como por centro de datos?
* ¿Cuál es la tendencia de utilización del almacenamiento en una matriz para todos los niveles?
* ¿Cuáles son mis 10 sistemas de almacenamiento con mayor utilización?
* ¿Cuál es la tendencia de utilización del almacenamiento de los grupos de almacenamiento?
* ¿Cuánta capacidad ya está asignada?
* ¿Qué capacidad está disponible para su asignación?




==== Modelo de datos de utilización del sistema de archivos

Este modelo de datos proporciona visibilidad sobre la utilización de la capacidad por parte de los hosts a nivel del sistema de archivos.  Los administradores pueden determinar la capacidad asignada y utilizada por sistema de archivos, determinar el tipo de sistema de archivos e identificar estadísticas de tendencias por tipo de sistema de archivos.  Puede responder las siguientes preguntas utilizando este modelo de datos:

* ¿Cuál es el tamaño del sistema de archivos?
* ¿Dónde se guardan los datos y cómo se accede a ellos, por ejemplo, localmente o SAN?
* ¿Cuáles son las tendencias históricas de la capacidad del sistema de archivos?  Entonces, en base a esto, ¿qué podemos anticipar para las necesidades futuras?




==== Modelo de datos de capacidad de volumen interno

Le permite responder preguntas sobre la capacidad utilizada del volumen interno, la capacidad asignada y el uso de la capacidad a lo largo del tiempo:

* ¿Qué volúmenes internos tienen una utilización superior a un umbral predefinido?
* ¿Qué volúmenes internos corren el riesgo de quedarse sin capacidad en función de una tendencia?  8 ¿Cuál es la capacidad utilizada versus la capacidad asignada en nuestros volúmenes internos?




==== Modelo de datos de capacidad portuaria

Le permite responder preguntas sobre la conectividad del puerto del conmutador, el estado del puerto y la velocidad del puerto a lo largo del tiempo.  Puede responder preguntas similares a las siguientes para ayudarlo a planificar la compra de nuevos conmutadores: ¿Cómo puedo crear un pronóstico de consumo de puerto que prediga la disponibilidad de recursos (puertos) (según el centro de datos, el proveedor del conmutador y la velocidad del puerto)?

* ¿Qué puertos tienen más probabilidades de quedarse sin capacidad, teniendo en cuenta la velocidad de los datos, el centro de datos, el proveedor y la cantidad de puertos de host y almacenamiento?
* ¿Cuáles son las tendencias de capacidad del puerto de conmutación a lo largo del tiempo?
* ¿Cuales son las velocidades del puerto?
* ¿Qué tipo de capacidad portuaria se necesita y qué organización está a punto de quedarse sin un determinado tipo de puerto o proveedor?
* ¿Cuál es el momento óptimo para comprar esa capacidad y ponerla a disposición?




==== Modelo de datos de capacidad de Qtree

Le permite analizar la tendencia de utilización de qtree (con datos como capacidad utilizada versus capacidad asignada) a lo largo del tiempo.  Puede ver la información por diferentes dimensiones, por ejemplo, por entidad comercial, aplicación, nivel y nivel de servicio.  Puede responder las siguientes preguntas utilizando este modelo de datos:

* ¿Cuál es la capacidad utilizada para qtrees frente a los límites establecidos por aplicación o entidad comercial?
* ¿Cuáles son las tendencias de nuestra capacidad utilizada y libre para que podamos realizar una planificación de la capacidad?
* ¿Qué entidades comerciales están utilizando la mayor capacidad?
* ¿Qué aplicaciones consumen más capacidad?




==== Modelo de datos de capacidad de VM

Le permite informar sobre su entorno virtual y su uso de capacidad.  Este modelo de datos le permite informar sobre los cambios en el uso de la capacidad a lo largo del tiempo para las máquinas virtuales y los almacenes de datos.  El modelo de datos también proporciona datos de aprovisionamiento fino y de devolución de cargos de máquinas virtuales.

* ¿Cómo puedo determinar el cargo por capacidad según la capacidad proporcionada a las máquinas virtuales y los almacenes de datos?
* ¿Qué capacidad no utilizan las máquinas virtuales y qué parte no utilizada está libre, huérfana u otra?
* ¿Qué necesitamos comprar en función de las tendencias de consumo?
* ¿Qué ahorros en eficiencia de almacenamiento consigo al utilizar tecnologías de deduplicación y aprovisionamiento fino de almacenamiento?


Las capacidades en el modelo de datos de capacidad de VM se toman de los discos virtuales (VMDK).  Esto significa que el tamaño aprovisionado de una VM que utiliza el modelo de datos de capacidad de VM es el tamaño de sus discos virtuales.  Esto es diferente de la capacidad aprovisionada en la vista Máquinas virtuales en Data Infrastructure Insights, que muestra el tamaño aprovisionado para la máquina virtual en sí.



==== Modelo de datos de capacidad de volumen

Le permite analizar todos los aspectos de los volúmenes de su inquilino y organizar los datos por proveedor, modelo, nivel, nivel de servicio y centro de datos.

Puede ver la capacidad relacionada con volúmenes huérfanos, volúmenes no utilizados y volúmenes de protección (utilizados para la replicación).  También puede ver diferentes tecnologías de volumen (iSCSI o FC) y comparar volúmenes virtuales con volúmenes no virtuales para problemas de virtualización de matrices.

Puede responder preguntas similares a las siguientes con este modelo de datos:

* ¿Qué volúmenes tienen una utilización superior a un umbral predefinido?
* ¿Cuál es la tendencia en mi centro de datos en cuanto a capacidad de volúmenes huérfanos?
* ¿Qué porcentaje de la capacidad de mi centro de datos está virtualizada o con aprovisionamiento ligero?
* ¿Cuánta capacidad de mi centro de datos debo reservar para la replicación?




=== Modelo de datos de contracargos

Le permite responder preguntas sobre la capacidad utilizada y la capacidad asignada en los recursos de almacenamiento (volúmenes, volúmenes internos y qtrees).  Este modelo de datos proporciona información sobre la rendición de cuentas y el cobro de capacidad de almacenamiento por parte de hosts, aplicaciones y entidades comerciales, e incluye datos actuales e históricos.  Los datos del informe se pueden clasificar por nivel de servicio y nivel de almacenamiento.

Puede utilizar este modelo de datos para generar informes de contracargos al encontrar la cantidad de capacidad que utiliza una entidad comercial.  Este modelo de datos le permite crear informes unificados de múltiples protocolos (incluidos NAS, SAN, FC e iSCSI).

* Para el almacenamiento sin volúmenes internos, los informes de contracargos muestran los contracargos por volúmenes.
* Para almacenamiento con volúmenes internos:
+
** Si las entidades comerciales están asignadas a volúmenes, los informes de contracargos muestran los contracargos por volúmenes.
** Si las entidades comerciales no están asignadas a volúmenes sino a qtrees, los informes de contracargos muestran los contracargos por qtrees.
** Si las entidades comerciales no están asignadas a volúmenes ni a qtrees, los informes de devolución de cargo muestran el volumen interno.
** La decisión de mostrar el contracargo por volumen, qtree o volumen interno se toma para cada volumen interno, por lo que es posible que diferentes volúmenes internos en el mismo grupo de almacenamiento muestren el contracargo en diferentes niveles.




Los datos de capacidad se eliminan después de un intervalo de tiempo predeterminado.  Para obtener más detalles, consulte Procesos de almacén de datos.

Los informes que utilizan el modelo de datos de contracargo pueden mostrar valores diferentes a los informes que utilizan el modelo de datos de capacidad de almacenamiento.

* Para las matrices de almacenamiento que no son sistemas de almacenamiento NetApp , los datos de ambos modelos de datos son los mismos.
* Para los sistemas de almacenamiento NetApp y Celerra, el modelo de datos de contracargo utiliza una sola capa (de volúmenes, volúmenes internos o qtrees) para basar sus cargos, mientras que el modelo de datos de capacidad de almacenamiento utiliza varias capas (de volúmenes y volúmenes internos) para basar sus cargos.




=== Modelo de datos de inventario

Le permite responder preguntas sobre recursos de inventario, incluidos hosts, sistemas de almacenamiento, conmutadores, discos, cintas, qtrees, cuotas, máquinas y servidores virtuales y dispositivos genéricos.  El modelo de datos de inventario incluye varios submercados que le permiten ver información sobre replicaciones, rutas FC, rutas iSCSI, rutas NFS y violaciones.  El modelo de datos de inventario no incluye datos históricos.  Preguntas que puedes responder con estos datos

* ¿Qué activos tengo y dónde están?
* ¿Quién está utilizando los activos?
* ¿Qué tipos de dispositivos tengo y cuáles son los componentes de esos dispositivos?
* ¿Cuántos hosts por sistema operativo tengo y cuántos puertos existen en esos hosts?
* ¿Qué matrices de almacenamiento por proveedor existen en cada centro de datos?
* ¿Cuántos conmutadores por proveedor tengo en cada centro de datos?
* ¿Cuántos puertos no tienen licencia?
* ¿Qué cintas de proveedores estamos utilizando y cuántos puertos existen en cada cinta? ¿Están todos los dispositivos genéricos identificados antes de comenzar a trabajar en los informes?
* ¿Cuáles son las rutas entre los hosts y los volúmenes de almacenamiento o cintas?
* ¿Cuáles son las rutas entre los dispositivos genéricos y los volúmenes de almacenamiento o cintas?
* ¿Cuántas infracciones de cada tipo tengo por centro de datos?
* Para cada volumen replicado, ¿cuáles son los volúmenes de origen y de destino?
* ¿Tengo alguna incompatibilidad de firmware o desajustes en la velocidad del puerto entre los HBA host de Fibre Channel y los conmutadores?




=== Modelo de datos de rendimiento

Le permite responder preguntas sobre el rendimiento de volúmenes, volúmenes de aplicaciones, volúmenes internos, conmutadores, aplicaciones, máquinas virtuales, VMDK, ESX versus máquinas virtuales, hosts y nodos de aplicaciones.  Muchos de estos informes informan datos _por hora_, datos _diarios_ o ambos.  Con este modelo de datos, puede crear informes que respondan a varios tipos de preguntas sobre gestión del rendimiento:

* ¿Qué volúmenes o volúmenes internos no han sido utilizados o accedidos durante un período específico?
* ¿Podemos identificar alguna posible configuración incorrecta del almacenamiento de una aplicación (no utilizada)?
* ¿Cuál fue el patrón general de comportamiento de acceso para una aplicación?
* ¿Los volúmenes escalonados se asignan adecuadamente para una aplicación determinada?
* ¿Podríamos utilizar un almacenamiento más barato para una aplicación que actualmente se está ejecutando sin afectar el rendimiento de la aplicación?
* ¿Cuáles son las aplicaciones que están produciendo más accesos al almacenamiento configurado actualmente?


Al utilizar las tablas de rendimiento del conmutador, puede obtener la siguiente información:

* ¿Está equilibrado el tráfico de mi host a través de los puertos conectados?
* ¿Qué conmutadores o puertos presentan una gran cantidad de errores?
* ¿Cuáles son los switches más utilizados según el rendimiento del puerto?
* ¿Cuáles son los conmutadores infrautilizados en función del rendimiento del puerto?
* ¿Cuál es la tendencia de rendimiento del host en función del rendimiento del puerto?
* ¿Cuál es la utilización del rendimiento durante los últimos X días para un host, sistema de almacenamiento, cinta o conmutador específicos?
* ¿Qué dispositivos están produciendo tráfico en un conmutador específico (por ejemplo, qué dispositivos son responsables del uso de un conmutador muy utilizado)?
* ¿Cuál es el rendimiento de una unidad de negocio específica en nuestro entorno?


Al utilizar las tablas de rendimiento del disco, puede obtener la siguiente información:

* ¿Cuál es el rendimiento de un grupo de almacenamiento específico en función de los datos de rendimiento del disco?
* ¿Cuál es el pool de almacenamiento más utilizado?
* ¿Cuál es la utilización promedio del disco para un almacenamiento específico?
* ¿Cuál es la tendencia de uso de un sistema de almacenamiento o un grupo de almacenamiento en función de los datos de rendimiento del disco?
* ¿Cuál es la tendencia de uso del disco para un grupo de almacenamiento específico?


Al utilizar las tablas de rendimiento de VM y VMDK, puede obtener la siguiente información:

* ¿Mi entorno virtual funciona de manera óptima?
* ¿Qué VMDK informan las cargas de trabajo más altas?
* ¿Cómo puedo utilizar el rendimiento informado de los VMD asignados a diferentes almacenes de datos para tomar decisiones sobre la reorganización en niveles?


El modelo de datos de rendimiento incluye información que le ayuda a determinar la idoneidad de los niveles, las configuraciones incorrectas de almacenamiento para las aplicaciones y los tiempos de último acceso de los volúmenes y los volúmenes internos.  Este modelo de datos proporciona datos como tiempos de respuesta, IOP, rendimiento, número de escrituras pendientes y estado de acceso.



=== Modelo de datos de eficiencia de almacenamiento

Le permite realizar un seguimiento de la puntuación y el potencial de eficiencia del almacenamiento a lo largo del tiempo.  Este modelo de datos almacena mediciones no sólo de la capacidad aprovisionada, sino también de la cantidad que se utiliza o consume (la medición física).  Por ejemplo, cuando se habilita el aprovisionamiento fino, Data Infrastructure Insights indica cuánta capacidad se toma del dispositivo.  También puede utilizar este modelo para determinar la eficiencia cuando la deduplicación está habilitada.  Puede responder varias preguntas utilizando el almacén de datos de eficiencia de almacenamiento:

* ¿Cuál es nuestro ahorro en eficiencia de almacenamiento como resultado de la implementación de tecnologías de aprovisionamiento fino y deduplicación?
* ¿Cuáles son los ahorros de almacenamiento en los centros de datos?
* Según las tendencias históricas de capacidad, ¿cuándo necesitamos comprar almacenamiento adicional?
* ¿Cuál sería la ganancia de capacidad si habilitáramos tecnologías como el aprovisionamiento fino y la deduplicación?
* Respecto a la capacidad de almacenamiento, ¿estoy en riesgo ahora?




=== Tablas de hechos y dimensiones del modelo de datos

Cada modelo de datos incluye tablas de hechos y de dimensiones.

* Tablas de hechos: Contienen datos que se miden, por ejemplo, cantidad, capacidad bruta y utilizable.  Contiene claves externas para las tablas de dimensiones.
* Tablas de dimensiones: contienen información descriptiva sobre hechos, por ejemplo, centro de datos y unidades de negocio.  Una dimensión es una estructura, a menudo compuesta de jerarquías, que categoriza datos.  Los atributos dimensionales ayudan a describir los valores dimensionales.


Al utilizar atributos de dimensión diferentes o múltiples (vistos como columnas en los informes), se crean informes que acceden a los datos de cada dimensión descrita en el modelo de datos.



=== Colores utilizados en los elementos del modelo de datos

Los colores en los elementos del modelo de datos tienen diferentes indicaciones.

* Activos amarillos: representan mediciones.
* Activos no amarillos: representan atributos.  Estos valores no se agregan.




=== Uso de múltiples modelos de datos en un informe

Normalmente se utiliza un modelo de datos por informe.  Sin embargo, puede escribir un informe que combine datos de múltiples modelos de datos.

Para escribir un informe que combine datos de múltiples modelos de datos, elija uno de los modelos de datos para utilizar como base y luego escriba consultas SQL para acceder a los datos de los almacenes de datos adicionales.  Puede utilizar la función Unión SQL para combinar los datos de las diferentes consultas en una única consulta que puede utilizar para escribir el informe.

Por ejemplo, supongamos que desea la capacidad actual de cada matriz de almacenamiento y desea capturar anotaciones personalizadas en las matrices.  Puede crear el informe utilizando el modelo de datos de capacidad de almacenamiento.  Puede utilizar los elementos de las tablas de Capacidad actual y de dimensiones y agregar una consulta SQL independiente para acceder a la información de anotaciones en el modelo de datos de Inventario.  Por último, puede combinar los datos vinculando los datos de almacenamiento de inventario a la tabla de dimensión de almacenamiento utilizando el nombre de almacenamiento y los criterios de unión.
