---
sidebar: sidebar 
permalink: reporting_querying_database.html 
summary: Utilice las API de Data Infrastructure Insights para consultar la base de datos de informes directamente. 
keywords: reporting, cognos, data warehouse, dwh, API 
---
= Acceda a la base de datos de informes a través de API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La potente API de Data Infrastructure Insights permite a los usuarios consultar la base de datos de informes de Data Infrastructure Insights directamente, sin pasar por el entorno de informes de Cognos.


NOTE: Esta documentación hace referencia a la función de informes de Data Infrastructure Insights , que está disponible en Data Infrastructure Insights Premium Edition.



== Odata

La API de informes de Data Infrastructure Insights sigue laslink:https://www.odata.org/["OData versión 4"] (Open Data Protocol) estándar para su consulta a la base de datos de Reportes.  Para obtener más información o aprender más, consultelink:https://www.odata.org/getting-started/basic-tutorial/["este tutorial"] en OData.

Todas las solicitudes comenzarán con la URL _\https://< URL de Data Infrastructure Insights >/rest/v1/dwh-management/odata_



== Generar una clave API

Leer más sobrelink:API_Overview.html["API de Data Infrastructure Insights"] .

Para generar una clave API, haga lo siguiente:

* Inicie sesión en su entorno de Data Infrastructure Insights y seleccione *Admin > Acceso API*.
* Haga clic en “+ Token de acceso API”.
* Introduzca un nombre y una descripción.
* Para el tipo, seleccione _Data Warehouse_.
* Establecer permisos como lectura/escritura.
* Establecer una fecha de vencimiento para los deseos.
* Haga clic en “Guardar”, luego *copie la clave y guárdela* en un lugar seguro.  No podrás acceder a la clave completa más tarde.


Las claves API son útiles para<<synchronous-or-asynchronous,_Sincronización_ o _Asincrónica_>> .



== Consulta directa de tablas

Con la clave API instalada, ahora es posible realizar consultas directas a la base de datos de informes.  Las URL largas se pueden simplificar a \https://.../odata/ para fines de visualización en lugar del formato completo \https://< URL de Data Infrastructure Insights >/rest/v1/dwh-management/odata/

Pruebe consultas sencillas como

* \https://< URL de Data Infrastructure Insights >/rest/v1/dwh-management/odata/dwh_custom
* \https://< URL de Data Infrastructure Insights >/rest/v1/dwh-management/odata/dwh_inventory
* \https://< URL de Data Infrastructure Insights >/rest/v1/dwh-management/odata/dwh_inventory/storage
* \https://< URL de Data Infrastructure Insights >/rest/v1/dwh-management/odata/dwh_inventory/disk
* \https://.../odata/dwh_custom/consultas_personalizadas




== Ejemplos de API REST

La URL para todas las llamadas es _\https://< URL de Data Infrastructure Insights >/rest/v1/dwh-management/odata_.

* GET /{schema}/** - Recupera datos de la base de datos de informes.


Formato: _\https://< URL de Data Infrastructure Insights >/rest/v1/dwh-management/odata/<nombre_del_esquema>/<consulta>_

Ejemplo:

 https://<domain>/rest/v1/dwh-management/odata/dwh_inventory/fabric?$count=true&$orderby=name
Resultado:

....
{
   "@odata.context": "$metadata#fabric",
   "@odata.count": 2,
   "value": [
       {
           "id": 851,
           "identifier": "10:00:50:EB:1A:40:3B:44",
           "wwn": "10:00:50:EB:1A:40:3B:44",
           "name": "10:00:50:EB:1A:40:3B:44",
           "vsanEnabled": "0",
           "vsanId": null,
           "zoningEnabled": "0",
           "url": "https://<domain>/web/#/assets/fabrics/941716"
       },
       {
           "id": 852,
           "identifier": "10:00:50:EB:1A:40:44:0C",
           "wwn": "10:00:50:EB:1A:40:44:0C",
           "name": "10:00:50:EB:1A:40:44:0C",
           "vsanEnabled": "0",
           "vsanId": null,
           "zoningEnabled": "0",
           "url": "https://<domain>/web/#/assets/fabrics/941836"
        }
    ]
}
....


== Consejos útiles

Tenga en cuenta lo siguiente al trabajar con consultas de API de informes.

* La carga útil de la consulta debe ser una cadena JSON válida
* La carga útil de la consulta debe estar contenida en una sola línea
* Las comillas dobles deben escaparse, es decir, \"
* Las pestañas se admiten como \t
* Evitar comentarios
* Se admiten nombres de tabla en minúsculas


Además:

* Se requieren 2 encabezados:
+
** Nombre “X-CloudInsights-ApiKey”
** Valor del atributo “<apikey>”




Su clave API será específica para su entorno de Data Infrastructure Insights .



== ¿Sincrónico o asincrónico?

De forma predeterminada, un comando API funcionará en modo _sincrónico_, lo que significa que usted envía la solicitud y la respuesta se devuelve inmediatamente.  Sin embargo, a veces una consulta puede tardar mucho tiempo en ejecutarse, lo que podría provocar que se agote el tiempo de espera de la solicitud.  Para evitar esto, puedes ejecutar una solicitud de forma _asincrónica_.  En el modo asincrónico, la solicitud devolverá una URL a través de la cual se podrá monitorear la ejecución.  La URL devolverá el resultado cuando esté listo.

Para ejecutar una consulta en modo asíncrono, agregue el encabezado `*Prefer: respond-async*` a la solicitud.  Tras una ejecución exitosa, la respuesta contendrá los siguientes encabezados:

....
Status Code: 202 (which means ACCEPTED)
preference-applied: respond-async
location: https://<Data Infrastructure Insights URL>/rest/v1/dwh-management/odata/dwh_custom/asyncStatus/<token>
....
Al consultar la URL de ubicación, se devolverán los mismos encabezados si la respuesta aún no está lista, o se devolverá con el estado 200 si la respuesta está lista.  El contenido de la respuesta será de tipo texto y contendrá el estado http de la consulta original y algunos metadatos, seguido de los resultados de la consulta original.

....
HTTP/1.1 200 OK
 OData-Version: 4.0
 Content-Type: application/json;odata.metadata=minimal
 oDataResponseSizeCounted: true

 { <JSON_RESPONSE> }
....
Para ver una lista de todas las consultas asincrónicas y cuáles están listas, use el siguiente comando:

 GET https://<Data Infrastructure Insights URL>/rest/v1/dwh-management/odata/dwh_custom/asyncList
La respuesta tiene el siguiente formato:

....
{
   "queries" : [
       {
           "Query": "https://<Data Infrastructure Insights URL>/rest/v1/dwh-management/odata/dwh_custom/heavy_left_join3?$count=true",
           "Location": "https://<Data Infrastructure Insights URL>/rest/v1/dwh-management/odata/dwh_custom/asyncStatus/<token>",
           "Finished": false
       }
   ]
}
....