---
sidebar: sidebar 
permalink: task_dc_ibm_ds4000.html 
keywords: data collector, IBM, DS4000 
summary: Recopilador de datos IBM TotalStorage DS4000 
---
= Recopilador de datos IBM TotalStorage DS4000
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Este recopilador de datos adquiere información de inventario y rendimiento del sistema de almacenamiento IBM DS4000.  Hay dos configuraciones posibles (firmware 6.x y firmware 7.x+), y ambas tienen los mismos valores.



== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario del recopilador de datos IBM DS4000.  Para cada tipo de activo adquirido, se muestra la terminología más común utilizada para este activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Disco | Disco 


| Grupo de volúmenes | Grupo de discos 


| Matriz de almacenamiento | Almacenamiento 


| Controladora | Nodo de almacenamiento 


| Grupo de volúmenes | Pool de almacenamiento 


| Volumen | Volumen 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

* Dirección IP de cada matriz DS5 o FAStT
* Validación de acceso haciendo ping a la dirección IP de ambos controladores en la matriz
* Requisitos del puerto: 2463




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Lista separada por comas de direcciones IP del controlador SANtricity de la matriz | Direcciones IP y/o nombres de dominio completos para los controladores de matriz 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (min) | El valor predeterminado es 30 minutos. 


| Intervalo de encuesta de rendimiento de hasta 3600 segundos | El valor predeterminado es 300 segundos 
|===


== Solución de problemas

Información adicional sobre este recopilador de datos se puede encontrar enlink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
