---
sidebar: sidebar 
permalink: task_config_telegraf_kubernetes.html 
keywords: telegraf 
summary: Recopilador de datos para Kubernetes 
---
= Recopilador de datos: Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Data Infrastructure Insights utiliza este recopilador de datos para reunir métricas de pods, nodos y contenedores de Kubernetes.



== Instalación

Para obtener instrucciones sobre la instalación de Kubernetes, consulte lalink:task_config_telegraf_agent_k8s.html["Operador de monitoreo de Kubernetes"] página.



== Acerca de Kube-state-metrics

El operador de monitoreo de Kubernetes instala kube-state-metrics automáticamente; no se necesita interacción del usuario.



=== Contadores de métricas de estado de Kube

El operador de monitoreo de Kubernetes de NetApp extrae los contadores kube-state-metrics que se enumeran a continuación.  Puede encontrar más detalles sobre cada contador en: https://github.com/kubernetes/kube-state-metrics/tree/main/docs#exposed-metrics[] .

. Métricas de DaemonSet
. Métricas de implementación
. Métricas del espacio de nombres
. Métricas de nodo
. Métricas de volumen persistente
. Métricas de reclamaciones de volumen persistente
. Métricas de pod
. Métricas de ReplicaSet
. Métricas de servicio
. Métricas de StatefulSet
. Métricas del escalador automático de pods horizontales
. Métricas de Cronjob
. Métricas de trabajo
. Métricas de cuotas de recursos

