---
sidebar: sidebar 
permalink: task_dc_ibm_cleversafe.html 
keywords: data collector, IBM Cleversafe 
summary: Configuración del recopilador de datos de IBM Cleversafe. 
---
= Recopilador de datos de IBM Cleversafe
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utiliza este recopilador de datos para descubrir datos de inventario y rendimiento de los sistemas de almacenamiento IBM Cleversafe.


NOTE: IBM Cleversafe se mide a una tasa diferente de TB sin procesar a unidad administrada.  Cada 40 TB de capacidad IBM Cleversafe sin formato se cobra como 1link:concept_subscribing_to_cloud_insights.html#pricing["Unidad Administrada (UM)"] .



== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario del recopilador de datos de IBM Cleversafe.  Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más común utilizada para este activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Pool de almacenamiento | Pool de almacenamiento 


| Recipiente | Volumen interno 


| Recipiente | Compartir archivos 


| Compartir NFS | Compartir 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

* La dirección IP de los servicios de datos externos para el clúster
* Nombre de usuario y contraseña del administrador
* Puerto 9440




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| IP del administrador o nombre de host | Dirección IP o nombre de host del nodo de administración 


| Nombre de usuario | Nombre de usuario para la cuenta de usuario con rol de superusuario o administrador del sistema 


| Password | Contraseña para la cuenta de usuario con rol de superusuario o administrador del sistema 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (min) | Intervalo entre sondeos de inventario. 


| Tiempo de espera de conexión HTTP (seg.) | Tiempo de espera HTTP en segundos. 
|===


== Solución de problemas

Información adicional sobre este recopilador de datos se puede encontrar enlink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
