---
sidebar: sidebar 
permalink: task_dc_redhat_virtualization.html 
keywords: data collector, Red Hat Virtualization 
summary: Configuración del recopilador de datos de Red Hat Virtualization. 
---
= Recopilador de datos de virtualización de Red Hat
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El recolector de datos DII para Red Hat Virtualization también es compatible con el proyecto de código abierto oVirt y Oracle Linux Virtualization Manager. Este recolector de datos se comunica a través de la API de REST con la interfaz HTTPS de la estación de gestión.



== Terminología

Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más común utilizada para el activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Disco | Disco virtual 


| Host | Host 


| Máquina virtual | Máquina virtual 


| Dominio de almacenamiento | Almacén de datos 


| Unidad lógica | LUN 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

* Dirección IP/nombre de host del servidor RHV/oVirt/OLVM a través del puerto 443 vía API de REST
* Nombre de usuario y contraseña de solo lectura
* RHV versión 3.0+/Ovirt 4.0+/OLVM 4.0+




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP del servidor RHV/Ovirt/OLVM | Dirección IP de la estación de gestión 


| Nombre de usuario | Nombre de usuario 


| Password | Password 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Puerto de comunicación HTTPS | Puerto utilizado para la comunicación HTTPS a RHEV 


| Intervalo de sondeo de inventario (min) | El valor predeterminado es 20 minutos. 


| Rendimiento de la máquina virtual | Habilitar la recopilación de rendimiento 


| Intervalo de sondeo de rendimiento (seg) | El valor por defecto es 900 
|===


== Solución de problemas

Información adicional sobre este recopilador de datos se puede encontrar enlink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
