---
sidebar: sidebar 
permalink: task_identify_inactive_devices.html 
keywords: inactive, device, remove, removing, identify, identifying 
summary: La identificación de dispositivos inactivos le permite elegir eliminarlos o asignarlos a una función activa. 
---
= Identificación de dispositivos inactivos
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Identificar los activos que tiene y quién los utiliza es fundamental para “dimensionarlos correctamente” y liberar infraestructura no utilizada.  Puede reasignar o desmantelar fácilmente recursos infrautilizados y evitar compras innecesarias.

Utilice los siguientes pasos para identificar activos inactivos.

.Pasos
* Vaya a *Observabilidad > Explorar -> +Nueva consulta de métricas*.
* Seleccione _Almacenamiento_ en el menú desplegable.
* Haga clic en el engranaje y agregue _isActive_ como columna.
+
Las filas que muestran una verificación están activas.  "X" indica dispositivos inactivos.



Para eliminar dispositivos inactivos, simplemente seleccione los dispositivos que desea eliminar y en el menú desplegable *Acciones masivas*, seleccione _Eliminar dispositivos inactivos_.
