---
sidebar: sidebar 
permalink: task_dc_hds_ops_center.html 
keywords: data collector, Hitachi Ops Center 
summary: Configuración del recopilador de datos de HDS Ops Center. 
---
= Recopilador de datos del Hitachi Ops Center
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Este recopilador de datos utiliza el conjunto integrado de aplicaciones de Hitachi Ops Center para acceder a los datos de inventario y rendimiento de múltiples dispositivos de almacenamiento.  Para el descubrimiento de inventario y capacidad, su instalación de Ops Center debe incluir los componentes "Servicios comunes" y "Administrador".  Para la recopilación de rendimiento, también debe tener implementado el "Analizador".



== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario de este recopilador de datos.  Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más común utilizada para este activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Sistemas de almacenamiento | Almacenamiento 


| Volumen | Volumen 


| Grupos de paridad | Grupo de almacenamiento (RAID), grupos de discos 


| Disco | Disco 


| Pool de almacenamiento | Pool de almacenamiento (fino, SNAP) 


| Grupos de paridad externa | Grupo de almacenamiento (backend), grupos de discos 


| Puerto | Nodo de almacenamiento → Nodo controlador → Puerto 


| Grupos anfitriones | Mapeo y enmascaramiento de volumen 


| Pares de volumen | Sincronización de almacenamiento 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos de inventario

Para poder recopilar datos de inventario, debe tener lo siguiente:

* Dirección IP o nombre de host del servidor del Centro de operaciones que aloja el componente "Servicios comunes"
* Cuenta de usuario y contraseña root/sysadmin que existen en todos los servidores que alojan componentes de Ops Center.  HDS no implementó la compatibilidad con API REST para el uso por parte de usuarios LDAP/SSO hasta Ops Center 10.8+




== Requisitos de rendimiento

Para poder recopilar datos de rendimiento se deben cumplir los siguientes requisitos:

El módulo "Analyzer" de HDS Ops Center debe estar instalado. Las matrices de almacenamiento deben alimentar el módulo "Analyzer" de Ops Center.



== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP del Hitachi Ops Center | Dirección IP o nombre de dominio completo del servidor del Centro de operaciones que aloja el componente "Servicios comunes" 


| Nombre de usuario | Nombre de usuario para el servidor del Centro de operaciones. 


| Password | Contraseña utilizada para el servidor del Centro de operaciones. 
|===


== Configuración avanzada

|===


| Campo | Descripción 


| Tipo de conexión | HTTPS (puerto 443) es el predeterminado 


| Anular puerto TCP | Especifique el puerto a utilizar si no es el predeterminado 


| Intervalo de sondeo de inventario (min) | Intervalo entre sondeos de inventario.  El valor predeterminado es 40. 


| Seleccione “Excluir” o “Incluir” para especificar una lista | Especifique si desea incluir o excluir la lista de matrices a continuación al recopilar datos. 


| Lista de dispositivos de filtrado | Lista separada por comas de números de serie de dispositivos para incluir o excluir 


| Intervalo de encuesta de rendimiento (seg.) | Intervalo entre encuestas de rendimiento.  El valor predeterminado es 300. 
|===
Información adicional se puede encontrar en ellink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
