---
sidebar: sidebar 
permalink: task_dc_na_solidfire.html 
summary: Configurar el recopilador de datos NetApp SolidFire 
keywords: data collector, queries, create 
---
= Recopilador de datos de matriz all-flash SolidFire de NetApp
:hardbreaks:
:allow-uri-read: 


[role="lead"]
El recopilador de datos de matriz All-Flash SolidFire de NetApp admite la recopilación de inventario y rendimiento de configuraciones SolidFire de iSCSI y Fibre Channel.

El recopilador de datos de SolidFire utiliza la API REST de SolidFire .  La unidad de adquisición donde reside el recopilador de datos debe poder iniciar conexiones HTTPS al puerto TCP 443 en la dirección IP de administración del clúster SolidFire .  El recopilador de datos necesita credenciales capaces de realizar consultas de API REST en el clúster SolidFire .



== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario del recopilador de datos de NetApp SolidFire All-Flash Array.  Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más común utilizada para este activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Conducir | Disco 


| Grupo | Almacenamiento 


| Node | Nodo de almacenamiento 


| Volumen | Volumen 


| Puerto de canal de fibra | Puerto 


| Grupo de acceso a volumen, asignación de LUN | Mapa de volumen 


| Sesión iSCSI | Máscara de volumen 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

Los siguientes son los requisitos para configurar este recopilador de datos:

* Dirección IP virtual de gestión
* Nombre de usuario y credenciales de solo lectura
* Puerto 443




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP virtual de gestión (MVIP) | Dirección IP virtual de administración del clúster SolidFire 


| Nombre de usuario | Nombre utilizado para iniciar sesión en el clúster SolidFire 


| Password | Contraseña utilizada para iniciar sesión en el clúster SolidFire 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Tipo de conexión | Elija el tipo de conexión 


| Puerto de comunicación | Puerto utilizado para la API de NetApp 


| Intervalo de sondeo de inventario (min) | El valor predeterminado es 20 minutos. 


| Intervalo de encuesta de rendimiento (seg.) | El valor predeterminado es 300 segundos 
|===


== Solución de problemas

Cuando SolidFire informa un error, se muestra en Data Infrastructure Insights de la siguiente manera:

_Se recibió un mensaje de error de un dispositivo SolidFire al intentar recuperar datos.  La llamada fue <método> (<cadena de parámetros>).  El mensaje de error del dispositivo fue (consulte el manual del dispositivo): <mensaje>_

Dónde:

* El <método> es un método HTTP, como GET o PUT.
* <parameterString> es una lista separada por comas de parámetros que se incluyeron en la llamada REST.
* El <mensaje> es lo que el dispositivo devolvió como mensaje de error.


Información adicional sobre este recopilador de datos se puede encontrar enlink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
