---
sidebar: sidebar 
permalink: task_cloud_insights_onboarding_1.html 
summary: Registrarse en Data Infrastructure Insights y crear su inquilino. 
keywords: onboarding, new user 
---
= Data Infrastructure Insights
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Antes de poder comenzar a trabajar con Data Infrastructure Insights, debe registrarse en el portal * NetApp Console*.  Si ya tiene un inicio de sesión en la NetApp Console , puede comenzar una prueba gratuita de Data Infrastructure Insights con unos pocos pasos rápidos.



== Creación de su cuenta de NetApp Console

Para comenzar a utilizar los servicios en la nube de NetApp, visitelink:https://console.netapp.com/["* NetApp Console*"^] y haga clic en *Comenzar*.

* Si aún no se ha registrado, seleccione *Registrarse*
* Ingrese una dirección de correo electrónico comercial válida y elija una contraseña.
* Introduzca el nombre de su empresa y su nombre completo.
* Acepte los términos y condiciones y seleccione *Continuar*.
* La consola lo guiará en el proceso de inicio.




=== ¿Qué pasa si ya tengo un inicio de sesión en la NetApp Console ?

Una vez que tenga una cuenta de NetApp Console , simplemente seleccione *Iniciar sesión* en ellink:https://console.netapp.com/["* NetApp Console*"^] página del portal.

Introduzca su dirección de correo electrónico y contraseña.  Luego serás llevado a la página de ofertas de nube de NetApp.

Vaya a *Análisis y control > Observabilidad* para obtener más información sobre Data Infrastructure Insights y/o solicitar una demostración.



== Comience su prueba gratuita de Data Infrastructure Insights

Si es la primera vez que inicia sesión en Data Infrastructure Insights, lea sobre todo lo que Data Infrastructure Insights tiene para ofrecer y, cuando esté _Listo para comenzar_, haga clic en *Solicitar prueba* y complete su información.

Como parte de la configuración de su inquilino de prueba, elegirá la región en la que alojará a su inquilino y si desea que esté en AWS o Azure.

Una vez completada la creación de su inquilino, use sus credenciales de consola para iniciar sesión y comenzar su prueba gratuita de 30 días de Data Infrastructure Insights. Durante esta prueba, podrá explorar las características que Data Infrastructure Insights tiene para ofrecer.

Durante la prueba gratuita, puedeslink:concept_subscribing_to_cloud_insights.html["Comienza tu suscripción"] a Data Infrastructure Insights en cualquier momento.  Cuando esté suscrito, podrá utilizar las funciones de Data Infrastructure Insights según su suscripción actual.



== Sign in y ve

Una vez que se haya creado su inquilino, en cualquier momento puede simplemente iniciar sesión en el portal NetApp BlueXP y navegar hasta el link:https://services.cloud.netapp.com["Servicios en la nube"] página y seleccione *Ir a Data Infrastructure Insights*.

También puede abrir un navegador directamente en la URL de su inquilino de Data Infrastructure Insights , por ejemplo:

 \https://<tenant-prefix>.c01.cloudinsights.netapp.com/
La URL también se incluirá en el correo electrónico de invitación de cada usuario para facilitar el acceso y la creación de marcadores.  Si el usuario aún no ha iniciado sesión en la consola, se le solicitará que lo haga.


NOTE: Los nuevos usuarios aún deben registrarse para acceder a la consola antes de poder acceder a la URL de su inquilino.

La primera vez que inicie sesión en un nuevo inquilino, se le guiará a través de la configuraciónlink:task_getting_started_with_cloud_insights.html["*comienza a recopilar datos*"] .



== Cerrar sesión

Para cerrar sesión en Data Infrastructure Insights, haga clic en su *Nombre de usuario* y seleccione *Cerrar sesión*.  Volverá a la pantalla de inicio de sesión de la consola.


NOTE: Al cerrar sesión en Data Infrastructure Insights, cerrará su sesión de la consola.  También se cerrará su sesión de otros servicios de NetApp Cloud que utilicen el inicio de sesión de la consola.



=== Tiempo de espera por inactividad

De forma predeterminada, Console cerrará la sesión de un usuario si no hay actividad durante seis horas (360 minutos).  Independientemente de la actividad, la sesión de los usuarios se cerrará después de siete días.
