---
sidebar: sidebar 
permalink: task_dc_brocade_rest.html 
keywords: data collector, Brocade, FC switch, FOS, Rest 
summary: Configuración del recopilador de datos REST de Brocade FOS. 
---
= Recopilador de datos REST de Brocade FOS
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utiliza el recopilador REST de Brocade FOS para descubrir el inventario y el rendimiento de los dispositivos conmutadores Brocade que ejecutan el firmware FabricOS (FOS) 8.2 y posteriores.  Tenga en cuenta que las primeras versiones de FOS 8.2 pueden tener errores en la API REST; se recomienda encarecidamente ejecutar la última versión posible de FOS que admita su plataforma.

Tenga en cuenta: el nivel de "usuario" predeterminado de FOS no es lo suficientemente potente para que Data Infrastructure Insights vea todos los aspectos lógicos de un dispositivo: necesitamos una cuenta de usuario con el "Rol de chasis" habilitado, así como permisos en todas las estructuras virtuales configuradas en un conmutador.

A continuación se muestra un ejemplo de cómo puede crear una cuenta de usuario de "menor privilegio" para el uso de Data Infrastructure Insights en una sesión SSH en un dispositivo FOS:

userConfig --add NetAppCIUser -r usuario -l 1-128 -c usuario -p Qwerty!

Esto creará un usuario “NetAppCIUser” con una contraseña “Qwerty!”.  Este usuario tiene el rol de “usuario” (-r) en las 128 estructuras virtuales posibles (-l).  Este usuario también tiene el rol “Chasis” requerido (-c) con acceso de nivel de usuario asignado.

De forma predeterminada, este recopilador intentará descubrir todos los dispositivos FOS que forman parte de todas las estructuras de las que forma parte el conmutador.

Tenga en cuenta: el usuario "usuario" de solo lectura predeterminado de FOS NO tiene permisos de visualización en todas las estructuras virtuales ni tampoco permisos de "rol de chasis".  Esto significa que tendrá pocas probabilidades de éxito al utilizar "usuario" con Data Infrastructure Insights, que necesita comprender tanto la configuración física como lógica del dispositivo FOS.



== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario del recopilador de datos REST de Brocade FOS.  Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más común utilizada para este activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Cambiar | Cambiar 


| Puerto | Puerto 


| Tejido virtual, tejido físico | Tela 


| Zona | Zona 


| Interruptor lógico | Interruptor lógico 


| Zona LSAN | Zona IVR 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

* Debe haber conectividad TCP a todos los conmutadores en la estructura.  Este tipo de recopilador de datos probará sin problemas tanto HTTP como HTTPS para cada dispositivo en la estructura.  Si selecciona la casilla de verificación _Descubrir todos los conmutadores en la estructura_, Data Infrastructure Insights identifica todos los conmutadores en la estructura; sin embargo, necesita conectividad TCP con estos conmutadores adicionales para descubrirlos.
* Se necesita la misma cuenta globalmente en todos los conmutadores de la red.  Puede utilizar la interfaz web del dispositivo para confirmar el acceso.




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Cambiar IP | Dirección IP o nombre de dominio completo del conmutador FOS 


| Nombre de usuario | Nombre de usuario para el conmutador 


| Password | Contraseña para el conmutador 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Dispositivos excluidos | Lista separada por comas de direcciones IPv4 de dispositivos que se excluirán del sondeo. 


| Intervalo de sondeo de inventario (min) | Intervalo entre sondeos de inventario.  El valor predeterminado es 60. 


| Descubra todos los interruptores en la tela | Seleccione para descubrir todos los interruptores en la tela. 


| Elija entre HBA y alias de zona | Elija si desea favorecer HBA o alias de zona. 


| Tipo de conexión | HTTP o HTTPS. 


| Tenga en cuenta que esta configuración solo cambia qué protocolo intenta usar CI por dispositivo primero: CI intentará el protocolo opuesto automáticamente si el predeterminado falla. | Anular puerto TCP 


| Especifique un puerto si no utiliza el predeterminado. | Intervalo de encuesta de rendimiento (seg.) 
|===


== Solución de problemas

Algunas cosas que puedes probar si encuentras problemas con este recopilador de datos:



=== Inventario

[cols="2*"]
|===
| Problema: | Prueba esto: 


| La función de prueba me advierte que un protocolo es inaccesible | Un dispositivo Brocade FOS 8.2+ determinado solo querrá hablar en HTTP o HTTPS: si un conmutador tiene un certificado digital instalado, el conmutador arrojará errores HTTP si uno intenta comunicarse con él con HTTP sin cifrar en lugar de HTTPS.  La función de prueba intenta la comunicación con HTTP y HTTPS: si la prueba le indica que un protocolo pasa, puede guardar el recopilador de manera segura y no preocuparse de que el otro protocolo no haya tenido éxito: el recopilador intentará ambos protocolos durante la recopilación y solo fallará si ninguno funciona. 


| Error: El inventario falla con 401 No autorizado...Clave de sesión no válida... | Este es un error distintivo de algunas versiones muy tempranas de FOS 8.2, como 8.2.1c, que NO admiten adecuadamente la autenticación básica HTTP.  Actualice a una versión posterior 8.2 o 9.* 


| Error: "Data Infrastructure Insights recibió un rol de chasis no válido" | Verifique que al usuario configurado en esta fuente de datos se le haya otorgado el permiso de rol de chasis. 


| Error: "Dirección IP del chasis no coincidente" | Cambie la configuración de la fuente de datos para utilizar la dirección IP del chasis. 


| El inventario falla con un 403 Prohibido | Esto puede deberse simplemente a credenciales incorrectas o puede ser un indicio de que está intentando usar un rol insuficientemente poderoso: recuerde que los usuarios de nivel "usuario" NO tienen el derecho de "Rol de chasis" requerido ni acceso de visualización a Virtual Fabrics que no sean los predeterminados. 
|===
Información adicional se puede encontrar en ellink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
