---
sidebar: sidebar 
permalink: task_dc_na_eseries.html 
keywords: data collector, ontap, clustered ontap, e-series, santricity 
summary: Configuración del recopilador de datos NetApp E-Series. 
---
= Recopilador de datos de API Santricity Legacy de NetApp E-Series
:hardbreaks:
:allow-uri-read: 


[role="lead"]
El recopilador de datos API Santricity Legacy de NetApp E-Series recopila datos de inventario y rendimiento.  El recopilador admite el firmware 7.x+ y utiliza las mismas configuraciones e informa los mismos datos.



== Terminología

Cloud Insight adquiere la siguiente información de inventario del recopilador de datos NetApp E-Series.  Para cada tipo de activo adquirido, se muestra la terminología más común utilizada para este activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Disco | Disco 


| Grupo de volúmenes | Grupo de discos 


| Matriz de almacenamiento | Almacenamiento 


| Controladora | Nodo de almacenamiento 


| Grupo de volúmenes | Pool de almacenamiento 


| Volumen | Volumen 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de este recopilador de datos.



== Terminología de la serie E (página de inicio)

Los siguientes términos se aplican a objetos o referencias que pueda encontrar en las páginas de destino de activos de NetApp E-Series.  Muchos de estos términos se aplican también a otros recopiladores de datos.



=== Almacenamiento

* Modelo – nombre del modelo del dispositivo.
* Proveedor: el mismo nombre de proveedor que vería si estuviera configurando una nueva fuente de datos
* Número de serie: el número de serie de la matriz.  En sistemas de almacenamiento con arquitectura de clúster como NetApp Clustered Data Ontap, este número de serie puede ser menos útil que los números de serie de los “Nodos de almacenamiento” individuales.
* IP: generalmente serán las IP o los nombres de host configurados en la fuente de datos
* Versión del microcódigo – firmware
* Capacidad bruta: suma en base 2 de todos los discos físicos del sistema, independientemente de su función
* Latencia: una representación de lo que experimenta el host que enfrenta cargas de trabajo, tanto en lecturas como en escrituras.  Lo ideal sería que Data Infrastructure Insights obtenga este valor directamente, pero a menudo no es así.  En lugar de que la matriz ofrezca esto, Data Infrastructure Insights generalmente realiza un cálculo ponderado por IOP derivado de las estadísticas de los volúmenes individuales.
* Rendimiento: el rendimiento total de la matriz frente al host.  Lo ideal es obtenerlo directamente de la matriz; si no está disponible, Data Infrastructure Insights suma el rendimiento de los volúmenes para obtener este valor.
* Administración: puede contener un hipervínculo a la interfaz de administración del dispositivo.  Creado programáticamente por la fuente de Data Infrastructure Insights como parte de los informes de inventario  




=== Pool de almacenamiento

* Almacenamiento: en qué matriz de almacenamiento reside este grupo. Obligatorio
* Tipo: un valor descriptivo de una lista de una lista enumerada de posibilidades.  Lo más común será “Aprovisionamiento fino” o “Grupo RAID”.
* Nodo: si la arquitectura de esta matriz de almacenamiento es tal que los grupos pertenecen a un nodo de almacenamiento específico, su nombre se verá aquí como un hipervínculo a su propia página de destino.
* Utiliza Flash Pool – Valor Sí/No
* Redundancia – Nivel RAID o esquema de protección.  La serie E informa sobre RAID 7 para grupos DDP
* Capacidad: los valores aquí son la capacidad lógica utilizada, la capacidad utilizable y la capacidad total lógica, y el porcentaje utilizado en estas.  Ambos valores incluyen la capacidad de “preservación” de la Serie E, lo que da como resultado que tanto los números como el porcentaje sean más altos que lo que puede mostrar la propia interfaz de usuario de la Serie E.
* Capacidad sobrecomprometida: si a través de tecnologías de eficiencia ha asignado una suma total de capacidades de volumen o de volumen interno mayor que la capacidad lógica del grupo de almacenamiento, el valor porcentual aquí será mayor a 0 %.
* Instantánea: capacidades de instantáneas utilizadas y totales, si la arquitectura de su grupo de almacenamiento dedica parte de su capacidad a áreas de segmentos exclusivamente para instantáneas
* Utilización: valor porcentual que muestra el mayor porcentaje de ocupación del disco de cualquier disco que aporte capacidad a este grupo de almacenamiento.  La utilización del disco no necesariamente tiene una fuerte correlación con el rendimiento de la matriz: la utilización puede ser alta debido a reconstrucciones de disco, actividades de deduplicación, etc. en ausencia de cargas de trabajo impulsadas por el host.  Además, las implementaciones de replicación de muchas matrices pueden impulsar la utilización del disco sin mostrarse como carga de trabajo de volumen.
* IOPS: la suma de IOPS de todos los discos que aportan capacidad a este grupo de almacenamiento.  Si las IOP de disco no están disponibles en una plataforma determinada, este valor se obtendrá de la suma de las IOP de volumen de todos los volúmenes que se encuentran en este grupo de almacenamiento.
* Rendimiento: el rendimiento total de todos los discos que aportan capacidad a este grupo de almacenamiento.  Si el rendimiento del disco no está disponible en una plataforma determinada, este valor se obtendrá de la suma del volumen total de todos los volúmenes que se encuentran en este grupo de almacenamiento.




=== Nodo de almacenamiento

* Almacenamiento: de qué matriz de almacenamiento forma parte este nodo. Obligatorio
* Socio de HA: en plataformas donde un nodo fallará en uno y solo otro nodo, generalmente se verá aquí
* Estado – salud del nodo.  Solo disponible cuando la matriz está lo suficientemente saludable como para ser inventariada por una fuente de datos
* Modelo – nombre del modelo del nodo
* Versión – nombre de la versión del dispositivo.
* Número de serie: el número de serie del nodo
* Memoria: memoria base 2 si está disponible
* Utilización: generalmente, un número de utilización de CPU o, en el caso de NetApp Ontap, un índice de estrés del controlador.  La utilización no está disponible actualmente para NetApp E-Series
* IOPS: un número que representa las IOPS impulsadas por el host en este controlador.  Lo ideal es obtenerlo directamente de la matriz; si no está disponible, se calculará sumando todas las IOP de los volúmenes que pertenecen exclusivamente a este nodo.
* Latencia: un número que representa la latencia típica del host o el tiempo de respuesta en este controlador.  Lo ideal es obtenerlo directamente de la matriz; si no está disponible, se calculará realizando un cálculo ponderado de IOP a partir de los volúmenes que pertenecen exclusivamente a este nodo.
* Rendimiento: un número que representa el rendimiento impulsado por el host en este controlador.  Lo ideal es obtenerlo directamente de la matriz; si no está disponible, se calculará sumando todo el rendimiento de los volúmenes que pertenecen exclusivamente a este nodo.
* Procesadores – Cantidad de CPU




== Requisitos

* La dirección IP de cada controlador en la matriz
* Requisito de puerto 2463




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Lista separada por comas de direcciones IP del controlador SANtricity de la matriz | Direcciones IP y/o nombres de dominio completos para los controladores de matriz 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (min) | El valor predeterminado es 30 minutos. 


| Intervalo de encuesta de rendimiento de hasta 3600 segundos | El valor predeterminado es 300 segundos 
|===


== Solución de problemas

Información adicional sobre este recopilador de datos se puede encontrar enlink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
