---
sidebar: sidebar 
permalink: task_dc_rubrik_cdm.html 
keywords: data collector, Rubrik, 
summary: Configuración del recopilador de datos CDM de Rubrik. 
---
= Recopilador de datos CDM de Rubrik
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utiliza el recopilador de datos de Rubrik para adquirir datos de inventario y rendimiento de los dispositivos de almacenamiento de Rubrik.



== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario del recopilador de datos de Rubrik.  Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más común utilizada para este activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Grupo | Almacenamiento, Pool de Almacenamiento 


| Node | Nodo de almacenamiento 


| Disco | Disco 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de esta fuente de datos.



== Requisitos

Para configurar este recopilador de datos se requiere lo siguiente:

* La Unidad de Adquisición de Data Infrastructure Insights iniciará conexiones al puerto TCP 443 al clúster Rubrik.  Un coleccionista por grupo.
* Dirección IP del clúster de Rubrik.
* Nombre de usuario y contraseña del cluster.
* Dirección IP o nombre de host del clúster de Rubrik.
* Para la autenticación básica, un nombre de usuario y una contraseña para el clúster.  Si prefiere utilizar la autenticación basada en cuenta de servicio, necesita una cuenta de servicio, un secreto y un ID de organización.
* Requisito de puerto: HTTPS 443




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Propiedad intelectual | Dirección IP del clúster Rubrik 


| Nombre de usuario / Cuenta de servicio | Nombre de usuario para el clúster 


| Contraseña / Secreto | Contraseña para el cluster 


| ID de la organización para la cuenta de servicio | Esta debe ser la cadena completa como "Organization:::nnnnnn-nnnn....." 
|===


== Configuración avanzada

[cols="2*"]
|===
| Intervalo de sondeo de inventario (min) | El valor predeterminado es 60 


| Intervalo de encuesta de rendimiento (seg.) | El valor predeterminado es 300 
|===


== Solución de problemas

Algunas cosas que puedes probar si encuentras problemas con este recopilador de datos:



=== Inventario

[cols="2*"]
|===
| Problema: | Prueba esto: 


| Recibí un mensaje que dice que se creó más de un almacenamiento. | Verifique que el clúster esté configurado correctamente y que el recopilador apunte a un solo clúster. 


| La encuesta falla con 400 [Solicitud incorrecta]....Id. administrado no válido.... | Ha completado el campo ID de organización con un valor, pero el clúster de Rubrik NO cree que sea un ID de organización válido, a pesar del mensaje de error de Rubrik que se refiere a él como "ManagedId". 
|===
Información adicional se puede encontrar en ellink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
