---
sidebar: sidebar 
permalink: task_configure_data_collectors.html 
keywords: acquisition, AU, data collector, collector, notification, notify, 
summary: Instrucciones generales para el recopilador de datos 
---
= Configuración de los colectores de datos
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Los recolectores de datos se configuran en su entorno Data Infrastructure Insights para recopilar datos de los dispositivos del centro de datos.

.Antes de empezar
* Debe haber configurado una unidad de adquisición para poder empezar a recopilar datos.
* Es necesario contar con credenciales para los dispositivos desde los cuales se recopilan datos.
* Las direcciones de red de dispositivos, la información de cuentas y las contraseñas son necesarias para todos los dispositivos desde los que se recopilan datos.


.Pasos
. En el menú Data Infrastructure Insights, haga clic en *Observabilidad > Recopiladores*
+
El sistema muestra los colectores de datos disponibles dispuestos por el proveedor.

. Haga clic en *+ Collector* y seleccione el recopilador de datos que desea configurar.
+
En el cuadro de diálogo puede configurar el recopilador de datos y agregar una unidad de adquisición.

. Introduzca un nombre para el recopilador de datos.
. Haga clic en *Configuración avanzada* para agregar campos de configuración adicionales. (No todos los recopiladores de datos necesitan configuración avanzada.)
. Haga clic en *Configuración de prueba* para comprobar que el recopilador de datos está configurado correctamente.
. Haga clic en *Agregar recopilador* para guardar la configuración y agregar el recopilador de datos a su inquilino de Data Infrastructure Insights.


Puede tardar hasta dos períodos de sondeo antes de que los datos del servicio se muestren en paneles o estén disponibles para realizar consultas.

* primera encuesta de inventario: inmediatamente
* primera encuesta de datos de rendimiento para establecer una línea de base: inmediatamente después de la encuesta de inventario
* segunda encuesta de rendimiento: dentro de los 15 segundos posteriores a la finalización de la primera encuesta de rendimiento


A continuación, el sondeo se realiza según el inventario configurado y los intervalos de sondeo de rendimiento.
