---
sidebar: sidebar 
permalink: task_dc_brocade_bna.html 
keywords: data collector, Brocade, BNA 
summary: Configuración del recopilador Brocade BNA. 
---
= Recopilador de datos de Brocade Network Advisor
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utiliza el recopilador de datos Brocade Network Advisor para adquirir datos de inventario y rendimiento de los conmutadores Brocade .



== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario del recopilador de datos de Brocade Network Advisor.  Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más común utilizada para este activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Cambiar | Cambiar 


| Puerto | Puerto 


| Tejido virtual, tejido físico | Tela 


| Interruptor lógico | Interruptor lógico 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

Para configurar este recopilador de datos se requiere lo siguiente:

* La Unidad de Adquisición de Data Infrastructure Insights iniciará conexiones al puerto TCP 443 en el servidor BNA.  El servidor BNA debe ejecutar la versión 14.2.1 o superior.
* Dirección IP del servidor Brocade Network Advisor
* Nombre de usuario y contraseña para una cuenta de administrador
* Requisito de puerto: HTTP/HTTPS 443




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| IP del servidor Brocade Network Advisor | Dirección IP del servidor Network Advisor 


| Nombre de usuario | Nombre de usuario para el conmutador 


| Nombre de usuario | Nombre de usuario administrador 


| Password | Contraseña de administrador 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Tipo de conexión | HTTPS (puerto predeterminado 443) o HTTP (puerto predeterminado 80) 


| Anular puerto de conexión | Si está en blanco, utilice el puerto predeterminado en el campo Tipo de conexión; de lo contrario, ingrese el puerto de conexión a utilizar. 


| Password | Contraseña para el conmutador 


| Intervalo de sondeo de inventario (min) | El valor predeterminado es 40 


| Puerta de enlace de acceso a informes | Marque para incluir dispositivos en el modo Access Gateway 


| Intervalo de encuesta de rendimiento (seg.) | El valor predeterminado es 1800 
|===


== Solución de problemas

Algunas cosas que puedes probar si encuentras problemas con este recopilador de datos:



=== Inventario

[cols="2*"]
|===
| Problema: | Prueba esto: 


| Reciba un mensaje que indica que más de un nodo está conectado al puerto de Access Gateway o que el recopilador de datos no puede descubrir el dispositivo de Access Gateway. | Verifique que el dispositivo NPV esté funcionando correctamente y que todos los WWN conectados sean los esperados.  No adquiera directamente el dispositivo VPN.  En cambio, la adquisición del conmutador de estructura central recopilará los datos del dispositivo VAN. 
|===
Información adicional se puede encontrar en ellink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
