---
sidebar: sidebar 
permalink: task_dc_emc_powerstore.html 
keywords: data collector, PowerStore, EMC, DELL 
summary: Configuración del recopilador de datos de DELL EMC PowerStore. 
---
= Recopilador de datos de Dell EMC PowerStore
:hardbreaks:
:allow-uri-read: 


[role="lead"]
El recopilador de datos de EMC PowerStore recopila información de inventario del almacenamiento de EMC PowerStore.  Para la configuración, el recopilador de datos requiere la dirección IP de los procesadores de almacenamiento y un nombre de usuario y contraseña de solo lectura.

El recopilador de datos de EMC PowerStore reúne las relaciones de replicación de volumen a volumen que PowerStore coordina entre otras matrices de almacenamiento.  Data Infrastructure Insights muestra una matriz de almacenamiento para cada clúster de PowerStore y recopila datos de inventario de los nodos y puertos de almacenamiento en ese clúster.  No se recopilan datos de volumen ni de grupo de almacenamiento.



== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario de este recopilador de datos.  Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más común utilizada para este activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| anfitrión | anfitrión 


| mapeo de volumen del host | mapeo de volumen del host 


| hardware (tiene Unidades bajo el objeto "extra_details"): Unidades | Disco 


| Aparato | Grupo de almacenamiento 


| Grupo | Matriz de almacenamiento 


| Node | Nodo de almacenamiento 


| puerto fc | Puerto 


| volume | Volumen 


| Volumen interno | sistema de archivos 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

Se requiere la siguiente información para configurar este recopilador de datos:

* Dirección IP o nombre de dominio completo del procesador de almacenamiento
* Nombre de usuario y contraseña de solo lectura




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Puerta(s) de enlace de PowerStore | Direcciones IP o nombres de dominio completos del almacenamiento de PowerStore 


| Nombre de usuario | Nombre de usuario para PowerStore 


| Password | Contraseña utilizada para PowerStore 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Puerto HTTPS | El valor predeterminado es 443 


| Intervalo de sondeo de inventario (minutos) | Intervalo entre sondeos de inventario. El valor predeterminado es 60 minutos. 
|===
La recopilación de rendimiento de PowerStore de Cloud Insight utiliza datos de origen con granularidad de 5 minutos de PowerStore.  Como tal, Data Infrastructure Insights sondea esos datos cada cinco minutos, y esto no es configurable.



== Solución de problemas

Información adicional sobre este recopilador de datos se puede encontrar enlink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
