---
sidebar: sidebar 
permalink: task_dc_nutanix.html 
keywords: data collector, Nutanix, NX Series 
summary: Configurando el recopilador de datos de Nutanix NX. 
---
= Recopilador de datos Nutanix NX
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Data Infrastructure Insights utiliza el recopilador de datos de Nutanix NX para obtener información sobre el inventario y el rendimiento de los sistemas de almacenamiento Nutanix NX.



[[terminology]]
== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario del recopilador de datos de Nutanix.  Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más común utilizada para este activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="50,50"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Pool de almacenamiento | Pool de almacenamiento 


| Contenedor Nutanix | Volumen interno 


| Contenedor Nutanix | Compartir archivos 


| Compartir NFS | Compartir 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de este recopilador de datos.



[[requirements]]
== Requisitos

* La dirección IP de los servicios de datos externos para el clúster
* Nombre de usuario y contraseña de solo lectura, a menos que se utilicen grupos de volúmenes, en cuyo caso se requieren nombre de usuario y contraseña de administrador
* Requisito de puerto: HTTPS 443




[[configuration]]
== Configuración

[cols="50,50"]
|===
| Campo | Descripción 


| Dirección IP externa de Prism | La dirección IP de los servicios de datos externos para el clúster 


| Nombre de usuario | Nombre de usuario para la cuenta de administrador 


| Password | Contraseña para la cuenta de administrador 
|===


[[advanced-configuration]]
== Configuración avanzada

[cols="50,50"]
|===
| Campo | Descripción 


| Puerto TCP | Puerto TCP utilizado para conectarse a la matriz Nutanix.  El valor predeterminado es 9440. 


| Intervalo de sondeo de inventario (min) | Intervalo entre sondeos de inventario. El valor predeterminado es 60 minutos. 


| Intervalo de sondeo de rendimiento (seg.) | Intervalo entre encuestas de rendimiento. El valor predeterminado es 300 segundos. 
|===


[[troubleshooting]]
== Solución de problemas

Información adicional sobre este recopilador de datos se puede encontrar enlink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
