---
sidebar: sidebar 
permalink: task_dc_emc_xio.html 
keywords: data collector, XtremeIO, EMC 
summary: Configuración del recopilador de datos XtremeIO. 
---
= Recopilador de datos Dell EMC XtremeIO
:hardbreaks:
:allow-uri-read: 


[role="lead"]
El recopilador de datos EMC XtremIO adquiere datos de inventario y rendimiento del sistema de almacenamiento EMC XtremIO.



== Requisitos

Para configurar el recopilador de datos EMC XtremIO (HTTP), debe tener:

* La dirección del host del servidor de administración XtremIO (XMS)
* Una cuenta con privilegios de administrador
* Acceso al puerto 443 (HTTPS)




== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario del recopilador de datos EMC XtremIO.  Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más común utilizada para este activo.  Al visualizar o solucionar problemas con esta fuente de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Disco (SSD) | Disco 


| Grupo | Almacenamiento 


| Controladora | Nodo de almacenamiento 


| Volumen | Volumen 


| Mapa LUN | Mapa de volumen 


| Iniciador FC de destino | Máscara de volumen 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de esta fuente de datos.



== Requisitos

* La dirección IP del host del servidor de administración XtremIO (XMS)
* Nombre de usuario y contraseña de administrador para XtremIO




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Anfitrión XMS | Dirección IP o nombre de dominio completo del servidor de administración XtremIO 


| Nombre de usuario | Nombre de usuario para el servidor de administración XtremIO 


| Password | Contraseña para el servidor de administración de XtremIO 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Puerto TCP | Puerto TCP utilizado para conectarse al servidor de administración XTremIO.  El valor predeterminado es 443. 


| Intervalo de sondeo de inventario (min) | Intervalo entre sondeos de inventario. El valor predeterminado es 60 minutos. 


| Intervalo de sondeo de rendimiento (seg.) | Intervalo entre encuestas de rendimiento. El valor predeterminado es 300 segundos. 
|===


== Solución de problemas

Información adicional sobre este recopilador de datos se puede encontrar enlink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
