---
sidebar: sidebar 
permalink: task_config_telegraf_consul.html 
keywords: telegraf, installation, install, consul 
summary: Configuración del recopilador de datos de Consul 
---
= Recopilador de datos del cónsul
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utiliza este recopilador de datos para recopilar métricas de Consul.



== Instalación

. Desde *Observabilidad > Recopiladores*, haga clic en *+Recopilador de datos*.  Elija Cónsul.
+
Si no ha configurado un agente para la recopilación, se le solicitará que lo haga.link:task_config_telegraf_agent.html["instalar un agente"] en su inquilino.

+
Si ya tiene un agente configurado, seleccione el sistema operativo o la plataforma adecuados y haga clic en *Continuar*.

. Siga las instrucciones en la pantalla de Configuración de Consul para configurar el recopilador de datos.  Las instrucciones varían según el tipo de sistema operativo o plataforma que esté utilizando para recopilar datos.




== Configuración

La información se puede encontrar en ellink:https://www.consul.io/docs/index.html["Documentación del cónsul"] .



== Objetos y contadores para el cónsul

Se recogen los siguientes objetos y sus contadores:

[cols="<.<,<.<,<.<,<.<"]
|===
| Objeto: | Identificadores: | Atributos: | Puntos de datos: 


| Cónsul | Nodo de servicio de verificación de ID de espacio de nombres | IP del nodo Sistema operativo del nodo UUID del nodo Nombre del nodo Nombre del servicio Nombre de verificación ID del servicio Estado | Advertencia de paso crítico 
|===


== Solución de problemas

Información adicional se puede encontrar en ellink:concept_requesting_support.html["Soporte"] página.
