---
sidebar: sidebar 
permalink: task_create_application.html 
summary: Usted define aplicaciones que luego aplica a los activos de su inquilino según sea necesario. 
keywords: application, create application, 
---
= Creación de aplicaciones
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Para realizar un seguimiento de los datos asociados con aplicaciones específicas que se ejecutan en su inquilino, puede definir las aplicaciones en Data Infrastructure Insights.

.Acerca de esta tarea
Data Infrastructure Insights le permite realizar un seguimiento de los datos de los activos asociados con las aplicaciones para cuestiones como el uso o los informes de costos.

.Pasos
. En el menú Data Infrastructure Insights , haga clic en *Observabilidad > Enriquecer > Aplicaciones*.  Seleccionar
+
Se muestra el cuadro de diálogo Agregar aplicación.

. Introduzca un nombre único para la aplicación.
. Seleccione una prioridad para la aplicación.
. Haga clic en *Guardar*.


Después de definir una aplicación, se puede asignar a los activos.



== Asignación de aplicaciones a activos

Este procedimiento asigna la aplicación a un host como ejemplo.  Puede asignar host, máquina virtual, volumen o volúmenes internos a una aplicación.

.Pasos
. Localiza el activo al que deseas asignar la aplicación:
. Haga clic en *Consultas > +Nueva consulta* y busque Host.
. Haga clic en la casilla de verificación a la izquierda del host que desea asociar con la aplicación.
. Haga clic en *Acciones masivas > Agregar aplicación*.
. Seleccione la aplicación a la que va a asignar el activo.


Cualquier aplicación nueva que asigne anulará cualquier aplicación en el activo que se haya derivado de otro activo.  Por ejemplo, los volúmenes heredan aplicaciones de los hosts y, cuando se asignan nuevas aplicaciones a un volumen, la nueva aplicación tiene prioridad sobre la aplicación derivada.


NOTE: Para entornos con grandes cantidades de activos relacionados, la herencia de las asignaciones de aplicaciones a esos activos podría demorar varios minutos.  Por favor, permita más tiempo para que se produzca la herencia si tiene muchos activos relacionados.

.Después de terminar
Después de asignar el host a la aplicación, puede asignar los activos restantes a la aplicación.  Para acceder a la página de inicio de la aplicación, haga clic en *Administrar > Aplicación* y seleccione la aplicación que creó.
