---
sidebar: sidebar 
permalink: task_dc_emc_vnx_file.html 
keywords: data collector, Celerra, EMC, DELL, VNX File 
summary: Configuración del recopilador de datos DELL EMC Celerra. 
---
= Recopilador de datos de archivos DELL EMC VNX (anteriormente Celerra Unified Storage System)
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Este recopilador de datos adquiere información de inventario del sistema de almacenamiento de archivos VNX.  Para la configuración, este recopilador de datos requiere la dirección IP de los procesadores de almacenamiento y un nombre de usuario y contraseña de solo lectura.



== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario del recopilador de datos de archivos VNX.  Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más común utilizada para este activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Servidor de red Celerra/Grupo de almacenamiento Celerra | Pool de almacenamiento 


| Sistema de archivos | Volumen interno 


| Transferencia de datos | Controladora 


| Sistema de archivos montado en un transportador de datos | Compartir archivos 


| Exportaciones CIFS y NFS | Compartir 


| Volumen del disco | LUN de backend 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

Necesita lo siguiente para configurar este recopilador de datos:

* La dirección IP del procesador de almacenamiento
* Nombre de usuario y contraseña de solo lectura
* Puerto SSH 22




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP del archivo VNX | Dirección IP o nombre de dominio completo del dispositivo de archivos VNX 


| Nombre de usuario | Nombre utilizado para iniciar sesión en el dispositivo de archivos VNX 


| Password | Contraseña utilizada para iniciar sesión en el dispositivo de archivos VNX 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (minutos) | Intervalo entre sondeos de inventario. El valor predeterminado es 20 minutos. 
|===


== Solución de problemas

Algunas cosas que puedes probar si encuentras problemas con este recopilador de datos:



=== Inventario

[cols="2*"]
|===
| Problema: | Prueba esto: 


| Error: No se puede continuar mientras la actualización de DART está en curso | Posible solución: pause el recopilador de datos y espere a que se complete la actualización de DART antes de intentar otra solicitud de adquisición. 
|===
Información adicional se puede encontrar en ellink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
