---
sidebar: sidebar 
permalink: task_dc_pure_flashblade.html 
keywords: data collector, Pure Storage, pure, FlashBlade 
summary: Configuración del recopilador de datos de Pure Storage. 
---
= Recopilador de datos FlashBlade de Pure Storage
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utiliza el recopilador de datos FlashBlade de Pure Storage para recopilar datos de inventario y rendimiento de los clústeres FlashBlade que exponen la versión 2 de su API REST.



== Terminología

Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más común utilizada para el activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Unidad (SSD) | Disco 


| Formación | Almacenamiento 


| Cuchilla | Nodo de almacenamiento 


| Sistema de archivos | Volumen interno 


| Cubo de almacenamiento de objetos | Árbol Q 


| Iniciador, Objetivo | Máscara de volumen 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

* Dirección IP del sistema de almacenamiento o nombre de dominio completo
* Token API, idealmente con una vida útil infinita.  Un usuario de nivel de solo lectura debería ser suficiente.
* Requisito de puerto: HTTPS 443




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP del host de FlashBlade | Dirección IP del sistema de almacenamiento 


| Nombre de usuario | Nombre de usuario para ayudar a los administradores de Data Infrastructure Insights a recordar a qué usuario pertenece su token de API 


| Token de API | Token de API 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Tipo de conexión | Elija HTTP o HTTPS.  También muestra el puerto predeterminado. 


| Anular el puerto TCP | Si está en blanco, utilice el puerto predeterminado en el campo Tipo de conexión; de lo contrario, ingrese el puerto de conexión a utilizar. 


| Intervalo de sondeo de inventario (min) | El valor predeterminado es 60 minutos. 


| Intervalo de encuesta de rendimiento (seg.) | El valor predeterminado es 300 
|===


== Solución de problemas

Algunas cosas que puedes probar si encuentras problemas con este recopilador de datos:



=== Inventario

[cols="2*"]
|===
| Problema: | Prueba esto: 


| "Credenciales de inicio de sesión no válidas" con mensajes de error como "La política no lo permite" o "No está autorizado". | Validar la cuenta de usuario y la contraseña de Pure a través de la interfaz http de Pure 
|===
Información adicional se puede encontrar en ellink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
