---
sidebar: sidebar 
permalink: task_configure_data_collectors.html 
keywords: acquisition, AU, data collector, collector, notification, notify, 
summary: Instrucciones generales para el recopilador de datos 
---
= Configuración de recopiladores de datos
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Configura los recopiladores de datos en tu entorno de Data Infrastructure Insights para recopilar datos de los dispositivos en el centro de datos.

.Antes de empezar
* Debe haber configurado una unidad de adquisición antes de poder comenzar a recopilar datos.
* Necesita credenciales para los dispositivos desde los que está recopilando datos.
* Se requieren direcciones de red del dispositivo, información de la cuenta y contraseñas para todos los dispositivos desde los que recopila datos.


.Pasos
. Desde el menú Data Infrastructure Insights , haga clic en *Observabilidad > Recopiladores*
+
El sistema muestra los recopiladores de datos disponibles organizados por proveedor.

. Haga clic en *+ Recopilador* y seleccione el recopilador de datos que desea configurar.
+
En el cuadro de diálogo puede configurar el recopilador de datos y agregar una unidad de adquisición.

. Introduzca un nombre para el recopilador de datos.
. Haga clic en *Configuración avanzada* para agregar campos de configuración adicionales.  (No todos los recopiladores de datos requieren una configuración avanzada).
. Haga clic en *Probar configuración* para verificar que el recopilador de datos esté configurado correctamente.
. Haga clic en *Agregar recopilador* para guardar la configuración y agregar el recopilador de datos a su inquilino de Data Infrastructure Insights .


Pueden pasar hasta dos períodos de sondeo antes de que los datos del servicio se muestren en los paneles o estén disponibles para consulta.

* 1ª encuesta de inventario: inmediata
* Primera encuesta de datos de rendimiento para establecer una línea base: inmediatamente después de la encuesta de inventario
* 2.ª encuesta de rendimiento: dentro de los 15 segundos posteriores a la finalización de la 1.ª encuesta de rendimiento


Luego, el sondeo continúa de acuerdo con los intervalos de sondeo de inventario y rendimiento configurados.
