---
sidebar: sidebar 
permalink: task_dc_dell_xc_series.html 
keywords: data collector, Dell, EMC, xc 
summary: Configuración del recopilador de datos de la serie XC de Dell EMC. 
---
= Recopilador de datos de la serie XC de Dell EMC
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utiliza este recopilador de datos para descubrir información de inventario y rendimiento de las matrices de almacenamiento de la serie Dell EMC XC.



== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP externa de Prism | Dirección IP del servidor XC 


| Nombre de usuario | Nombre de usuario para el servidor XC 


| Password | Contraseña utilizada para el servidor XC 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Puerto TCP | Puerto utilizado para la comunicación TCP con el servidor XC 


| Intervalo de sondeo de inventario (min) | Intervalo entre sondeos de inventario. El valor predeterminado es 60 minutos. 


| Intervalo de encuesta de rendimiento (min) | Intervalo entre encuestas de rendimiento. El valor predeterminado es 300 segundos. 
|===


== Solución de problemas

Información adicional se puede encontrar en ellink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
