---
sidebar: sidebar 
permalink: task_dc_emc_ecs.html 
keywords: data collector, ecs, EMC 
summary: Configuración del recopilador de datos ECS. 
---
= Configuración del recopilador de datos EMC ECS
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Este recopilador de datos adquiere datos de inventario y rendimiento de los sistemas de almacenamiento EMC ECS.  Para la configuración, el recopilador de datos requiere una dirección IP o un nombre de host del clúster ECS y un nombre de usuario y una contraseña.


NOTE: Dell EMC ECS se mide a una tasa de TB sin procesar diferente a la de unidad administrada.  Cada 40 TB de capacidad ECS sin formato se cobra como 1link:concept_subscribing_to_cloud_insights.html#pricing["Unidad Administrada (UM)"] .



[[terminology]]
== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario del recopilador de datos ECS.  Para cada tipo de activo adquirido, se muestra la terminología más común utilizada para este activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="50,50"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Grupo | Almacenamiento 


| Arrendatario | Pool de almacenamiento 


| Balde | Volumen interno 


| Disco | Disco 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de este recopilador de datos.



[[requirements]]
== Requisitos

* Una dirección IP o un nombre de host del clúster ECS
* Un nombre de usuario y una contraseña para el sistema ECS
* Puerto 4443 (HTTPS).  Requiere conectividad saliente al puerto TCP 4443 en el sistema ECS.




[[configuration]]
== Configuración

[cols="50,50"]
|===
| Campo | Descripción 


| Anfitrión ECS | Dirección IP o nombre de dominio completo del sistema ECS 


| Puerto de host ECS | Puerto utilizado para la comunicación con el host ECS 


| ID de usuario de ECS | ID de usuario para ECS 


| Password | Contraseña utilizada para ECS 
|===


[[advanced-configuration]]
== Configuración avanzada

[cols="50,50"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (min) | El valor predeterminado es 360 minutos. 
|===


[[troubleshooting]]
== Solución de problemas

Algunas cosas que puedes probar si encuentras problemas con este recopilador de datos:



[[inventory]]
=== Inventario

[cols="50,50"]
|===
| Problema: | Prueba esto: 


| Error: Error en la autenticación del usuario. | Asegúrese de que sus credenciales para este dispositivo sean correctas. 
|===


[[performance]]
=== Actuación

[cols="50,50"]
|===
| Problema: | Prueba esto: 


| Error: No se recopilaron suficientes datos. | * Verifique la marca de tiempo de recopilación en el archivo de registro y modifique el intervalo de sondeo en consecuencia. * Espere más tiempo. 


| Error: el intervalo de sondeo de rendimiento es demasiado grande. | Verifique la marca de tiempo de recopilación en el archivo de registro ${logfile} y modifique el intervalo de sondeo según corresponda 
|===
Información adicional se puede encontrar en ellink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
