---
sidebar: sidebar 
permalink: task_dc_ms_azure.html 
keywords: data collector, azure, 
summary: Configuración del recopilador de datos de proceso de Azure. 
---
= Configuración del recopilador de datos de proceso de Azure
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utiliza el recopilador de datos de cómputo de Azure para adquirir datos de inventario y rendimiento de las instancias de cómputo de Azure.



== Requisitos

Necesita la siguiente información para configurar este recopilador de datos.

* Requisito de puerto: 443 HTTPS
* URI de redireccionamiento de Azure OAuth 2.0 (login.microsoftonline.com)
* IP Rest de administración de Azure (management.azure.com)
* Dirección IP del Administrador de recursos de Azure (management.core.windows.net)
* Id. de la aplicación principal de servicio de Azure (cliente) (se requiere rol de lector)
* Clave de autenticación de entidad de servicio de Azure (contraseña de usuario)
* Debe configurar una cuenta de Azure para el descubrimiento de Data Infrastructure Insights .
+
Una vez que la cuenta esté configurada correctamente y registres la aplicación en Azure, tendrás las credenciales necesarias para descubrir la instancia de Azure con Data Infrastructure Insights.  El siguiente enlace describe cómo configurar la cuenta para el descubrimiento.https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal[]





== Configuración

Introduzca datos en los campos del recopilador de datos de acuerdo con la siguiente tabla:

[cols="2*"]
|===
| Campo | Descripción 


| Id. de la aplicación principal de servicio de Azure (cliente) (se requiere rol de lector) | ID de inicio de sesión en Azure.  Requiere acceso de rol de lector. 


| Identificador de inquilino de Azure | ID de inquilino de Microsoft 


| Clave de autenticación de entidad de servicio de Azure | Clave de autenticación de inicio de sesión 


| Entiendo que Microsoft me factura las solicitudes de API. | Marque esto para verificar su comprensión de que Microsoft le factura las solicitudes de API realizadas mediante el sondeo de Insight. 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (min) | El valor predeterminado es 60 


| Seleccione “Excluir” o “Incluir” para aplicar el filtro de máquinas virtuales por etiquetas | Especifique si desea incluir o excluir máquinas virtuales por etiquetas al recopilar datos.  Si se selecciona “Incluir”, el campo Clave de etiqueta no puede estar vacío. 


| Claves y valores de etiqueta para filtrar máquinas virtuales | Haga clic en *+ Etiqueta de filtro* para elegir qué máquinas virtuales (y discos asociados) desea incluir o excluir filtrando claves y valores que coincidan con las claves y valores de las etiquetas en la máquina virtual.  La clave de etiqueta es obligatoria, el valor de etiqueta es opcional.  Cuando el valor de etiqueta está vacío, la máquina virtual se filtra siempre que coincida con la clave de etiqueta. 


| Intervalo de encuesta de rendimiento (seg.) | El valor predeterminado es 300 
|===


== Solución de problemas

Información adicional sobre este recopilador de datos se puede encontrar enlink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
