---
sidebar: sidebar 
permalink: task_dc_na_ontap_rest.html 
keywords: data collector, ontap, ontap, CDOT, REST 
summary: Recopilador de datos REST de ONTAP 
---
= Recopilador de datos REST de NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Este recopilador de datos adquiere inventario, registros EMS y datos de rendimiento de los sistemas de almacenamiento que ejecutan ONTAP 9.14.1 y versiones posteriores mediante llamadas a la API REST. Para los sistemas ONTAP en versiones anteriores, utilice el tipo de recopilador "NetApp ONTAP Data Management Software" basado en ZAPI.


NOTE: El recopilador ONTAP REST se puede utilizar como reemplazo del recopilador anterior basado en ONTAPI.  Como tal, puede haber diferencias en las métricas que se recopilan o informan.  Para obtener más información sobre las diferencias entre ONTAPI y REST, consulte lalink:https://docs.netapp.com/us-en/ontap-restmap-9141/index.html["Mapeo de ONTAPI a REST de ONTAP 9.14.1"] documentación.



== Requisitos

Los siguientes son los requisitos para configurar y utilizar este recopilador de datos:

* Debe tener acceso a una cuenta de usuario con el nivel de acceso requerido.  Tenga en cuenta que se requieren permisos de administrador si se crea un nuevo usuario/rol REST.
+
** En términos funcionales, Data Infrastructure Insights realiza principalmente solicitudes de lectura, pero se requieren algunos permisos de escritura para que Data Infrastructure Insights se registre en la matriz ONTAP .  Consulte la _Nota sobre permisos_ inmediatamente debajo.


* ONTAP versión 9.14.1 o superior.
* Requisitos del puerto: 443
* Tenga en cuenta que las métricas de Fpolicy no son compatibles con el recopilador REST de ONTAP (los recopiladores de datos de seguridad de carga de trabajo utilizan servidores FPolicy, y las métricas de FPolicy le permiten supervisar la actividad de recopilación de datos de seguridad de carga de trabajo). Para respaldar las métricas de Fpolicy, utilice el link:task_dc_na_cdot.html["Gestión de datos de ONTAP"] coleccionista.




== Una nota sobre los permisos

Dado que varios paneles ONTAP de Data Infrastructure Insights dependen de contadores ONTAP avanzados, debe mantener habilitada la opción *Habilitar recopilación avanzada de datos de contadores* en la sección Configuración avanzada del recopilador de datos.

Para crear una cuenta local para Data Infrastructure Insights a nivel de clúster, inicie sesión en ONTAP con el nombre de usuario y la contraseña del administrador de administración de clúster y ejecute los siguientes comandos en el servidor de ONTAP :

. Antes de comenzar, debe iniciar sesión en ONTAP con una cuenta de _Administrador_ y los _comandos de nivel de diagnóstico_ deben estar habilitados.
. Recupera el nombre del SVM que es de tipo _admin_. Vas a usar este nombre en los comandos posteriores.
+
 vserver show -type admin
. Crea un rol usando los siguientes comandos:
+
....
security login rest-role create -role {role name} -api /api -access readonly
security login rest-role create -role {role name} -api /api/cluster/agents -access all
vserver services web access create -name spi -role {role name} -vserver {vserver name as retrieved above}
....
. Cree el usuario de solo lectura utilizando el siguiente comando.  Una vez que haya ejecutado el comando de creación, se le pedirá que ingrese una contraseña para este usuario.  Tenga en cuenta que en el siguiente comando mostramos el conjunto de roles en _ci_readonly_.  Si crea un rol con un nombre diferente en el paso 3 anterior, utilice ese nombre de rol personalizado en su lugar.


 security login create -user-or-group-name {username} -application http -authentication-method password -role {role name}
Si se utiliza una cuenta AD/LDAP, el comando debe ser

 security login create -user-or-group-name DOMAIN\aduser/adgroup -application http -authentication-method domain -role ci_readonly
El rol resultante y el inicio de sesión del usuario se verán así:  El resultado real puede variar:

[listing]
----
security login rest-role show -vserver <vserver name> -role restRole

               Role                                    Access
Vserver        Name            API                     Level
----------     -------------   -------------------     ------
<vserver name> restRole        /api                    readonly
                               /api/cluster/agents     all
2 entries were displayed.

security login show -vserver <vserver name> -user-or-group-name restUser

Vserver: <vserver name>
                                                                 Second
User/Group                 Authentication                 Acct   Authentication
Name           Application Method        Role Name        Locked Method
-------------- ----------- ------------- ---------------- ------ --------------
restUser       http        password      restRole         no     none
----
Puede verificar el acceso spi si es necesario:

[listing]
----
**Vserver:> vserver services web access show -name spi
 Vserver                      Type     Service Name     Role
-------------- -------- ---------------- ----------------
<vserver name >     admin             spi           admin
<vserver name >     admin             spi           csrestrole

2 entries were displayed.**
----


== Migración

Para migrar de un recopilador de datos ONTAP (ontapi) anterior al recopilador REST de ONTAP más nuevo, haga lo siguiente:

. Agregue el recopilador REST.  Se recomienda ingresar información de un usuario diferente al configurado para el recopilador anterior.  Por ejemplo, utilice el usuario indicado en la sección Permisos anterior.
. Pausa el recopilador anterior para que no continúe recopilando datos.
. Deje que el nuevo recopilador REST adquiera datos durante al menos 30 minutos.  Ignore cualquier dato durante este tiempo que no parezca "normal".
. Después del período de descanso, deberías ver que tus datos se estabilizan a medida que el recopilador REST sigue adquiriendo.


Puedes utilizar este mismo proceso para volver al recopilador anterior, si lo deseas.



== Configuración

[cols="50,50"]
|===
| Campo | Descripción 


| Dirección IP de administración de ONTAP | Dirección IP o nombre de dominio completo del clúster de NetApp .  Debe ser una IP/FQDN de administración de clúster. 


| Nombre de usuario de ONTAP REST | Nombre de usuario para el clúster de NetApp 


| Contraseña de ONTAP REST | Contraseña para el clúster de NetApp 
|===


== Configuración avanzada

[cols="50,50"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (min) | El valor predeterminado es 60 minutos. 


| Intervalo de encuesta de rendimiento (seg.) | El valor predeterminado es 60 segundos. 


| Recopilación avanzada de datos de contadores | Seleccione esta opción para incluir datos del Contador avanzado de ONTAP en las encuestas. Habilitado por defecto. 


| Habilitar la recopilación de eventos de EMS | Seleccione esta opción para incluir datos de eventos de registro de ONTAP EMS. Habilitado por defecto. 


| Intervalo de sondeo EMS (seg.) | El valor predeterminado es 60 segundos. 
|===


== Terminología

Data Infrastructure Insights adquiere datos de inventario, registros y rendimiento del recopilador de datos ONTAP .  Para cada tipo de activo adquirido, se muestra la terminología más común utilizada para el activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="50,50"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Disco | Disco 


| Grupo de incursión | Grupo de discos 


| Grupo | Almacenamiento 


| Node | Nodo de almacenamiento 


| Agregar | Pool de almacenamiento 


| LUN | Volumen 


| Volumen | Volumen interno 


| Máquina virtual de almacenamiento/Vservidor | Máquina virtual de almacenamiento 
|===


== Terminología de gestión de datos de ONTAP

Los siguientes términos se aplican a objetos o referencias que pueda encontrar en las páginas de inicio de activos de almacenamiento de ONTAP Data Management.  Muchos de estos términos se aplican también a otros recopiladores de datos.



=== Almacenamiento

* Modelo: una lista delimitada por comas de los nombres de modelos de nodos únicos y discretos dentro de este clúster.  Si todos los nodos de los clústeres son del mismo tipo de modelo, solo aparecerá un nombre de modelo.
* Proveedor: el mismo nombre de proveedor que vería si estuviera configurando una nueva fuente de datos.
* Número de serie: el UUID de la matriz
* IP: generalmente serán las IP o los nombres de host configurados en la fuente de datos.
* Versión de microcódigo – firmware.
* Capacidad bruta: suma en base 2 de todos los discos físicos del sistema, independientemente de su función.
* Latencia: una representación de lo que experimenta el host que enfrenta cargas de trabajo, tanto en lecturas como en escrituras.  Lo ideal sería que Data Infrastructure Insights obtenga este valor directamente, pero a menudo no es así.  En lugar de que la matriz ofrezca esto, Data Infrastructure Insights generalmente realiza un cálculo ponderado por IOP derivado de las estadísticas de los volúmenes internos individuales.
* Rendimiento: agregado de los volúmenes internos.
* Gestión: esto puede contener un enlace para la interfaz de gestión del dispositivo. Creado mediante programación por la fuente de datos Data Infrastructure Insights como parte de los informes de inventario.




=== Pool de almacenamiento

* Almacenamiento: en qué matriz de almacenamiento reside este grupo.  Obligatorio.
* Tipo: un valor descriptivo de una lista de una lista enumerada de posibilidades.  Lo más común será “Agregado” o “Grupo RAID”.
* Nodo: si la arquitectura de esta matriz de almacenamiento es tal que los grupos pertenecen a un nodo de almacenamiento específico, su nombre se verá aquí como un hipervínculo a su propia página de destino.
* Utiliza Flash Pool – Valor Sí/No – ¿este pool basado en SATA/SAS tiene SSD utilizados para aceleración de almacenamiento en caché?
* Redundancia – Nivel RAID o esquema de protección.  RAID_DP es paridad dual, RAID_TP es paridad triple.
* Capacidad: los valores aquí son la capacidad lógica utilizada, la capacidad utilizable y la capacidad total lógica, y el porcentaje utilizado en estas.
* Capacidad sobrecomprometida: si al usar tecnologías de eficiencia ha asignado una suma total de capacidades de volumen o de volumen interno mayor que la capacidad lógica del grupo de almacenamiento, el valor porcentual aquí será mayor a 0 %.
* Instantánea: capacidades de instantáneas utilizadas y totales, si la arquitectura de su grupo de almacenamiento dedica parte de su capacidad a áreas de segmentos exclusivamente para instantáneas.  Es probable que ONTAP en configuraciones MetroCluster presenten esto, mientras que otras configuraciones de ONTAP lo presentan en menor medida.
* Utilización: valor porcentual que muestra el mayor porcentaje de ocupación del disco de cualquier disco que aporte capacidad a este grupo de almacenamiento.  La utilización del disco no necesariamente tiene una fuerte correlación con el rendimiento de la matriz: la utilización puede ser alta debido a reconstrucciones de disco, actividades de deduplicación, etc. en ausencia de cargas de trabajo impulsadas por el host.  Además, las implementaciones de replicación de muchas matrices pueden impulsar la utilización del disco sin mostrarse como volumen interno o carga de trabajo de volumen.
* IOPS: la suma de IOPS de todos los discos que aportan capacidad a este grupo de almacenamiento.  Rendimiento: el rendimiento total de todos los discos que aportan capacidad a este grupo de almacenamiento.




=== Nodo de almacenamiento

* Almacenamiento: de qué matriz de almacenamiento forma parte este nodo.  Obligatorio.
* Socio de HA: en plataformas donde un nodo fallará en uno y solo otro nodo, generalmente se verá aquí.
* Estado – salud del nodo.  Solo está disponible cuando la matriz está lo suficientemente saludable como para ser inventariada por una fuente de datos.
* Modelo: nombre del modelo del nodo.
* Versión – nombre de la versión del dispositivo.
* Número de serie: el número de serie del nodo.
* Memoria: memoria base 2 si está disponible.
* Utilización: en ONTAP, este es un índice de estrés del controlador de un algoritmo propietario.  Con cada encuesta de rendimiento, se informará un número entre 0 y 100 %, que es el mayor entre la contención del disco WAFL o la utilización promedio de la CPU.  Si observa valores sostenidos > 50%, esto es indicativo de un tamaño insuficiente: posiblemente un controlador/nodo no lo suficientemente grande o no hay suficientes discos giratorios para absorber la carga de trabajo de escritura.
* IOPS: se deriva directamente de las llamadas ONTAP REST en el objeto de nodo.
* Latencia: se deriva directamente de las llamadas ONTAP REST en el objeto de nodo.
* Rendimiento: derivado directamente de las llamadas ONTAP REST en el objeto de nodo.
* Procesadores – Cantidad de CPU.




== Métricas de potencia de ONTAP

Varios modelos de ONTAP proporcionan métricas de potencia para Data Infrastructure Insights que se pueden usar para monitorear o generar alertas.  Las listas de modelos compatibles y no compatibles que aparecen a continuación no son exhaustivas, pero deberían brindar cierta orientación; en general, si un modelo pertenece a la misma familia que uno de la lista, el soporte debería ser el mismo.

Modelos compatibles:

A200 A220 A250 A300 A320 A400 A700 A700s A800 A900 C190 FAS2240-4 FAS2552 FAS2650 FAS2720 FAS2750 FAS8200 FAS8300 FAS8700 FAS9000

Modelos no compatibles:

FAS2620 FAS3250 FAS3270 FAS500f FAS6280 FAS/ AFF 8020 FAS/ AFF 8040 FAS/ AFF 8060 FAS/ AFF 8080



== Solución de problemas

Algunas cosas que puedes probar si encuentras problemas con este recopilador de datos:

[cols="2*"]
|===
| Problema: | Prueba esto: 


| Al intentar crear un recopilador de datos ONTAP REST, se ve un error como el siguiente: Configuración: 10.193.70.14: La API de descanso de ONTAP en 10.193.70.14 no está disponible: 10.193.70.14 no pudo obtener /api/cluster: 400 Solicitud incorrecta | Esto se debe probablemente a una matriz ONTAP más antigua (por ejemplo, ONTAP 9.6) que no tiene capacidades de API de REST. ONTAP 9.14.1 es la versión mínima de ONTAP compatible con el recopilador REST de ONTAP. Se deben esperar respuestas "400 Bad Request" en las versiones de ONTAP anteriores a REST. Para las versiones de ONTAP que sí son compatibles con REST pero no son 9.14.1 o posteriores, puedes ver el siguiente mensaje similar: Configuration: 10.193.98.84: ONTAP rest API at 10.193.98.84 is not available: 10.193.98.84: ONTAP rest API at 10.193.98.84 is available: cheryl5-cluster-2 9.10.1 a3cb3247-3d3c-11ee-8ff3-005056b364a7 but is not of minimum version 9.14.1. 


| Veo métricas vacías o "0" donde el recopilador ontapi de ONTAP muestra datos. | ONTAP REST no informa las métricas que se utilizan internamente solo en el sistema ONTAP .  Por ejemplo, ONTAP REST no recopilará agregados del sistema, solo se recopilarán los SVM de tipo "datos".  Otros ejemplos de métricas REST de ONTAP que pueden informar datos cero o vacíos: InternalVolumes: REST ya no informa vol0.  Agregados: REST ya no informa aggr0.  Almacenamiento: la mayoría de las métricas son una acumulación de las métricas de volumen interno y se verán afectadas por lo anterior.  Máquinas virtuales de almacenamiento: REST ya no informa sobre SVM de tipo distinto a "datos" (por ejemplo, "clúster", "mgmt", "nodo").  También puede notar un cambio en la apariencia de los gráficos que sí tienen datos, debido al cambio en el período de sondeo de rendimiento predeterminado de 15 minutos a 5 minutos.  Una encuesta más frecuente significa más puntos de datos para graficar. 
|===
Información adicional se puede encontrar en ellink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
