---
sidebar: sidebar 
permalink: task_dc_emc_recoverpoint.html 
keywords: data collector, RecoverPoint, EMC, DELL 
summary: Configuración de Dell EMC RecoverPoint data Collector. 
---
= Recopilador de datos de Dell EMC RecoverPoint
:hardbreaks:
:allow-uri-read: 


[role="lead"]
El principal caso de uso del recopilador de datos de EMC RecoverPoint es descubrir las relaciones de replicación de volumen a volumen que facilita el dispositivo de almacenamiento RecoverPoint. Este colector también descubrirá el propio dispositivo RecoverPoint. Tenga en cuenta que Dell/EMC vende una solución de backup de VMware para equipos virtuales, "RecoverPoint for VMs", que no es compatible con este recopilador

Para la configuración, el recopilador de datos requiere la dirección IP de los procesadores de almacenamiento y un nombre de usuario y contraseña de sólo lectura.

El recopilador de datos de EMC RecoverPoint recopila las relaciones de replicación de volumen a volumen que RecoverPoint coordina en otras cabinas de almacenamiento. Data Infrastructure Insights muestra una cabina de almacenamiento para cada clúster de RecoverPoint, y recoge datos de inventario de nodos y puertos de almacenamiento en ese clúster. No se recopilan datos de volúmenes o pool de almacenamiento.



== Requisitos

Para configurar este recopilador de datos se necesita la siguiente información:

* Dirección IP o nombre de dominio completo del procesador de almacenamiento
* Nombre de usuario y contraseña de solo lectura
* Acceso a API DE REST a través del puerto 443




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección de RecoverPoint | Dirección IP o nombre de dominio completo del clúster RecoverPoint 


| Nombre de usuario | Nombre de usuario del clúster RecoverPoint 


| Contraseña | Contraseña utilizada para el clúster RecoverPoint 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Puerto TCP | Puerto TCP utilizado para conectarse al clúster RecoverPoint 


| Intervalo de sondeo de inventario (minutos) | Intervalo entre sondeos de inventario. El valor predeterminado es 20 minutos. 


| Clústeres excluidos | Lista de nombres o ID de clúster separados por comas para excluirlos al realizar el sondeo. 
|===


== Resolución de problemas

Puede encontrar información adicional sobre este recopilador de datos en la link:concept_requesting_support.html["Soporte técnico"] página o en el link:reference_data_collector_support_matrix.html["Matriz de compatibilidad de recopilador de datos"].
