---
sidebar: sidebar 
permalink: task_dc_ibm_cs.html 
keywords: data collector, IBM CS, CS Series 
summary: Configuración del recopilador de datos de IBM CS. 
---
= Recopilador de datos de IBM CS
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utiliza este recopilador de datos para descubrir datos de inventario y rendimiento de los sistemas de almacenamiento de IBM CS.



== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario del recopilador de datos de IBM CS.  Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más común utilizada para este activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Pool de almacenamiento | Pool de almacenamiento 


| Recipiente | Volumen interno 


| Recipiente | Compartir archivos 


| Compartir NFS | Compartir 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

* La dirección IP de los servicios de datos externos para el clúster
* Nombre de usuario y contraseña del administrador
* Puerto 9440




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP externa de Prism | La dirección IP de los servicios de datos externos para el clúster 


| Nombre de usuario | Nombre de usuario para la cuenta de administrador 


| Password | Contraseña para la cuenta de administrador 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Puerto TCP | Puerto TCP utilizado para conectarse a la matriz IBM CS.  El valor predeterminado es 9440. 


| Intervalo de sondeo de inventario (min) | Intervalo entre sondeos de inventario. El valor predeterminado es 60 minutos. 


| Intervalo de sondeo de rendimiento (seg.) | Intervalo entre encuestas de rendimiento. El valor predeterminado es 300 segundos. 
|===


== Solución de problemas

Información adicional sobre este recopilador de datos se puede encontrar enlink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
