---
sidebar: sidebar 
permalink: task_dc_hds_hcp.html 
keywords: data collector, Hitachi HDS, HCP 
summary: Configuración del recopilador de datos HDS. 
---
= Colector de datos Hitachi HCP
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Este recopilador de datos es compatible con Hitachi Content Platform (HCP) mediante la API de administración de HCP.


NOTE: La plataforma de contenido de Hitachi se mide a una tarifa diferente de TB sin procesar a unidad administrada.  Cada 40 TB de capacidad HCP sin formato se cobra como 1link:concept_subscribing_to_cloud_insights.html#pricing["Unidad Administrada (UM)"] .



== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario del recopilador de datos Hitachi HCP.  Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más común utilizada para este activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Clúster de profesionales sanitarios | Almacenamiento 


| Arrendatario | Pool de almacenamiento 


|  | Espacio de nombres 


| Volumen interno | Node 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos de inventario

Para poder recopilar datos de inventario, debe tener lo siguiente:

* Dirección IP del servidor HCP
* Nombre de usuario y contraseña de solo lectura para el software HCP y privilegios de pares




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Anfitrión de HCP | Dirección IP o nombre de dominio completo del host HCP 


| Puerto HCP | El valor predeterminado es 9090 


| ID de usuario de HCP | Nombre de usuario para el host HCP. 


| Contraseña de HCP | Contraseña utilizada para el host HCP. 


| Tipo de autenticación de HCP | Elija HCP_LOCAL o ACTIVE_DIRECTORY 
|===


== Configuración avanzada

|===


| Campo | Descripción 


| Intervalo de sondeo de inventario (min) | Intervalo entre sondeos de inventario.  El valor predeterminado es 60. 


| Intervalo de encuesta de rendimiento (seg.) | Intervalo entre encuestas de rendimiento.  El valor predeterminado es 900. 
|===
Información adicional se puede encontrar en ellink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
