---
sidebar: sidebar 
permalink: task_dc_cohesity_smartfiles.html 
keywords: data collector, cohesity 
summary: Configuración del recopilador de datos Cohesity SmartFiles. 
---
= Recopilador de datos Cohesity SmartFiles
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Este recopilador basado en API REST adquirirá un clúster Cohesity, descubriendo las “Vistas” (como volúmenes internos de Data Infrastructure Insights ), los distintos nodos y recopilando métricas de rendimiento.



== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| IP del Clúster de Cohesión | Dirección IP del clúster Cohesity 


| Nombre de usuario | Nombre de usuario para el clúster Cohesity 


| Password | Contraseña utilizada para el clúster Cohesity 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Puerto TCP | Puerto utilizado para la comunicación TCP con el clúster Cohesity 


| Intervalo de sondeo de inventario (min) | Intervalo entre sondeos de inventario. El valor predeterminado es 60 minutos. 


| Intervalo de encuesta de rendimiento (min) | Intervalo entre encuestas de rendimiento. El valor predeterminado es 900 segundos. 
|===


== Solución de problemas

Información adicional se puede encontrar en ellink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
