---
sidebar: sidebar 
permalink: task_view_configured_data_collectors.html 
keywords: acquisition, AU, data collector, collector, bulk edit, postpone polling, resume polling 
summary: Un resumen. 
---
= Administrar recopiladores de datos configurados
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La página Recopiladores de datos instalados proporciona acceso a los recopiladores de datos que se han configurado para Data Infrastructure Insights.  Puede utilizar esta página para modificar los recopiladores de datos existentes.

.Pasos
. En el menú Data Infrastructure Insights , haga clic en *Observabilidad > Recopiladores*
+
Se muestra la pantalla Recopiladores de datos disponibles.

. Haga clic en *Recopiladores de datos instalados*
+
Se muestra una lista de todos los recopiladores de datos instalados.  La lista proporciona el nombre del recopilador, el estado, la dirección IP a la que accede el recopilador y cuándo se adquirieron los datos por última vez de un dispositivo.  Las acciones que se pueden realizar en esta pantalla incluyen:

+
** Encuesta de control
** Cambiar las credenciales del recopilador de datos
** Recolectores de datos clonados






== Control del sondeo del recopilador de datos

Después de realizar un cambio en un recopilador de datos, es posible que desee que sondee inmediatamente para verificar los cambios, o puede que desee posponer la recopilación de datos en un recopilador de datos durante uno, tres o cinco días mientras trabaja en un problema.

.Pasos
. En el menú Data Infrastructure Insights , haga clic en *Observabilidad > Recopiladores*
. Haga clic en *Recopiladores de datos instalados*
. Seleccione la casilla de verificación a la izquierda del recopilador de datos que desea cambiar
. Haga clic en *Acciones masivas* y seleccione la acción de sondeo que desea realizar.
+
Se pueden realizar acciones masivas simultáneamente en varios recopiladores de datos.  Seleccione los recopiladores de datos y elija la acción a realizar en el menú *Acción masiva*.





== Edición de la información del recopilador de datos

Puede editar la información de configuración del recopilador de datos existente.

.Para editar un solo recopilador de datos:
. En el menú Data Infrastructure Insights , haga clic en *Observabilidad > Recopiladores* para abrir la lista de recopiladores de datos instalados.
. En el menú de opciones a la derecha del recopilador de datos que desea modificar, haga clic en *Editar*.
+
Se abre el cuadro de diálogo Editar recopilador.

. Ingrese los cambios y haga clic en *Probar configuración* para probar la nueva configuración o haga clic en *Guardar* para guardar la configuración.


También puedes editar varios recopiladores de datos:

. Seleccione la casilla de verificación a la izquierda de cada recopilador de datos que desee cambiar.
. Haga clic en el botón *Acciones masivas* y seleccione *Editar* para abrir el cuadro de diálogo Editar recopilador de datos.
. Modifique los campos como se indica arriba.
+

NOTE: Los recopiladores de datos seleccionados deben ser del mismo proveedor y modelo, y residir en la misma unidad de adquisición.

+
Al editar varios recopiladores de datos, el campo Nombre del recopilador de datos muestra “Mixto” y no se puede editar.  Otros campos, como el nombre de usuario y la contraseña, aparecen como “Mixtos” y se pueden editar.  Los campos que comparten el mismo valor en los recopiladores de datos seleccionados muestran los valores actuales y se pueden editar.

+
Al editar varios recopiladores de datos, el botón *Configuración de prueba* no está disponible.





== Clonación de recopiladores de datos

Al utilizar la función de clonación, puede agregar rápidamente una fuente de datos que tenga las mismas credenciales y atributos que otra fuente de datos.  La clonación le permite configurar fácilmente múltiples instancias del mismo tipo de dispositivo.

.Pasos
. En el menú Data Infrastructure Insights , haga clic en *Observabilidad > Recopiladores*.
. Haga clic en *Recopiladores de datos instalados*.
. Haga clic en la casilla de verificación a la izquierda del recopilador de datos que desea copiar.
. En el menú de opciones a la derecha del recopilador de datos seleccionado, haga clic en *Clonar*.
+
Se muestra el cuadro de diálogo Recopilador de datos de clonación.

. Introduzca nueva información en los campos obligatorios.
. Haga clic en *Guardar*.


.Después de terminar
La operación de clonación copia todos los demás atributos y configuraciones para crear el nuevo recopilador de datos.



== Realizar acciones masivas en recopiladores de datos

Puede editar simultáneamente cierta información para varios recopiladores de datos.  Esta función le permite iniciar una encuesta, posponerla y reanudarla en varios recopiladores de datos.  Además, puedes eliminar varios recopiladores de datos.

.Pasos
. En el menú Data Infrastructure Insights , haga clic en *Observabilidad > Recopiladores*
. Haga clic en *Recopiladores de datos instalados*
. Haga clic en la casilla de verificación a la izquierda de los recopiladores de datos que desea modificar.
. En el menú de opciones a la derecha, haga clic en la opción que desee realizar.


.Después de terminar
La operación que usted seleccionó se realiza en los recopiladores de datos.  Cuando elige eliminar recopiladores de datos, se muestra un cuadro de diálogo que le solicita que acepte la acción.
