---
sidebar: sidebar 
permalink: task_dc_amazon_ec2.html 
keywords: data collector, EC2, 
summary: Configuración del recopilador de datos de Amazon EC2. 
---
= Configuración del recopilador de datos de Amazon EC2
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utiliza el recopilador de datos de Amazon EC2 para adquirir datos de inventario y rendimiento de las instancias EC2.



== Requisitos

Para recopilar datos de los dispositivos Amazon EC2, debe tener la siguiente información:

* Debes tener uno de los siguientes:
+
** El *rol de IAM* para su cuenta en la nube de Amazon EC2, si utiliza la autenticación de rol de IAM.  La función IAM solo se aplica si su unidad de adquisición está instalada en una instancia de AWS.
** El ID de *clave de acceso IAM* y la clave de acceso secreta para su cuenta en la nube de Amazon EC2, si utiliza la autenticación de clave de acceso IAM.


* Debes tener el privilegio de "organización de lista"
* Puerto 443 HTTPS
* Las instancias EC2 se pueden informar como una máquina virtual o (de forma menos natural) un host.  Los volúmenes EBS se pueden informar como un disco virtual utilizado por la máquina virtual, así como también como un almacén de datos que proporciona la capacidad para el disco virtual.


Las claves de acceso constan de un ID de clave de acceso (por ejemplo, AKIAIOSFODNN7EXAMPLE) y una clave de acceso secreta (por ejemplo, wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY).  Utilice claves de acceso para firmar solicitudes programáticas que realice a EC2 si utiliza los SDK de Amazon EC2, REST o las operaciones de API de consulta.  Estas claves se proporcionan con su contrato de Amazon.



== Configuración

Introduzca datos en los campos del recopilador de datos de acuerdo con la siguiente tabla:

[cols="2*"]
|===
| Campo | Descripción 


| Región de AWS | Elija la región de AWS 


| Rol de IAM | Solo para uso cuando se adquiere en una AU en AWS.  Vea a continuación para obtener más información sobre<<iam-role,Rol de IAM>> . 


| ID de clave de acceso de AWS IAM | Ingrese el ID de clave de acceso de AWS IAM.  Obligatorio si no utiliza el rol IAM. 


| Clave de acceso secreta de AWS IAM | Ingrese la clave de acceso secreta de AWS IAM.  Obligatorio si no utiliza el rol IAM. 


| Entiendo que AWS me factura las solicitudes de API. | Marque esto para verificar su comprensión de que AWS le factura las solicitudes de API realizadas mediante el sondeo de Data Infrastructure Insights . 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Incluir regiones adicionales | Especifique regiones adicionales para incluir en la encuesta. 


| Rol de cuenta cruzada | Rol para acceder a recursos en diferentes cuentas de AWS. 


| Intervalo de sondeo de inventario (min) | El valor predeterminado es 60 


| Seleccione “Excluir” o “Incluir” para aplicar el filtro de máquinas virtuales por etiquetas | Especifique si desea incluir o excluir máquinas virtuales por etiquetas al recopilar datos.  Si se selecciona “Incluir”, el campo Clave de etiqueta no puede estar vacío. 


| Claves y valores de etiqueta para filtrar máquinas virtuales | Haga clic en *+ Etiqueta de filtro* para elegir qué máquinas virtuales (y discos asociados) desea incluir o excluir filtrando claves y valores que coincidan con las claves y valores de las etiquetas en la máquina virtual.  La clave de etiqueta es obligatoria, el valor de etiqueta es opcional.  Cuando el valor de etiqueta está vacío, la máquina virtual se filtra siempre que coincida con la clave de etiqueta. 


| Intervalo de encuesta de rendimiento (seg.) | El valor predeterminado es 1800 


| Espacio de nombres de métricas del agente de CloudWatch | Espacio de nombres en EC2/EBS desde el que se recopilarán datos.  Tenga en cuenta que si se cambian los nombres de las métricas predeterminadas en este espacio de nombres, es posible que Data Infrastructure Insights no pueda recopilar esos datos renombrados.  Se recomienda dejar los nombres de métricas predeterminados. 
|===


== Clave de acceso de IAM

Las claves de acceso son credenciales a largo plazo para un usuario de IAM o el usuario raíz de la cuenta de AWS.  Las claves de acceso se utilizan para firmar solicitudes programáticas a la AWS CLI o la API de AWS (directamente o mediante el AWS SDK).

Las claves de acceso constan de dos partes: un ID de clave de acceso y una clave de acceso secreta.  Cuando utiliza la autenticación _Clave de acceso IAM_ (a diferencia de la autenticación _Rol IAM_), debe usar tanto el ID de la clave de acceso como la clave de acceso secreta juntas para la autenticación de las solicitudes.  Para obtener más información, consulte la documentación de Amazon enlink:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html["Teclas de acceso"] .



== Rol de IAM

Al utilizar la autenticación _IAM Role_ (a diferencia de la autenticación de clave de acceso IAM), debe asegurarse de que el rol que crea o especifica tenga los permisos adecuados necesarios para acceder a sus recursos.

Por ejemplo, si crea un rol de IAM llamado _InstanceEc2ReadOnly_, debe configurar la política para otorgar permiso de acceso a la lista de solo lectura de EC2 a todos los recursos de EC2 para este rol de IAM.  Además, debe otorgar acceso a STS (Servicio de token de seguridad) para que este rol pueda asumir roles en varias cuentas.

Después de crear una función de IAM, puede adjuntarla cuando cree una nueva instancia de EC2 o cualquier instancia de EC2 existente.

Después de adjuntar la función IAM _InstanceEc2ReadOnly_ a una instancia EC2, podrá recuperar la credencial temporal a través de los metadatos de la instancia por nombre de función IAM y usarla para acceder a los recursos de AWS mediante cualquier aplicación que se ejecute en esta instancia EC2.

Para obtener más información, consulte la documentación de Amazon enlink:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html["Roles de IAM"] .

Nota: La función IAM solo se puede usar cuando la unidad de adquisición se ejecuta en una instancia de AWS.



== Asignación de etiquetas de Amazon a anotaciones de Data Infrastructure Insights

El recopilador de datos de Amazon EC2 incluye una opción que le permite completar las anotaciones de Data Infrastructure Insights con etiquetas configuradas en EC2.  Las anotaciones deben tener exactamente el mismo nombre que las etiquetas EC2.  Data Infrastructure Insights siempre completará las anotaciones de tipo texto con el mismo nombre y hará el "mejor intento" por completar las anotaciones de otros tipos (numéricos, booleanos, etc.).  Si su anotación es de un tipo diferente y el recopilador de datos no logra completarla, puede ser necesario eliminar la anotación y volver a crearla como un tipo de texto.

Tenga en cuenta que AWS distingue entre mayúsculas y minúsculas, mientras que Data Infrastructure Insights no lo hace.  Entonces, si crea una anotación llamada "PROPIETARIO" en Data Infrastructure Insights y etiquetas llamadas "PROPIETARIO", "Propietario" y "propietario" en EC2, todas las variaciones de "propietario" en EC2 se asignarán a la anotación "PROPIETARIO" de Cloud Insight.



== Incluir regiones adicionales

En la sección *Configuración avanzada* de AWS Data Collector, puede configurar el campo *Incluir regiones adicionales* para incluir regiones adicionales, separadas por coma o punto y coma.  De forma predeterminada, este campo está configurado en *_us-.*_*, que recopila datos en todas las regiones de AWS de EE. UU.  Para recopilar datos en _todas_ las regiones, configure este campo en *_.*_*.  Si el campo *Incluir regiones adicionales* está vacío, el recopilador de datos recopilará datos de los activos especificados en el campo *Región de AWS* como se especifica en la sección *Configuración*.



== Recopilación de cuentas secundarias de AWS

Data Infrastructure Insights admite la recopilación de cuentas secundarias para AWS dentro de un único recopilador de datos de AWS.  La configuración de esta colección se realiza en el entorno de AWS:

* Debe configurar cada cuenta secundaria para que tenga un rol de AWS que permita que el ID de la cuenta principal acceda a los detalles de EC2 desde la cuenta secundaria.
* Cada cuenta secundaria debe tener el nombre del rol configurado como la misma cadena.
* Ingrese esta cadena de nombre de rol en la sección *Configuración avanzada* de AWS Data Collector de Data Infrastructure Insights , en el campo *Rol entre cuentas*.
* La cuenta donde está instalado el recopilador debe tener privilegios de _administrador de acceso delegado_.  Ver ellink:https://docs.aws.amazon.com/accounts/latest/reference/using-orgs-delegated-admin.html["Documentación de AWS"] Para más información.


Práctica recomendada: se recomienda encarecidamente asignar la política _AmazonEC2ReadOnlyAccess_ predefinida de AWS a la cuenta principal de EC2.  Además, el usuario configurado en la fuente de datos debe tener al menos la política predefinida _AWSOrganizationsReadOnlyAccess_ asignada, para poder realizar consultas en AWS.

Consulte lo siguiente para obtener información sobre cómo configurar su entorno para permitir que Data Infrastructure Insights recopile información de las cuentas secundarias de AWS:

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html["Tutorial: Delegar acceso entre cuentas de AWS mediante roles de IAM"]

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_aws-accounts.html["Configuración de AWS: proporcionar acceso a un usuario de IAM en otra cuenta de AWS de su propiedad"]

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html["Creación de un rol para delegar permisos a un usuario de IAM"]



== Solución de problemas

Información adicional sobre este recopilador de datos se puede encontrar enlink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
