---
sidebar: sidebar 
permalink: task_dc_na_storagegrid.html 
summary: Configurar recopilador de datos de StorageGRID de NetApp 
keywords: data collector, queries, create, storagegrid 
---
= Recopilador de datos de NetApp StorageGRID
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
El recopilador de datos de StorageGRID de NetApp admite el inventario y la recopilación de rendimiento de las configuraciones de StorageGRID.


NOTE: La medición de StorageGRID se realiza a una tasa de TB bruta diferente a la de la unidad gestionada. Cada 40 TB de capacidad StorageGRID sin formato se carga como 1 MB link:concept_subscribing_to_cloud_insights.html#pricing["Unidad administrada (UM)"].



== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario del recopilador de NetApp StorageGRID. Para cada tipo de activo adquirido, se muestra la terminología más común utilizada para este activo. Al ver o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Plazo del proveedor/modelo | Término de información sobre la infraestructura de datos 


| StorageGRID | Reducida 


| Nodo | Nodo 


| Inquilino | Pool de almacenamiento 


| Cucharón | Volumen interno 
|===


== Requisitos

A continuación se muestran los requisitos para configurar este origen de datos:

* Dirección IP del host StorageGRID
* Nombre de usuario y contraseña para un usuario que tiene asignadas las funciones de consulta métrica y acceso de inquilino
* Puerto 443




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP del host StorageGRID | La dirección IP virtual de gestión del dispositivo StorageGRID 


| Nombre de usuario | Nombre que se utiliza para iniciar sesión en el dispositivo StorageGRID 


| Contraseña | Contraseña utilizada para iniciar sesión en el dispositivo StorageGRID 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (mín.) | El valor predeterminado es 60 minutos 


| Intervalo de sondeo de rendimiento (s) | El valor predeterminado es 900 segundos 
|===


== Inicio de sesión único (SSO)

link:https://docs.netapp.com/sgws-112/index.jsp["StorageGRID"]Las versiones de firmware tienen versiones de API correspondientes; la API 3,0 y las versiones posteriores admiten inicio de sesión único (SSO).

|===


| Versión de firmware | Versión de API | Inicio de sesión único de soporte (SSO) 


| 11,1 | 2 | No 


| 11,2 | 3,0 | Sí 


| 11,5 | 3,3 | Sí 
|===


== Resolución de problemas

Puede encontrar información adicional sobre este recopilador de datos en la link:concept_requesting_support.html["Soporte técnico"] página o en el link:reference_data_collector_support_matrix.html["Matriz de compatibilidad de recopilador de datos"].
