---
sidebar: sidebar 
permalink: task_cs_getting_started.html 
keywords: collectors, data collectors, configure, introduction, browsers, Cloud Secure 
summary: Implemente agentes de seguridad de carga de trabajo y recopiladores de datos para monitorear la actividad del usuario y detectar amenazas de seguridad. 
---
= Introducción a la seguridad de la carga de trabajo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Workload Security le ayuda a supervisar la actividad del usuario y a detectar posibles amenazas de seguridad en su entorno de almacenamiento.  Antes de poder comenzar la monitorización, es necesario configurar los agentes, los recopiladores de datos y los servicios de directorio para establecer las bases de una monitorización de seguridad integral.

El sistema de seguridad de carga de trabajo utiliza un agente para recopilar datos de acceso de los sistemas de almacenamiento e información de usuario de los servidores de servicios de directorio.

Debe configurar lo siguiente antes de poder comenzar a recopilar datos:

[cols="2*"]
|===


| Tarea | Información relacionada 


| Configurar un agente  a| 
link:concept_cs_agent_requirements.html["Requisitos del agente"]

link:task_cs_add_agent.html["Agregar agente"]



| Configurar un conector de directorio de usuarios | link:task_config_user_dir_connect.html["Agregar conector de directorio de usuarios"] 


| Configurar recopiladores de datos | Haga clic en *Seguridad de carga de trabajo > Recopiladores* Haga clic en el recopilador de datos que desea configurar. Consulte la sección de referencia del proveedor del recopilador de datos de la documentación para obtener información sobre el recopilador. 


| Crear cuentas de usuario | link:concept_user_roles.html["Administrar cuentas de usuario"] 
|===
Workload Security también puede integrarse con otras herramientas.  Por ejemplo,link:http://docs.netapp.com/us-en/cloudinsights/CloudInsights_CloudSecure_Splunk_integration_guide.pdf["ver esta guía"] sobre la integración con Splunk.
