---
sidebar: sidebar 
permalink: task_dc_na_storagegrid.html 
summary: Configurar el recopilador de datos NetApp StorageGRID 
keywords: data collector, queries, create, storagegrid 
---
= Recopilador de datos NetApp StorageGRID
:hardbreaks:
:allow-uri-read: 


[role="lead"]
El recopilador de datos StorageGRID de NetApp admite la recopilación de inventario y rendimiento de las configuraciones de StorageGRID .

[NOTE]
====
Para proporcionar una medición consistente de los derechos de DII en todos los sistemas StorageGRID independientemente de la configuración y topología del hardware subyacente, Data Infrastructure Insights utiliza la capacidad total disponible (storagegrid_storage_utilization_total_space_bytes), en lugar de la capacidad RAW basada en el diseño del disco físico.

Para los clientes que utilizan el modelo de licencia basado en capacidad, StorageGRID se mide como almacenamiento de “objetos”.

Para los clientes que utilizan el modelo de licencia heredado (MU), StorageGRID se mide como almacenamiento secundario, a una tasa de 40 TiB por 1 MU.

====


== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario del recopilador NetApp StorageGRID .  Para cada tipo de activo adquirido, se muestra la terminología más común utilizada para este activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| StorageGRID | Almacenamiento 


| Node | Node 


| Arrendatario | Pool de almacenamiento 


| Balde | Volumen interno 
|===


== Requisitos

Los siguientes son los requisitos para configurar esta fuente de datos:

* Dirección IP del host de StorageGRID
* Un nombre de usuario y una contraseña para un usuario al que se le han asignado los roles de Consulta de métricas y Acceso de inquilino
* Puerto 443




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP del host de StorageGRID | Dirección IP virtual de administración del dispositivo StorageGRID 


| Nombre de usuario | Nombre utilizado para iniciar sesión en el dispositivo StorageGRID 


| Password | Contraseña utilizada para iniciar sesión en el dispositivo StorageGRID 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (min) | El valor predeterminado es 60 minutos 


| Intervalo de sondeo de rendimiento (seg.) | El valor predeterminado es 900 segundos 
|===


== Inicio de sesión único (SSO)

Ellink:https://docs.netapp.com/sgws-112/index.jsp["StorageGRID"] Las versiones de firmware tienen versiones de API correspondientes; la API 3.0 y las versiones más nuevas admiten el inicio de sesión único (SSO).

|===


| Versión de firmware | Versión API | Admite inicio de sesión único (SSO) 


| 11,1 | 2 | No 


| 11,2 | 3,0 | Sí 


| 11,5 | 3,3 | Sí 
|===


== Solución de problemas

Información adicional sobre este recopilador de datos se puede encontrar enlink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
