---
sidebar: sidebar 
permalink: task_identify_inactive_devices.html 
keywords: inactive, device, remove, removing, identify, identifying 
summary: La identificación de dispositivos inactivos le permite elegir eliminarlos o asignarlos a un rol activo. 
---
= Identificación de dispositivos inactivos
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Identificar los activos de los que dispone y quién los utiliza es fundamental para “dimensionar correctamente” y liberar infraestructura no utilizada. Puede reasignar o retirar recursos infrautilizados fácilmente y evitar compras innecesarias.

Siga estos pasos para identificar activos inactivos.

.Pasos
* Vaya a *Observabilidad > Explorar -> +Nueva consulta de métricas*.
* Seleccione _Storage_ en la lista desplegable.
* Haga clic en el engranaje y agregue _isActive_ como columna.
+
Las filas que muestran una comprobación están activas. X indica los dispositivos inactivos.



Para eliminar dispositivos inactivos, simplemente seleccione los dispositivos que desea eliminar y en el menú desplegable * Acciones masivas *, seleccione _Eliminar dispositivos inactivos_.
