---
sidebar: sidebar 
permalink: task_dc_dell_xc_series.html 
keywords: data collector, Dell, EMC, xc 
summary: Configuración del recopilador de datos Dell EMC XC Series. 
---
= Recopilador de datos de la serie EMC XC de Dell
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utiliza este recopilador de datos para descubrir información de inventario y rendimiento de las matrices de almacenamiento Dell EMC XC Series.



== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP externa del prisma | Dirección IP del servidor XC 


| Nombre de usuario | Nombre de usuario del servidor XC 


| Contraseña | Contraseña utilizada para el servidor XC 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Puerto TCP | Puerto utilizado para la comunicación TCP con el servidor XC 


| Intervalo de sondeo de inventario (mín.) | Intervalo entre sondeos de inventario. El valor predeterminado es 60 minutos. 


| Intervalo de sondeo de rendimiento (mín.) | Intervalo entre sondeos de rendimiento. El valor predeterminado es 300 segundos. 
|===


== Resolución de problemas

Puede encontrar información adicional en la link:concept_requesting_support.html["Soporte técnico"] página o en el link:reference_data_collector_support_matrix.html["Matriz de compatibilidad de recopilador de datos"].
