---
sidebar: sidebar 
permalink: task_create_annotation_rules.html 
summary: Crea reglas de anotación para aplicar anotaciones automáticamente a múltiples activos. 
keywords: annotate, annotation, rules 
---
= Creación de reglas de anotación
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede utilizar reglas de anotación para aplicar anotaciones automáticamente a varios activos según los criterios que defina.  Data Infrastructure Insights asigna las anotaciones a los activos según estas reglas.  Las anotaciones configuradas manualmente en las páginas de activos individuales tienen prioridad sobre las anotaciones basadas en reglas cuando Cloud Insight evalúa las reglas de anotación.

.Antes de empezar
Debes haber creado una consulta para la regla de anotación.

.Pasos
. En el menú Data Infrastructure Insights, haga clic en *Administrar > Reglas de anotación*.
. Haga clic en *+ Regla* para agregar una nueva regla de anotación.
+
Se muestra el cuadro de diálogo Agregar regla.

. Haga lo siguiente:
+
.. En el cuadro *Nombre*, ingrese un nombre único que describa la regla.
+
El nombre aparece en la página Reglas de anotación.

.. Haga clic en *Consulta* y seleccione la consulta que Data Infrastructure Insights utiliza para identificar los activos a los que se aplica la anotación.
.. Haga clic en *Anotación* y seleccione la anotación que desea aplicar.
.. Haga clic en *Valor* y seleccione un valor para la anotación.
+
Por ejemplo, si elige Cumpleaños como anotación, especifica una fecha para el valor.

.. Haga clic en *Guardar*
.. Haga clic en *Ejecutar todas las reglas* si desea ejecutar todas las reglas inmediatamente; de lo contrario, las reglas se ejecutarán en un intervalo programado regularmente.
+

NOTE: En un entorno de Data Infrastructure Insights de gran tamaño, es posible que notes que la ejecución de las reglas de anotación parece tardar un tiempo en completarse.  Esto se debe a que el indexador se ejecuta primero y debe completarse antes de ejecutar las reglas.  El indexador es lo que le da a Data Infrastructure Insights la capacidad de buscar o filtrar objetos y contadores nuevos o actualizados en sus datos.  El motor de reglas espera hasta que el indexador complete su actualización antes de aplicar las reglas.







== Modificar las reglas de anotación

Puede modificar una regla de anotación para cambiar el nombre de la regla, su anotación, el valor de la anotación o la consulta asociada con la regla.

.Pasos
. En el menú Data Infrastructure Insights , haga clic en *Administrar > Reglas de anotación*.
+
La página Reglas de anotación muestra la lista de reglas de anotación existentes.

. Localice la regla de anotación que desea modificar.
+
Puede filtrar las reglas de anotación ingresando un valor en el cuadro de filtro o haciendo clic en un número de página para explorar las reglas de anotación por página.

. Haga clic en el icono de menú de la regla que desea modificar.
. Haga clic en *Editar*
+
Se muestra el cuadro de diálogo Editar regla.

. Modificar el nombre de la regla de anotación, la anotación, el valor o la consulta.




== Cambiar el orden de las reglas

Las reglas de anotación se procesan desde la parte superior de la lista de reglas hasta la parte inferior.  Para cambiar el orden en que se procesa una regla, haga lo siguiente:

.Pasos
. Haga clic en el icono de menú de la regla que desea mover.
. Haga clic en *Mover hacia arriba* o *Mover hacia abajo* según sea necesario hasta que la regla aparezca en la ubicación que desee.


Tenga en cuenta que al ejecutar varias reglas que actualizan la misma anotación en un activo, la primera regla (ejecutada de arriba hacia abajo) aplica la anotación y actualiza el activo; luego, la segunda regla se aplica pero no cambia ninguna anotación que ya haya sido establecida por la regla anterior.



== Eliminar reglas de anotación

Es posible que desees eliminar las reglas de anotación que ya no se utilizan.

.Pasos
. En el menú Data Infrastructure Insights , haga clic en *Administrar > Reglas de anotación*.
+
La página Reglas de anotación muestra la lista de reglas de anotación existentes.

. Localice la regla de anotación que desea eliminar.
+
Puede filtrar las reglas de anotación ingresando un valor en el cuadro de filtro o haciendo clic en un número de página para explorar las reglas de anotación por página.

. Haga clic en el icono de menú de la regla que desea eliminar.
. Haga clic en *Eliminar*
+
Se muestra un mensaje de confirmación preguntándole si desea eliminar la regla.

. Haga clic en *Aceptar*

