---
sidebar: sidebar 
permalink: task_create_annotation.html 
keywords: annotations, annotation rules, manual annotations, 
summary: Cómo crear una anotación. 
---
= Uso de anotaciones
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Crea anotaciones y asígnalas a los activos que supervisas.  Las anotaciones son notas que proporcionan información sobre un activo, como la ubicación física, el final de su vida útil, el nivel de almacenamiento o los niveles de servicio de volumen.



== Definición de anotaciones

Al usar anotaciones, puede agregar datos personalizados específicos de su negocio que coincidan con las necesidades de su negocio y sus activos.  Si bien Data Infrastructure Insights proporciona un conjunto de anotaciones predeterminadas, como el ciclo de vida del activo (fecha de nacimiento o fin de vida útil), la ubicación del edificio o centro de datos y el nivel, es posible que desee ver los datos de otras maneras.

Los datos en las anotaciones personalizadas complementan los datos del dispositivo ya recopilados, como el fabricante del conmutador, la cantidad de puertos y las estadísticas de rendimiento.  Data Infrastructure Insights no descubre los datos que agrega mediante anotaciones.

.Antes de empezar
* Enumere cualquier terminología industrial a la que se deben asociar los datos ambientales.
* Enumere la terminología corporativa a la que se deben asociar los datos del entorno.
* Identifique cualquier tipo de anotación predeterminado que pueda utilizar.
* Identifique qué anotaciones personalizadas necesita crear.  Debe crear la anotación antes de poder asignarla a un activo.


Utilice los siguientes pasos para crear una anotación.

.Pasos
. En el menú Data Infrastructure Insights , haga clic en *Observabilidad > Enriquecer > Anotaciones*
. Haga clic en *+ Anotación * para crear una nueva anotación.
. Ingrese un nombre, una descripción y un tipo para la nueva anotación.
+
Por ejemplo, ingrese lo siguiente para crear una anotación de texto que defina la ubicación física de un activo en el Centro de datos 4:

+
** Ingrese un nombre para la anotación, como "Ubicación".
** Ingrese una descripción de lo que describe la anotación, como "La ubicación física es el Centro de datos 4".
** Ingrese el 'tipo' de anotación que es, por ejemplo "Texto".






== Asignar anotaciones manualmente a los activos

Asignar anotaciones a los activos le ayuda a ordenarlos, agruparlos y generar informes sobre ellos de maneras relevantes para su negocio.  Si bien puede asignar anotaciones a activos de un tipo particular automáticamente mediante reglas de anotación, puede asignar anotaciones a un activo individual mediante su página de activos.

.Antes de empezar
* Debes haber creado la anotación que deseas asignar.


.Pasos
. Inicie sesión en su entorno de Data Infrastructure Insights .
. Localice el activo al que desea aplicar la anotación.
+
** Puede localizar activos mediante consultas, eligiendo desde un widget del panel o buscando.  Cuando haya localizado el activo que desea, haga clic en el enlace para abrir la página de destino del activo.


. En la página de activos, en la sección Datos de usuario, haga clic en *+ Anotación*.
. Se muestra el cuadro de diálogo Agregar anotación.
. Seleccione una anotación de la lista.
. Haga clic en Valor y realice una de las siguientes acciones, según el tipo de anotación que haya seleccionado:
+
** Si el tipo de anotación es lista, fecha o booleano, seleccione un valor de la lista.
** Si el tipo de anotación es texto, escriba un valor.


. Haga clic en *Guardar*.


Si desea cambiar el valor de la anotación después de asignarla, haga clic en el campo de anotación y seleccione un valor diferente.  Si la anotación es de tipo lista para la cual está seleccionada la opción _Agregar nuevos valores sobre la marcha_, puede escribir un nuevo valor además de seleccionar un valor existente.



== Asignar anotaciones mediante reglas de anotación

Para asignar automáticamente anotaciones a los activos según los criterios que usted defina, configure reglas de anotación.  Data Infrastructure Insights asigna las anotaciones a los activos según estas reglas.  Data Infrastructure Insights también proporciona dos reglas de anotación predeterminadas, que puede modificar para adaptarlas a sus necesidades o eliminarlas si no desea utilizarlas.



=== Creación de reglas de anotación

Como alternativa a la aplicación manual de anotaciones a activos individuales, puede aplicar anotaciones automáticamente a múltiples activos utilizando reglas de anotación.  Las anotaciones configuradas manualmente en las páginas de activos individuales tienen prioridad sobre las anotaciones basadas en reglas cuando Insight evalúa las reglas de anotación.

.Antes de empezar
Debes haber creado una consulta para la regla de anotación.

.Acerca de esta tarea
Aunque puedes editar los tipos de anotación mientras creas las reglas, debes haber definido los tipos con anticipación.

.Pasos
. Haga clic en *Administrar > Reglas de anotación*
+
La página Reglas de anotación muestra la lista de reglas de anotación existentes.

. Haga clic en *+ Agregar*.
. Haga lo siguiente:
+
.. En el cuadro *Nombre*, ingrese un nombre único que describa la regla.
+
Este nombre aparecerá en la página Reglas de anotación.

.. Haga clic en *Consulta* y seleccione la consulta que se utiliza para aplicar la anotación a los activos.
.. Haga clic en *Anotación* y seleccione la anotación que desea aplicar.
.. Haga clic en *Valor* y seleccione un valor para la anotación.
+
Por ejemplo, si elige Cumpleaños como anotación, especifica una fecha para el valor.

.. Haga clic en *Guardar*
.. Haga clic en *Ejecutar todas las reglas* si desea ejecutar todas las reglas inmediatamente; de lo contrario, las reglas se ejecutarán en un intervalo programado regularmente.



