---
sidebar: sidebar 
permalink: task_dc_ms_hyperv.html 
keywords: data collector, Microsoft, Hyper-V 
summary: Configuración del recopilador de datos de Microsoft Hyper-V. 
---
= Recopilador de datos de Microsoft Hyper-V
:hardbreaks:
:allow-uri-read: 


[role="lead"]
El recopilador de datos de Microsoft Hyper-V adquiere datos de inventario y rendimiento del entorno informático del servidor virtualizado.  Este recopilador de datos puede descubrir un host Hyper-V independiente o un clúster completo: cree un recopilador por cada host o clúster independiente.



== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario de Microsoft Hyper-V (WMI).  Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más común utilizada para este activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Disco duro virtual | Disco virtual 


| Host | Host 


| Máquina virtual | Máquina virtual 


| Volúmenes compartidos de clúster (CSV), volumen de partición | Almacén de datos 


| Dispositivo SCSI de Internet, LUN SCSI de múltiples rutas | LUN 


| Puerto de canal de fibra | Puerto 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

Para configurar este recopilador de datos se requiere lo siguiente:

* Hyper-V requiere que el puerto 5985 esté abierto para la recopilación de datos y el acceso/administración remotos.
* Dirección IP o FQDN del clúster o hipervisor independiente.  El uso del nombre de host o IP del clúster flotante es probablemente el enfoque más confiable en comparación con apuntar el recopilador a solo un nodo específico en un clúster.
* Cuenta de usuario de nivel administrativo que funciona en todos los hipervisores del clúster.
* WinRM debe estar habilitado y escuchando en todos los hipervisores
* Requisitos del puerto: Puerto 135 a través de WMI y puertos TCP dinámicos asignados 1024-65535 para Windows 2003 y anteriores y 49152-65535 para Windows 2008.
* La resolución de DNS debe tener éxito, incluso si el recopilador de datos apunta solo a una dirección IP
* Cada hipervisor Hyper-V debe tener activada la “Medición de recursos” para cada máquina virtual, en cada host.  Esto permite que cada hipervisor tenga más datos disponibles para Data Infrastructure Insights en cada invitado.  Si esto no se configura, se adquirirán menos métricas de rendimiento para cada invitado.  Puede encontrar más información sobre la medición de recursos en la documentación de Microsoft:
+
link:https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh831661(v=ws.11)["Descripción general de la medición de recursos de Hyper-V"]

+
link:https://docs.microsoft.com/en-us/powershell/module/hyper-v/enable-vmresourcemetering?view=win10-ps["Habilitar VMResourceMetering"]




NOTE: El recopilador de datos de Hyper-V requiere una unidad de adquisición de Windows.



== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP del clúster o FQDN del clúster flotante | La dirección IP o el nombre de dominio completo para el clúster o un hipervisor independiente y no agrupado 


| Nombre de usuario | Nombre de usuario administrador para el hipervisor 


| Password | Contraseña para el hipervisor 


| Sufijo de dominio DNS | El sufijo del nombre de host que se combina con el nombre de host simple para representar el FQDN de un hipervisor 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (min) | El valor predeterminado es 20 minutos. 
|===


== Solución de problemas

Información adicional sobre este recopilador de datos se puede encontrar enlink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
