---
sidebar: sidebar 
permalink: task_dc_hds_hcp.html 
keywords: data collector, Hitachi HDS, HCP 
summary: Configurar el recopilador de datos de HDS. 
---
= Recopilador de datos de Hitachi HCP
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Este recopilador de datos admite la Plataforma de Contenido Hitachi (HCP) que utiliza la API de Gestión de HCP.


NOTE: La Plataforma de Contenido de Hitachi se evalúa con una tasa de TB bruta diferente a la de la Unidad administrada. Cada 40 TB de capacidad de HCP sin formato se carga como 1link:concept_subscribing_to_cloud_insights.html#pricing["Unidad administrada (UM)"].



== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario del recopilador de datos HCP de Hitachi. Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más habitual utilizada para este activo. Al ver o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Plazo del proveedor/modelo | Término de información sobre la infraestructura de datos 


| Clúster HCP | Reducida 


| Inquilino | Pool de almacenamiento 


|  | Espacio de nombres 


| Volumen interno | Nodo 
|===
Nota: Sólo son asignaciones de terminología comunes y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos de inventario

Para recopilar datos de inventario, debe contar con lo siguiente:

* Dirección IP del servidor HCP
* Nombre de usuario y contraseña de sólo lectura para el software HCP y los privilegios del mismo nivel




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Host HCP | Dirección IP o nombre de dominio completo del host HCP 


| Puerto HCP | El valor predeterminado es 9090 


| ID Usuario HCP | Nombre de usuario del host HCP. 


| Contraseña de HCP | Contraseña utilizada para el host HCP. 


| Tipo de autenticación HCP | Elija HCP_LOCAL o ACTIVE_DIRECTORY 
|===


== Configuración avanzada

|===


| Campo | Descripción 


| Intervalo de sondeo de inventario (mín.) | Intervalo entre sondeos de inventario. El valor predeterminado es 60. 


| Intervalo de sondeo de rendimiento (s) | Intervalo entre sondeos de rendimiento. El valor predeterminado es 900. 
|===
Puede encontrar información adicional en la link:concept_requesting_support.html["Soporte técnico"] página o en el link:reference_data_collector_support_matrix.html["Matriz de compatibilidad de recopilador de datos"].
