---
sidebar: sidebar 
permalink: task_dc_hds_nas.html 
keywords: data collector, HDS HNAS, HDS NAS 
summary: 'Configuración del recopilador de datos HDS NAS (HNAS).' 
---
= Configuración del recopilador de datos NAS de Hitachi Vantara
:hardbreaks:
:allow-uri-read: 


[role="lead"]
El recopilador de datos NAS de Hitachi Vantara es un recopilador de datos de inventario y configuración que admite el descubrimiento de clústeres NAS HDS.  Data Infrastructure Insights admite el descubrimiento de recursos compartidos NFS y CIFS, sistemas de archivos (volúmenes internos) y tramos (grupos de almacenamiento).



== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario del recopilador de datos HNAS.  Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más común utilizada para este activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Nivel | Grupo de discos 


| Grupo | Almacenamiento 


| Node | Nodo de almacenamiento 


| Durar | Pool de almacenamiento 


| Unidad del sistema | Lun de backend 


| Sistema de archivos | Volumen interno 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

* Dirección IP del dispositivo
* Puerto 22, protocolo SSH
* Nombre de usuario y contraseña - nivel de privilegio: Supervisor
* Nota: Este recopilador de datos está basado en SSH, por lo que la AU que lo aloja debe poder iniciar sesiones SSH en TCP 22 en el propio HNAS o en la unidad de administración de sistemas (SMU) a la que está conectado el clúster.




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Anfitrión de HNAS | Dirección IP o nombre de dominio completo del host de administración de HNAS 


| Nombre de usuario | Nombre de usuario para HNAS CLI 


| Password | Contraseña utilizada para HNAS CLI 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (min) | Intervalo entre sondeos de inventario. El valor predeterminado es 30 minutos. 
|===


== Solución de problemas

Algunas cosas que puedes probar si encuentras problemas con este recopilador de datos:



=== Inventario

[cols="2*"]
|===
| Problema: | Prueba esto: 


| "Error de conexión" con mensajes de error "Error al configurar el canal de shell:" o "Error al abrir el canal de shell" | Probablemente se deba a problemas de conectividad de red o a que SSH está mal configurado.  Confirmar la conexión con el cliente SSH alternativo 


| "Tiempo de espera agotado" o "Error al recuperar datos" con mensajes de error "El comando: XXX ha expirado". | * Pruebe el comando con un cliente SSH alternativo * Aumente el tiempo de espera 


| Error de conexión o Credenciales de inicio de sesión no válidas con el mensaje "No se pudo comunicar con el dispositivo". | * Verificar la dirección IP * Verificar el nombre de usuario y la contraseña * Confirmar la conexión con el cliente SSH alternativo 
|===
Información adicional se puede encontrar en ellink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
