---
sidebar: sidebar 
permalink: task_dc_lenovo.html 
keywords: data collector,Lenovo, HX Series 
summary: Configuración del recopilador de datos de Lenovo. 
---
= Recopilador de datos de Lenovo
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utiliza el recopilador de datos de Lenovo para descubrir datos de inventario y rendimiento de los sistemas de almacenamiento Lenovo HX.

Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

* Dirección IP externa de Prism
* Nombre de usuario y contraseña del administrador
* Requisito de puerto TCP: 9440




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP externa de Prism | La dirección IP de los servicios de datos externos para el clúster 


| Nombre de usuario | Nombre de usuario para la cuenta de administrador 


| Password | Contraseña para la cuenta de administrador 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Puerto TCP | Puerto TCP utilizado para conectarse a la matriz.  El valor predeterminado es 9440. 


| Intervalo de sondeo de inventario (min) | Intervalo entre sondeos de inventario. El valor predeterminado es 60 minutos. 


| Intervalo de sondeo de rendimiento (seg.) | Intervalo entre encuestas de rendimiento. El valor predeterminado es 300 segundos. 
|===


== Solución de problemas

Información adicional sobre este recopilador de datos se puede encontrar enlink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
