---
sidebar: sidebar 
permalink: task_cs_user_management.html 
keywords: Workload Security, User, Login, account, cloud secure 
summary: Seguridad de la carga de trabajo Las cuentas de usuario se administran a través de la gestión de usuarios de Data Infrastructure Insights 
---
= Gestión de usuarios
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Las cuentas de usuario de Workload Security se administran a través de Data Infrastructure Insights.

Data Infrastructure Insights proporciona cuatro niveles de cuenta de usuario: Propietario de la cuenta, Administrador, Usuario e Invitado.  A cada cuenta se le asignan niveles de permisos específicos.  Una cuenta de usuario que tenga privilegios de administrador puede crear o modificar usuarios y asignar a cada usuario uno de los siguientes roles de seguridad de carga de trabajo:

|===


| Role | Acceso de seguridad a la carga de trabajo 


| Administrador | Puede realizar todas las funciones de seguridad de carga de trabajo, incluidas las de alertas, análisis forense, recopiladores de datos, políticas de respuesta automatizadas y API para seguridad de carga de trabajo.  Un administrador también puede invitar a otros usuarios, pero solo puede asignar roles de seguridad de carga de trabajo. 


| Usuario | Puede ver y administrar alertas y ver análisis forenses.  El rol de usuario puede cambiar el estado de alerta, agregar una nota, tomar instantáneas manualmente y restringir el acceso de los usuarios. 


| Invitado | Puede ver alertas y análisis forenses.  El rol de invitado no puede cambiar el estado de alerta, agregar una nota, tomar instantáneas manualmente ni restringir el acceso de los usuarios. 
|===
.Pasos
. Iniciar sesión en Seguridad de la carga de trabajo
. En el menú, haga clic en *Admin > Gestión de usuarios*
+
Serás redirigido a la página de Administración de usuarios de Data Infrastructure Insights.

. Seleccione el rol deseado para cada usuario.


Al agregar un nuevo usuario, simplemente seleccione el rol deseado (generalmente Usuario o Invitado).

Puede encontrar más información sobre las cuentas y roles de usuario en Data Infrastructure Insightslink:https://docs.netapp.com/us-en/cloudinsights/concept_user_roles.html["Rol de usuario"] documentación.
