---
sidebar: sidebar 
permalink: task_dc_ibm_cs.html 
keywords: data collector, IBM CS, CS Series 
summary: Configurar el recopilador de datos de IBM CS. 
---
= Recopilador de datos IBM CS
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utiliza este recopilador de datos para descubrir los datos de inventario y rendimiento de los sistemas de almacenamiento IBM CS.



== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario del recopilador de datos de IBM CS. Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más habitual utilizada para este activo. Al ver o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Plazo del proveedor/modelo | Término de información sobre la infraestructura de datos 


| Pool de almacenamiento | Pool de almacenamiento 


| Contenedor | Volumen interno 


| Contenedor | Recurso compartido de archivos 


| Recurso compartido NFS | Share 
|===
Nota: Sólo son asignaciones de terminología comunes y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

* La dirección IP de servicios de datos externos para el clúster
* Nombre de usuario y contraseña del administrador
* Puerto 9440




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP externa del prisma | La dirección IP de servicios de datos externos para el clúster 


| Nombre de usuario | Nombre de usuario de la cuenta de administrador 


| Contraseña | Contraseña para la cuenta de administrador 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Puerto TCP | Puerto TCP utilizado para conectarse a la matriz IBM CS. El valor predeterminado es 9440. 


| Intervalo de sondeo de inventario (min) | Intervalo entre sondeos de inventario. El valor predeterminado es 60 minutos. 


| Intervalo de sondeo de rendimiento (s) | Intervalo entre sondeos de rendimiento. El valor predeterminado es 300 segundos. 
|===


== Resolución de problemas

Puede encontrar información adicional sobre este recopilador de datos en la link:concept_requesting_support.html["Soporte técnico"] página o en el link:reference_data_collector_support_matrix.html["Matriz de compatibilidad de recopilador de datos"].
