---
sidebar: sidebar 
permalink: task_dc_oracle_zfs.html 
keywords: data collector, Oracle, ZFS, storage applicance 
summary: Configuración del recopilador de datos de Oracle ZFS. 
---
= Recopilador de datos de Oracle ZFS Storage Appliance
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utiliza el recopilador de datos de Oracle ZFS Storage Appliance para reunir datos de inventario y rendimiento.



== Terminología

Data Infrastructure Insights adquiere información de inventario con el recopilador de datos Oracle ZFS.  Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más común utilizada para este activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Disco (SSD) | Disco 


| Grupo | Almacenamiento 


| Controladora | Nodo de almacenamiento 


| LUN | Volumen 


| Mapa LUN | Mapa de volumen 


| Iniciador, Objetivo | Máscara de volumen 


| Compartir | Volumen interno 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de esta fuente de datos.



== Requisitos

* Nombres de host para el controlador ZFS-1 y el controlador ZFS-2
* Nombre de usuario y contraseña del administrador
* Requisito de puerto: 215 HTTP/HTTPS




== Métricas de rendimiento requeridas

Los dispositivos Oracle ZFS brindan a los administradores de almacenamiento grandes cantidades de flexibilidad para capturar estadísticas de rendimiento.  Data Infrastructure Insights espera que _cada_ controlador en un par de alta disponibilidad esté configurado para capturar las siguientes métricas:

* smb2.ops[compartir]
* nfs3.ops[compartir]
* nfs4.ops[compartir]
* nfs4-1.ops[compartir]


Si el controlador no logra capturar alguno o todos estos datos, es probable que Data Infrastructure Insights no tenga o no informe la carga de trabajo en los "Volúmenes internos".



== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Nombre de host del controlador ZFS-1 | Nombre de host para el controlador de almacenamiento 1 


| Nombre de host del controlador ZFS-2 | Nombre de host para el controlador de almacenamiento 2 


| Nombre de usuario | Nombre de usuario para la cuenta de usuario del administrador del sistema de almacenamiento 


| Password | Contraseña para la cuenta de usuario administrador 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Tipo de conexión | HTTPS o HTTP, también muestra el puerto predeterminado 


| Anular puerto de conexión | Si está en blanco, utilice el puerto predeterminado en el campo Tipo de conexión; de lo contrario, ingrese el puerto de conexión a utilizar. 


| Intervalo de sondeo de inventario | El valor predeterminado es 60 segundos. 


| Intervalo de encuesta de rendimiento (seg.) | El valor predeterminado es 300. 
|===


== Solución de problemas

Algunas cosas que puedes probar si encuentras problemas con este recopilador de datos:



=== Inventario

[cols="2a, 2a"]
|===
| Problema: | Prueba esto: 


 a| 
"Credenciales de inicio de sesión no válidas"
 a| 
Validar la cuenta de usuario y la contraseña de Zfs



 a| 
"La solicitud falló con el estado 404 \https://.....:215/api/access/v1"
 a| 
Es posible que su matriz ZFS sea demasiado antigua para tener soporte de API REST.  AK 2013.1.3.0 fue la primera versión del sistema operativo ZFS compatible con API REST, y no todos los dispositivos ZFS pueden actualizarse a ella.



 a| 
"Error de configuración" con el mensaje de error "El servicio REST está deshabilitado"
 a| 
Verifique que el servicio REST esté habilitado en este dispositivo.



 a| 
"Error de configuración" con el mensaje de error "Usuario no autorizado para el comando"
 a| 
Es probable que este error se deba a que ciertos roles (por ejemplo, 'advanced_analytics') no están incluidos para el usuario configurado.

La aplicación del ámbito de Analytics para el usuario con rol de solo lectura puede eliminar el error. Siga estos pasos:

. En el sistema ZFs, desde la pantalla Configuración -> Usuarios, mueva el mouse sobre el rol y haga doble clic para permitir la edición
. Seleccione “Análisis” en el menú desplegable Alcance.  Aparece una lista de las posibles propiedades.
. Haga clic en la casilla de verificación superior y se seleccionarán las tres propiedades.
. Haga clic en el botón Agregar en el lado derecho.
. Haga clic en el botón Aplicar en la parte superior derecha de la ventana emergente.  La ventana emergente se cerrará.


|===
Información adicional se puede encontrar en ellink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
