---
sidebar: sidebar 
permalink: task_cs_delete_agent.html 
keywords: agent, Workload Security, delete agent, Cloud Secure 
summary: Eliminación de agentes de seguridad de carga de trabajo 
---
= Eliminar un agente de seguridad de carga de trabajo
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Cuando se elimina un agente de seguridad de carga de trabajo, primero se deben eliminar todos los recopiladores de datos asociados con el agente.



== Eliminar un agente


IMPORTANT: Al eliminar un agente se eliminan todos los recopiladores de datos asociados con el agente.  Si planea configurar los recopiladores de datos con un agente diferente, debe crear una copia de seguridad de las configuraciones del recopilador de datos antes de eliminar el agente.

.Antes de empezar
. Asegúrese de que todos los recopiladores de datos asociados con el agente se eliminen del portal de seguridad de carga de trabajo.
+
Nota: Ignore este paso si todos los recolectores asociados están en estado DETENIDO.



.Pasos para eliminar un Agente:
. Inicie sesión en la máquina virtual del agente mediante SSH y ejecute el siguiente comando.  Cuando se le solicite, ingrese "y" para continuar.
+
....
sudo /opt/netapp/cloudsecure/agent/install/cloudsecure-agent-uninstall.sh
Uninstall CloudSecure Agent? [y|N]:
....
. Haga clic en *Seguridad de la carga de trabajo > Recopiladores > Agentes*
+
El sistema muestra la lista de Agentes configurados.

. Haga clic en el menú de opciones del Agente que está eliminando.
. Haga clic en *Eliminar*.
+
El sistema muestra la página *Eliminar agente*.

. Haga clic en *Eliminar* para confirmar la eliminación.

