---
sidebar: sidebar 
permalink: task_config_cs_incloud.html 
keywords: Cloud, Storage, AWS, Cloud Volumes, Cloud ONTAP, firewall, VPC, Subnet,  cloud secure 
summary: Configure los recopiladores de datos de seguridad de carga de trabajo para Cloud Volumes ONTAP y Amazon FSx for NetApp ONTAP para monitorear el acceso a archivos, la actividad del usuario y detectar amenazas en su infraestructura de almacenamiento en la nube. 
---
= Configuración del recopilador Cloud Volumes ONTAP y Amazon FSx for NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Supervise el acceso de usuarios y archivos en su infraestructura de almacenamiento en la nube configurando los recopiladores de datos de Workload Security para Cloud Volumes ONTAP y Amazon FSx for NetApp ONTAP. Esta guía proporciona instrucciones paso a paso para implementar agentes en AWS y conectarlos a sus instancias de almacenamiento en la nube.



== Configuración de almacenamiento de Cloud Volumes ONTAP

Consulte la documentación de OnCommand Cloud Volumes ONTAP para configurar una instancia de AWS de nodo único/HA para alojar el agente de seguridad de carga de trabajo:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html[]

Una vez completada la configuración, siga los pasos para configurar su SVM:https://docs.netapp.com/us-en/cloudinsights/task_add_collector_svm.html[]



== Plataformas compatibles

* Cloud Volumes ONTAP, compatible con todos los proveedores de servicios en la nube disponibles donde sea posible.  Por ejemplo: Amazon, Azure, Google Cloud.
* ONTAP Amazon FSx




== Configuración de la máquina del agente

La máquina del agente debe configurarse en las subredes respectivas de los proveedores de servicios en la nube.  Obtenga más información sobre el acceso a la red en [Requisitos del agente].

A continuación se muestran los pasos para la instalación del agente en AWS.  Se pueden seguir pasos equivalentes, según corresponda al proveedor de servicios en la nube, en Azure o Google Cloud para la instalación.

En AWS, utilice los siguientes pasos para configurar la máquina que se utilizará como agente de seguridad de carga de trabajo:

Utilice los siguientes pasos para configurar la máquina que se utilizará como agente de seguridad de carga de trabajo:

.Pasos
. Inicie sesión en la consola de AWS, navegue a la página Instancias EC2 y seleccione _Iniciar instancia_.
. Seleccione una AMI de RHEL o CentOS con la versión adecuada como se menciona en esta página:https://docs.netapp.com/us-en/cloudinsights/concept_cs_agent_requirements.html[]
. Seleccione la VPC y la subred en la que reside la instancia de Cloud ONTAP .
. Seleccione _t2.xlarge_ (4 vcpus y 16 GB de RAM) como recursos asignados.
+
.. Cree la instancia EC2.


. Instale los paquetes de Linux necesarios utilizando el administrador de paquetes YUM:
+
.. Instalar _wget_ y _unzip_ paquetes nativos de Linux.






== Instalar el agente de seguridad de carga de trabajo

. Inicie sesión como administrador o propietario de cuenta en su entorno de Data Infrastructure Insights .
. Vaya a *Recopiladores* de seguridad de carga de trabajo y haga clic en la pestaña *Agentes*.
. Haga clic en *+Agente* y especifique RHEL como la plataforma de destino.
. Copie el comando de instalación del agente.
. Pegue el comando de instalación del agente en la instancia RHEL EC2 en la que ha iniciado sesión.  Esto instala el agente de seguridad de carga de trabajo, que proporciona toda lalink:concept_cs_agent_requirements.html["Requisitos previos del agente"] se cumplen.


Para conocer los pasos detallados, consulte este enlace: https://docs.netapp.com/us-en/cloudinsights/task_cs_add_agent.html#steps-to-install-agent



== Solución de problemas

Los problemas conocidos y sus resoluciones se describen en la siguiente tabla.

|===


| Problema | Resolución 


| El recopilador de datos muestra el error “Seguridad de la carga de trabajo: No se pudo determinar el tipo de ONTAP para el recopilador de datos de Amazon FxSN”.  El cliente no puede agregar un nuevo recopilador de datos de Amazon FSxN a Workload Security.  La conexión al clúster FSxN en el puerto 443 desde el agente está agotando el tiempo de espera.  Los grupos de seguridad de firewall y AWS tienen las reglas necesarias habilitadas para permitir la comunicación.  Ya hay un agente implementado y también está en la misma cuenta de AWS.  Este mismo agente se utiliza para conectar y supervisar los dispositivos NetApp restantes (y todos están funcionando). | Resuelva este problema agregando el segmento de red LIF fsxadmin a la regla de seguridad del agente.  Se permiten todos los puertos si no está seguro acerca de ellos. 
|===