---
sidebar: sidebar 
permalink: task_query_copy_table_values.html 
summary: Puede copiar valores de una tabla al portapapeles para usarlos en otras aplicaciones. 
keywords: query, queries, copy, values, clipboard 
---
= Copiar valores de la tabla
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Puede copiar valores de las tablas al portapapeles para usarlos en cuadros de búsqueda u otras aplicaciones.

.Acerca de esta tarea
Hay dos métodos que puede utilizar para copiar valores de tablas o resultados de consultas al portapapeles.

.Pasos
. Método 1: Resalte el texto deseado con el mouse, cópielo y péguelo en los campos de búsqueda u otras aplicaciones.
. Método 2: Para campos de valor único, pase el cursor sobre el campo y haga clic en el ícono del portapapeles que aparece.  El valor se copia al portapapeles para su uso en campos de búsqueda u otras aplicaciones.
+
Tenga en cuenta que solo se pueden copiar valores que sean vínculos a activos utilizando este método.  Sólo los campos que incluyen valores únicos (es decir, no listas) tienen el ícono de copia.


