---
sidebar: sidebar 
permalink: task_dc_nutanix.html 
keywords: data collector, Nutanix, NX Series 
summary: Configurar el recopilador de datos de Nutanix. 
---
= Recopilador de datos Nutanix NX
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Data Infrastructure Insights utiliza el recopilador de datos Nutanix para detectar datos de inventario y rendimiento de los sistemas de almacenamiento Nutanix NX.



== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario del recopilador de datos Nutanix. Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más habitual utilizada para este activo. Al ver o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Plazo del proveedor/modelo | Término de información sobre la infraestructura de datos 


| Pool de almacenamiento | Pool de almacenamiento 


| Contenedor Nutanix | Volumen interno 


| Contenedor Nutanix | Recurso compartido de archivos 


| Recurso compartido NFS | Share 
|===
Nota: Sólo son asignaciones de terminología comunes y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

* La dirección IP de servicios de datos externos para el clúster
* El nombre de usuario y la contraseña de solo lectura, a menos que volume_groups estén en uso, en cuyo caso, se requieren el nombre de usuario y la contraseña del administrador
* Requisito de puerto: HTTPS 443




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP externa del prisma | La dirección IP de servicios de datos externos para el clúster 


| Nombre de usuario | Nombre de usuario de la cuenta de administrador 


| Contraseña | Contraseña para la cuenta de administrador 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Puerto TCP | Puerto TCP utilizado para conectarse a la cabina Nutanix. El valor predeterminado es 9440. 


| Intervalo de sondeo de inventario (min) | Intervalo entre sondeos de inventario. El valor predeterminado es 60 minutos. 


| Intervalo de sondeo de rendimiento (s) | Intervalo entre sondeos de rendimiento. El valor predeterminado es 300 segundos. 
|===


== Resolución de problemas

Puede encontrar información adicional sobre este recopilador de datos en la link:concept_requesting_support.html["Soporte técnico"] página o en el link:reference_data_collector_support_matrix.html["Matriz de compatibilidad de recopilador de datos"].
