---
sidebar: sidebar 
permalink: task_dc_emc_vnx_unified.html 
keywords: data collector, VNX, EMC, Dell 
summary: Configuración del recopilador de datos VNX. 
---
= Configuración del recopilador de datos unificado de Dell EMC VNX
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Para la configuración, el recopilador de datos Dell EMC VNX Unified (SSH) requiere la dirección IP de la estación de control y un nombre de usuario y contraseña de solo lectura.



== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario de este recopilador de datos.  Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más común utilizada para este activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Disco | Disco 


| Carpeta de disco | Grupo de discos 


| Sistema de archivos | Volumen interno 


| Almacenamiento | Almacenamiento 


| Procesador de almacenamiento | Nodo de almacenamiento 


| Pool de almacenamiento, grupo RAID | Pool de almacenamiento 


| LUN | Volumen 


| Transferencia de datos | Controladora 


| Sistema de archivos montado en un transportador de datos | Compartir archivos 


| Exportaciones CIFS y NFS | Compartir 


| Volumen del disco | LUN de backend 
|===


== Requisitos

Necesita lo siguiente para configurar el recopilador de datos VNX (SSH):

* Dirección IP y credenciales de VNX para la estación de control Celerra.
* Nombre de usuario y contraseña de sólo lectura.
* El recopilador de datos puede ejecutar comandos NaviCLI/NaviSecCLI contra la matriz de backend utilizando los cabezales NAS del sistema operativo DART




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP de VNX | Dirección IP o nombre de dominio completo de la estación de control VNX 


| Nombre de usuario | Nombre de usuario para la estación de control VNX 


| Password | Contraseña para la estación de control VNX 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (min) | Intervalo entre sondeos de inventario. El valor predeterminado es 40 minutos. 


| Intervalo de encuesta de rendimiento (seg). | Intervalo entre encuestas de rendimiento. El valor predeterminado es 300 segundos. 
|===


== Solución de problemas

Información adicional sobre este recopilador de datos se puede encontrar enlink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
