---
sidebar: sidebar 
permalink: task_dc_emc_recoverpoint.html 
keywords: data collector, RecoverPoint, EMC, DELL 
summary: Configuración del recopilador de datos de DELL EMC RecoverPoint. 
---
= Recopilador de datos de Dell EMC RecoverPoint
:hardbreaks:
:allow-uri-read: 


[role="lead"]
El caso de uso principal del recopilador de datos de EMC RecoverPoint es descubrir las relaciones de replicación de volumen a volumen que facilita el dispositivo de almacenamiento RecoverPoint.  Este recopilador también descubrirá el propio dispositivo Recoverpoint.  Tenga en cuenta que Dell/EMC vende una solución de respaldo de VMware para máquinas virtuales, "RecoverPoint para máquinas virtuales", que no es compatible con este recopilador.

Para la configuración, el recopilador de datos requiere la dirección IP de los procesadores de almacenamiento y un nombre de usuario y contraseña de solo lectura.

El recopilador de datos de EMC RecoverPoint reúne las relaciones de replicación de volumen a volumen que RecoverPoint coordina entre otras matrices de almacenamiento.  Data Infrastructure Insights muestra una matriz de almacenamiento para cada clúster de RecoverPoint y recopila datos de inventario de los nodos y puertos de almacenamiento en ese clúster.  No se recopilan datos de volumen ni de grupo de almacenamiento.



== Requisitos

Se requiere la siguiente información para configurar este recopilador de datos:

* Dirección IP o nombre de dominio completo del procesador de almacenamiento
* Nombre de usuario y contraseña de solo lectura
* Acceso a la API REST a través del puerto 443




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección de RecoverPoint | Dirección IP o nombre de dominio completo del clúster de RecoverPoint 


| Nombre de usuario | Nombre de usuario para el clúster de RecoverPoint 


| Password | Contraseña utilizada para el clúster de RecoverPoint 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Puerto TCP | Puerto TCP utilizado para conectarse al clúster de Recoverpoint 


| Intervalo de sondeo de inventario (minutos) | Intervalo entre sondeos de inventario. El valor predeterminado es 20 minutos. 


| Clústeres excluidos | Lista separada por comas de ID o nombres de clústeres que se excluirán durante el sondeo. 
|===


== Solución de problemas

Información adicional sobre este recopilador de datos se puede encontrar enlink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
