---
sidebar: sidebar 
permalink: task_dc_nutanix_ahv.html 
keywords: data collector, Nutanix, AHV Series , Acropolis, hypervisor 
summary: Configurando el recopilador de datos de Nutanix AHV. 
---
= Recopilador de datos de Nutanix AHV
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El colector de Nutanix AHV recopila el inventario y el rendimiento de la virtualización de Nutanix Acropolis Hypervisor (AHV) desde Nutanix Prism Central usando las REST APIs de Prism Central v4 (Cluster Management y Virtual Machine Management namespaces). Informa los datos en el modelo OData de virtualización (VirtualizationRoot y entidades relacionadas: hosts, máquinas virtuales, almacenes de datos, discos virtuales y relaciones).



[[terminology]]
== Terminología

[cols="50,50"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Nodo AHV (host) | Host 


| Cluster Central de Prism | Hipervisor (servidor virtual) 


| Acropolis VM | Máquina virtual 


| Contenedor de almacenamiento | Almacén de datos 


| Grupo de volúmenes ADSF | LUN 


| Disco de la máquina virtual | Disco virtual 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de este recopilador de datos.



[[requirements]]
== Requisitos

* Dirección IP de Prism Central o nombre de dominio completo
* Nombre de usuario y contraseña locales o LDAP de Prism Central (basta con una cuenta de solo lectura)
* Requisito de puerto: HTTPS 9440
* Prism Central version pc.2023.x o posterior (API v3); se recomienda pc.7.x o posterior (API v4)
* Las métricas de rendimiento requieren Prism Central con API v4.0.b1 o posterior (pc.7.3+). En versiones anteriores, se recopila el inventario pero no se reportan datos de rendimiento.




[[configuration]]
== Configuración

[cols="50,50"]
|===
| Campo | Descripción 


| IP de Prism Central / Nombre de host | Dirección IP o FQDN de la instancia de Prism Central 


| Nombre de usuario | Nombre de usuario de Prism Central 


| Password | Contraseña de Prism Central 
|===


[[advanced-configuration]]
== Configuración avanzada

[cols="50,50"]
|===
| Campo | Descripción 


| Puerto TCP | Puerto TCP utilizado para conectarse a Prism Central. El valor predeterminado es 9440. 


| Intervalo de sondeo de inventario (min) | Intervalo entre las consultas de inventario. El valor predeterminado es 60 minutos. 


| Intervalo de sondeo de rendimiento (seg.) | Intervalo entre las encuestas de rendimiento. El valor predeterminado es 300 segundos. 


| Tiempo de espera HTTP (seg) | Tiempo de espera de la solicitud HTTP. El valor predeterminado es 60. 


| Número de reintentos HTTP | Número de reintentos HTTP en caso de fallos transitorios. El valor por defecto es 3. 
|===


[[troubleshooting]]
== Solución de problemas

Información adicional sobre este recopilador de datos se puede encontrar enlink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
