---
sidebar: sidebar 
permalink: task_dc_aws_s3.html 
keywords: data collector, S3, Storage 
summary: Configuración de AWS S3 como recopilador de datos de almacenamiento. 
---
= Configuración de AWS S3 como recopilador de datos de almacenamiento
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utiliza AWS S3 como recopilador de datos de almacenamiento para adquirir datos de inventario y rendimiento de las instancias de AWS S3.



== Requisitos

Para recopilar datos de AWS S3 como dispositivos de almacenamiento, debe tener la siguiente información:

* Debes tener uno de los siguientes:
+
** El *rol de IAM* para su cuenta en la nube de AWS, si utiliza la autenticación de rol de IAM.  La función IAM solo se aplica si su unidad de adquisición está instalada en una instancia de AWS.
** El ID de *clave de acceso IAM* y la clave de acceso secreta para su cuenta en la nube de AWS, si utiliza la autenticación de clave de acceso IAM.


* Debes tener el privilegio de "organización de lista"
* Puerto 443 HTTPS
* Las instancias de AWS S3 se pueden informar como una máquina virtual o (de forma menos natural) un host.  Los volúmenes EBS se pueden informar como un disco virtual utilizado por la máquina virtual, así como también como un almacén de datos que proporciona la capacidad para el disco virtual.


Las claves de acceso constan de un ID de clave de acceso (por ejemplo, AKIAIOSFODNN7EXAMPLE) y una clave de acceso secreta (por ejemplo, wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY).  Utilice claves de acceso para firmar solicitudes programáticas que realice a AWS si utiliza los SDK de AWS, REST o operaciones de API de consulta.  Estas claves se proporcionan con su contrato de Amazon.



== Configuración

Introduzca datos en los campos del recopilador de datos de acuerdo con la siguiente tabla:

[cols="2*"]
|===
| Campo | Descripción 


| Región de AWS | Elija la región de AWS 


| Rol de IAM | Solo para uso cuando se adquiere en una AU en AWS.  Vea a continuación para obtener más información sobre<<iam-role,Rol de IAM>> . 


| ID de clave de acceso de AWS IAM | Ingrese el ID de clave de acceso de AWS IAM.  Obligatorio si no utiliza el rol IAM. 


| Clave de acceso secreta de AWS IAM | Ingrese la clave de acceso secreta de AWS IAM.  Obligatorio si no utiliza el rol IAM. 


| Entiendo que AWS me factura las solicitudes de API. | Marque esto para verificar su comprensión de que AWS le factura las solicitudes de API realizadas mediante el sondeo de Data Infrastructure Insights . 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Rol de cuenta cruzada | Rol para acceder a recursos en diferentes cuentas de AWS. 


| Intervalo de sondeo de inventario (min) | El valor predeterminado es 60 


| Seleccione “Excluir” o “Incluir” para aplicar el filtro de máquinas virtuales por etiquetas | Especifique si desea incluir o excluir máquinas virtuales por etiquetas al recopilar datos.  Si se selecciona “Incluir”, el campo Clave de etiqueta no puede estar vacío. 


| Intervalo de encuesta de rendimiento (seg.) | El valor predeterminado es 1800 
|===


== Clave de acceso de IAM

Las claves de acceso son credenciales a largo plazo para un usuario de IAM o el usuario raíz de la cuenta de AWS.  Las claves de acceso se utilizan para firmar solicitudes programáticas a la AWS CLI o la API de AWS (directamente o mediante el AWS SDK).

Las claves de acceso constan de dos partes: un ID de clave de acceso y una clave de acceso secreta.  Cuando utiliza la autenticación _Clave de acceso IAM_ (a diferencia de la autenticación _Rol IAM_), debe usar tanto el ID de la clave de acceso como la clave de acceso secreta juntas para la autenticación de las solicitudes.  Para obtener más información, consulte la documentación de Amazon enlink:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html["Teclas de acceso"] .



== Rol de IAM

Al utilizar la autenticación _IAM Role_ (a diferencia de la autenticación de clave de acceso IAM), debe asegurarse de que el rol que crea o especifica tenga los permisos adecuados necesarios para acceder a sus recursos.

Por ejemplo, si crea un rol de IAM llamado _InstanceS3ReadOnly_, debe configurar la política para otorgar permiso de acceso a la lista de solo lectura de S3 a todos los recursos de S3 para este rol de IAM.  Además, debe otorgar acceso a STS (Servicio de token de seguridad) para que este rol pueda asumir roles en varias cuentas.

Después de crear una función de IAM, puede adjuntarla cuando cree una nueva instancia de S3 o cualquier instancia de S3 existente.

Después de adjuntar la función IAM _InstanceS3ReadOnly_ a una instancia S3, podrá recuperar la credencial temporal a través de los metadatos de la instancia por nombre de función IAM y usarla para acceder a los recursos de AWS mediante cualquier aplicación que se ejecute en esta instancia S3.

Para obtener más información, consulte la documentación de Amazon enlink:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html["Roles de IAM"] .

Nota: La función IAM solo se puede usar cuando la unidad de adquisición se ejecuta en una instancia de AWS.



== Asignación de etiquetas de Amazon a anotaciones de Data Infrastructure Insights

El recopilador de datos de AWS S3 como almacenamiento incluye una opción que le permite completar las anotaciones de Data Infrastructure Insights con etiquetas configuradas en S3.  Las anotaciones deben tener exactamente el mismo nombre que las etiquetas de AWS.  Data Infrastructure Insights siempre completará las anotaciones de tipo texto con el mismo nombre y hará el "mejor intento" por completar las anotaciones de otros tipos (numéricos, booleanos, etc.).  Si su anotación es de un tipo diferente y el recopilador de datos no logra completarla, puede ser necesario eliminar la anotación y volver a crearla como un tipo de texto.

Tenga en cuenta que AWS distingue entre mayúsculas y minúsculas, mientras que Data Infrastructure Insights no lo hace.  Entonces, si crea una anotación llamada "PROPIETARIO" en Data Infrastructure Insights y etiquetas llamadas "PROPIETARIO", "Propietario" y "propietario" en S3, todas las variaciones de "propietario" de S3 se asignarán a la anotación "PROPIETARIO" de Cloud Insight.



== Recopilación de cuentas secundarias de AWS

Data Infrastructure Insights admite la recopilación de cuentas secundarias para AWS dentro de un único recopilador de datos de AWS.  La configuración de esta colección se realiza en el entorno de AWS:

* Debe configurar cada cuenta secundaria para que tenga un rol de AWS que permita que el ID de la cuenta principal acceda a los detalles de S3 desde la cuenta secundaria.
* Cada cuenta secundaria debe tener el nombre del rol configurado como la misma cadena.
* Ingrese esta cadena de nombre de rol en la sección *Configuración avanzada* de AWS Data Collector de Data Infrastructure Insights , en el campo *Rol entre cuentas*.
* La cuenta donde está instalado el recopilador debe tener privilegios de _administrador de acceso delegado_.  Ver ellink:https://docs.aws.amazon.com/accounts/latest/reference/using-orgs-delegated-admin.html["Documentación de AWS"] Para más información.


Práctica recomendada: se recomienda encarecidamente asignar la política _AmazonS3ReadOnlyAccess_ predefinida de AWS a la cuenta principal de S3.  Además, el usuario configurado en la fuente de datos debe tener al menos la política predefinida _AWSOrganizationsReadOnlyAccess_ asignada, para poder realizar consultas en AWS.

Consulte lo siguiente para obtener información sobre cómo configurar su entorno para permitir que Data Infrastructure Insights recopile información de las cuentas secundarias de AWS:

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html["Tutorial: Delegar acceso entre cuentas de AWS mediante roles de IAM"]

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_aws-accounts.html["Configuración de AWS: proporcionar acceso a un usuario de IAM en otra cuenta de AWS de su propiedad"]

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html["Creación de un rol para delegar permisos a un usuario de IAM"]



== Solución de problemas

Información adicional sobre este recopilador de datos se puede encontrar enlink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
