---
sidebar: sidebar 
permalink: task_dc_hpe_nimble.html 
keywords: data collector, HP Nimble, HP, HPE, Alletra 6000 
summary: 'Configuración del recopilador de datos HP Enterprise Alletra 6000 (anteriormente Nimble).' 
---
= Recopilador de datos HPE Alletra 6000
:hardbreaks:
:allow-uri-read: 


[role="lead"]
El recopilador de datos HP Enterprise Alletra 6000 (anteriormente Nimble) admite datos de inventario y rendimiento para matrices de almacenamiento Alletra 6000.



== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario de este recopilador.  Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más común utilizada para este activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Formación | Almacenamiento 


| Disco | Disco 


| Volumen | Volumen 


| Pool | Pool de almacenamiento 


| Iniciador | Alias de host de almacenamiento 


| Controladora | Nodo de almacenamiento 


| Interfaz de canal de fibra | Controladora 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

Debe tener lo siguiente para poder recopilar datos de inventario y configuración de la matriz de almacenamiento:

* La matriz debe estar instalada y configurada, y ser accesible desde el cliente a través de su nombre de dominio completo (FQDN) o dirección IP de administración de matriz.
* La matriz debe ejecutar NimbleOS 2.3.x o posterior.
* Debe tener un nombre de usuario y una contraseña válidos para la matriz con al menos un rol de nivel "Operador".  El rol "Invitado" no tiene acceso suficiente para comprender las configuraciones del iniciador.
* El puerto 5392 debe estar abierto en la matriz.


Debe tener lo siguiente para poder recopilar datos de rendimiento de la matriz de almacenamiento:

* La matriz debe ejecutar NimbleOS 4.0.0 o posterior
* La matriz debe tener volúmenes configurados.  La única API de rendimiento que tiene NimbleOS es para volúmenes, y todas las estadísticas que informa Data Infrastructure Insights se derivan de las estadísticas sobre volúmenes.




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP de administración de matriz | Nombre de dominio completo (FQDN) o dirección IP de administración de matriz. 


| Nombre de usuario | Nombre de usuario para la matriz 


| Password | Contraseña para la matriz 
|===


== Configuración avanzada

|===


| Campo | Descripción 


| Puerto | Puerto utilizado por la API REST de Nimble.  El valor predeterminado es 5392. 


| Intervalo de sondeo de inventario (min) | Intervalo entre sondeos de inventario. El valor predeterminado es 60 minutos. 
|===
Nota: El intervalo de sondeo de rendimiento predeterminado es de 300 segundos y no se puede cambiar.  Este es el único intervalo compatible con HPE Alletra 6000.
