---
sidebar: sidebar 
permalink: task_dc_ms_anf.html 
keywords: data collector, azure, Netapp files, anf 
summary: Configuración del recopilador de datos de Azure NetApp Files . 
---
= Configuración del recopilador de datos de Azure NetApp Files
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utiliza el recopilador de datos de Azure NetApp Files para adquirir datos de inventario y rendimiento.



== Requisitos

Necesita la siguiente información para configurar este recopilador de datos.

* Requisito de puerto: 443 HTTPS
* IP Rest de administración de Azure (management.azure.com)
* Identificador de cliente de entidad de servicio de Azure (cuenta de usuario)
* Clave de autenticación de entidad de servicio de Azure (contraseña de usuario)
* Debe configurar una cuenta de Azure para el descubrimiento de Data Infrastructure Insights .
+
Una vez que la cuenta esté configurada correctamente y registres la aplicación en Azure, tendrás las credenciales necesarias para descubrir la instancia de Azure con Data Infrastructure Insights.  El siguiente enlace describe cómo configurar la cuenta para el descubrimiento:



https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal[]



== Configuración

Introduzca datos en los campos del recopilador de datos de acuerdo con la siguiente tabla:

[cols="2*"]
|===
| Campo | Descripción 


| ID de cliente de entidad de servicio de Azure | ID de inicio de sesión en Azure 


| ID de inquilino de Azure | ID de inquilino de Azure 


| Clave de autenticación de entidad de servicio de Azure | Clave de autenticación de inicio de sesión 


| Entiendo que Microsoft me factura las solicitudes de API. | Marque esto para verificar su comprensión de que Microsoft le factura las solicitudes de API realizadas mediante el sondeo de Insight. 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (min) | El valor predeterminado es 60 
|===


== Solución de problemas

* Las credenciales utilizadas por el recopilador de datos ANF deben tener acceso a cualquier suscripción de Azure que contenga volúmenes ANF.
* Si el acceso del lector provoca que la recopilación de rendimiento falle, intente otorgar acceso de colaborador a nivel de grupo de recursos.


Información adicional sobre este recopilador de datos se puede encontrar enlink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
