---
sidebar: sidebar 
permalink: task_research_failed_collector.html 
keywords: data collector, changes, failures 
summary: Errores del recopilador de datos 
---
= Investigando un recopilador de datos fallido
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Si un recopilador de datos tiene un mensaje de error y un Impacto alto o medio, debe investigar este problema utilizando la página de resumen del recopilador de datos con su información vinculada.

Utilice los siguientes pasos para determinar la causa de los recopiladores de datos fallidos.  Los mensajes de error del recopilador de datos se muestran en el menú *Admin* y en la página *Recopiladores de datos instalados*.

.Pasos
. Haga clic en *Admin* > *Recopiladores de datos* > *Recopiladores de datos instalados*.
. Haga clic en el nombre vinculado del recopilador de datos que falla para abrir la página Resumen.
. En la página Resumen, consulte el área Comentarios para leer cualquier nota que pueda haber dejado otro ingeniero que también pueda estar investigando esta falla.
. Tenga en cuenta todos los mensajes de rendimiento.
. Mueva el puntero del mouse sobre los segmentos del gráfico de la línea de tiempo de eventos para mostrar información adicional.
. Seleccione un mensaje de error para un dispositivo y muestrelo debajo de la línea de tiempo del evento y haga clic en el ícono Detalles del error que se muestra a la derecha del mensaje.
+
Los detalles del error incluyen el texto del mensaje de error, las causas más probables, la información en uso y sugerencias de lo que se puede intentar para corregir el problema.

. En el área Dispositivos informados por este recopilador de datos, puede filtrar la lista para mostrar solo los dispositivos de interés y puede hacer clic en el *Nombre* vinculado de un dispositivo para mostrar la página de activos de ese dispositivo.
. Cuando regrese a la página de resumen del recopilador de datos, verifique el área *Mostrar cambios recientes* en la parte inferior de la página para ver si los cambios recientes podrían haber causado el problema.

