---
sidebar: sidebar 
permalink: task_dc_emc_vnx_block.html 
keywords: data collector, EMC, clariion, VNX block 
summary: 'Configuración de DELL EMC VNX Block Storage (anteriormente CLARiiON).' 
---
= Recopilador de datos de almacenamiento en bloque Dell EMC VNX (NaviCLI)
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utiliza el recopilador de datos Dell EMC VNX Block Storage (NaviSec) (anteriormente CLARiiON) para adquirir datos de inventario y rendimiento.



== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario del recopilador de datos de almacenamiento en bloque EMC VNX.  Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más común utilizada para este activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Disco | Disco 


| Almacenamiento | Almacenamiento 


| Procesador de almacenamiento | Nodo de almacenamiento 


| Este grupo, RAID Group | Pool de almacenamiento 


| LUN | Volumen 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de esta fuente de datos.



== Requisitos

Para poder recopilar datos se deben cumplir los siguientes requisitos:

* Una dirección IP de cada procesador de almacenamiento en bloque VNX
* Nombre de usuario y contraseña de Navisphere de solo lectura para las matrices de almacenamiento en bloque VNX
* NaviSecCli debe estar instalado en Data Infrastructure Insights AU
* Validación de acceso: ejecute NaviSecCLI desde la AU de Data Infrastructure Insights en cada matriz usando el nombre de usuario y la contraseña.
* Requisitos del puerto: 80, 443
* La versión de NaviSecCLI debe corresponder con el código FLARE más nuevo en su matriz
* Para el rendimiento, el registro de estadísticas debe estar habilitado.




== Sintaxis de la interfaz de línea de comandos de NaviSphere

naviseccli.exe -h <dirección IP> -user <usuario> -password <contraseña> -scope <alcance, use 0 para alcance global> -port <use 443 por defecto> comando



== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP de almacenamiento en bloque VNX | Dirección IP o nombre de dominio completo del almacenamiento en bloque VNX 


| Nombre de usuario | Nombre utilizado para iniciar sesión en el dispositivo de almacenamiento en bloque VNX. 


| Password | Contraseña utilizada para iniciar sesión en el dispositivo de almacenamiento en bloque VNX. 


| Ruta CLI a naviseccli.exe | Ruta completa a la carpeta que contiene el ejecutable _naviseccli.exe_ 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (min) | Intervalo entre sondeos de inventario.  El valor predeterminado es 40 minutos. 


| Alcance | El ámbito del cliente seguro.  El valor predeterminado es Global. 


| Intervalo de encuesta de rendimiento (seg.) | Intervalo entre encuestas de rendimiento. El valor predeterminado es 300 segundos. 
|===


== Solución de problemas

Algunas cosas que puedes probar si encuentras problemas con este recopilador de datos:



=== Inventario

[cols="2a, 2a"]
|===
| Problema: | Prueba esto: 


 a| 
Error:

* El agente no se está ejecutando
* No se pudo encontrar naviseccli
* No se pudo ejecutar ningún comando

 a| 
* Confirme que NaviSphere CLI esté instalado en la unidad de adquisición de Cloud Insight
* No ha seleccionado la opción "Usar cliente seguro" en el asistente de configuración del recopilador de datos y no tiene instalada una versión no segura de Naviphere CLI.
* Confirme que el directorio de instalación de NaviSphere CLI sea correcto en la configuración del recopilador de datos
* Confirme que la IP del almacenamiento en bloque VNX sea correcta en la configuración del recopilador de datos:
* De la Unidad de Adquisición de Data Infrastructure Insights :
+
** Abra un CMD.
** Cambie el directorio al directorio de instalación configurado
** Intente establecer una conexión con el dispositivo de almacenamiento en bloque VNX escribiendo “navicli -h {ip} getagent” (reemplace {ip} con la IP real)






 a| 
Error: 4.29 emc235848 emc241018 getall No se pudo analizar la información del alias del host
 a| 
Es probable que esto se deba a un problema de corrupción de FLARE 29 en la base de datos del iniciador del host en la matriz misma.  Consulte los artículos de la base de conocimientos de EMC: emc235848, emc241018.  También puedes consultar https://now.netapp.com/Knowledgebase/solutionarea.asp?id=kb58128[]



 a| 
Error: No se pueden recuperar los Meta LUN.  Error al ejecutar java -jar navicli.jar
 a| 
* Modificar la configuración del recopilador de datos para utilizar el cliente seguro (recomendado)
* Instale navicli.jar en la ruta CLI a navicli.exe O naviseccli.exe
* Nota: navicli.jar está obsoleto a partir de la versión 6.26 de EMC Navisphere
* El navicli.jar puede estar disponible en http://powerlink.emc.com




 a| 
Error: Los grupos de almacenamiento no informan los discos en el procesador de servicio en la dirección IP configurada
 a| 
Configure el recopilador de datos con ambas IP del procesador de servicio, separadas por una coma



 a| 
Error: Error de falta de coincidencia de revisión
 a| 
* Generalmente, esto se debe a la actualización del firmware en el dispositivo de almacenamiento en bloque VNX, pero no a la actualización de la instalación de NaviCLI.exe.  Esto también podría deberse a tener diferentes dispositivos con diferentes firmwares, pero solo una CLI instalada (con una versión de firmware diferente).
* Verifique que tanto el dispositivo como el host estén ejecutando versiones idénticas del software:
+
** Desde la Unidad de Adquisición de Data Infrastructure Insights , abra una ventana de línea de comandos
** Cambie el directorio al directorio de instalación configurado
** Establezca una conexión con el dispositivo CLARiiON escribiendo “navicli -h <ip> getagent”
** Busque el número de versión en las primeras líneas.  Ejemplo: “Rev. del agente: 6.16.2 (0.1)”
** Busque y compare la versión en la primera línea.  Ejemplo: “Navisphere CLI Revisión 6.07.00.04.07”






 a| 
Error: Configuración no compatible - No hay puertos de canal de fibra
 a| 
El dispositivo no está configurado con ningún puerto Fibre Channel.  Actualmente, solo se admiten configuraciones FC.  Verifique que esta versión/firmware sea compatible.

|===
Información adicional se puede encontrar en ellink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
