---
sidebar: sidebar 
permalink: task_modify_delete_query.html 
summary: Modificar o eliminar una consulta 
keywords: query, queries, modify, edit, delete, remove 
---
= Modificar o eliminar una consulta
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Puede cambiar los criterios asociados a una consulta cuando desee cambiar los criterios de búsqueda de los activos que está consultando.



== Modificar una consulta

.Pasos
. Haga clic en *Explorar* y seleccione *Todas las consultas métricas*.
+
Se muestra la página Consultas.

. Haga clic en el nombre de la consulta
. Para agregar un criterio a la consulta, haga clic en el ícono Columnas y seleccione una métrica o atributo de la lista.


Cuando haya realizado todos los cambios necesarios, realice una de las siguientes acciones:

* Haga clic en el botón *Guardar* para guardar la consulta con el nombre utilizado inicialmente.
* Haga clic en el menú desplegable junto al botón *Guardar* y seleccione *Guardar como* para guardar la consulta con otro nombre.  Esto no sobrescribe la consulta original.
* Haga clic en el menú desplegable junto al botón *Guardar* y seleccione *Cambiar nombre* para cambiar el nombre de la consulta que utilizó inicialmente.  Esto sobrescribe la consulta original.
* Haga clic en el menú desplegable junto al botón *Guardar* y seleccione *Descartar cambios* para revertir la consulta a los últimos cambios guardados.




== Eliminar una consulta

Para eliminar una consulta, haga clic en *Consultas* y seleccione *Mostrar todas las consultas*, y realice una de las siguientes acciones:

. Haga clic en el menú de "tres puntos" a la derecha de la consulta y haga clic en *Eliminar*.
. Haga clic en el nombre de la consulta y seleccione *Eliminar* en el menú desplegable *Guardar*.

