---
sidebar: sidebar 
permalink: task_dc_na_cdot.html 
keywords: data collector, ontap, ontap, CDOT 
summary: Recopilador de datos de ONTAP 
---
= Recopilador de datos del software de gestión de datos NetApp ONTAP
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Este recopilador de datos adquiere datos de inventario y rendimiento de los sistemas de almacenamiento que ejecutan ONTAP mediante llamadas API de solo lectura desde una cuenta de ONTAP .  Este recopilador de datos también crea un registro en el registro de aplicaciones del clúster para acelerar el soporte.



== Terminología

Data Infrastructure Insights adquiere datos de inventario y rendimiento del recopilador de datos ONTAP .  Para cada tipo de activo adquirido, se muestra la terminología más común utilizada para el activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Disco | Disco 


| Grupo de incursión | Grupo de discos 


| Grupo | Almacenamiento 


| Node | Nodo de almacenamiento 


| Agregar | Pool de almacenamiento 


| LUN | Volumen 


| Volumen | Volumen interno 
|===


== Terminología de gestión de datos de ONTAP

Los siguientes términos se aplican a objetos o referencias que pueda encontrar en las páginas de inicio de activos de almacenamiento de ONTAP Data Management.  Muchos de estos términos se aplican también a otros recopiladores de datos.



=== Almacenamiento

* Modelo: una lista delimitada por comas de los nombres de modelos de nodos únicos y discretos dentro de este clúster.  Si todos los nodos de los clústeres son del mismo tipo de modelo, solo aparecerá un nombre de modelo.
* Proveedor: el mismo nombre de proveedor que vería si estuviera configurando una nueva fuente de datos.
* Número de serie: el número de serie de la matriz.  En sistemas de almacenamiento con arquitectura de clúster como ONTAP Data Management, este número de serie puede ser menos útil que los números de serie de los “Nodos de almacenamiento” individuales.
* IP: generalmente serán las IP o los nombres de host configurados en la fuente de datos.
* Versión de microcódigo – firmware.
* Capacidad bruta: suma en base 2 de todos los discos físicos del sistema, independientemente de su función.
* Latencia: una representación de lo que experimenta el host que enfrenta cargas de trabajo, tanto en lecturas como en escrituras.  Lo ideal sería que Data Infrastructure Insights obtenga este valor directamente, pero a menudo no es así.  En lugar de que la matriz ofrezca esto, Data Infrastructure Insights generalmente realiza un cálculo ponderado por IOP derivado de las estadísticas de los volúmenes internos individuales.
* Rendimiento: agregado a partir de volúmenes internos.  Administración: puede contener un hipervínculo a la interfaz de administración del dispositivo.  Creado programáticamente por la fuente de datos Data Infrastructure Insights como parte del informe de inventario.




=== Pool de almacenamiento

* Almacenamiento: en qué matriz de almacenamiento reside este grupo.  Obligatorio.
* Tipo: un valor descriptivo de una lista de una lista enumerada de posibilidades.  Lo más común será “Agregado” o “Grupo RAID”.
* Nodo: si la arquitectura de esta matriz de almacenamiento es tal que los grupos pertenecen a un nodo de almacenamiento específico, su nombre se verá aquí como un hipervínculo a su propia página de destino.
* Utiliza Flash Pool – Valor Sí/No – ¿este pool basado en SATA/SAS tiene SSD utilizados para aceleración de almacenamiento en caché?
* Redundancia – Nivel RAID o esquema de protección.  RAID_DP es paridad dual, RAID_TP es paridad triple.
* Capacidad: los valores aquí son la capacidad lógica utilizada, la capacidad utilizable y la capacidad total lógica, y el porcentaje utilizado en estas.
* Capacidad sobrecomprometida: si al usar tecnologías de eficiencia ha asignado una suma total de capacidades de volumen o de volumen interno mayor que la capacidad lógica del grupo de almacenamiento, el valor porcentual aquí será mayor a 0 %.
* Instantánea: capacidades de instantáneas utilizadas y totales, si la arquitectura de su grupo de almacenamiento dedica parte de su capacidad a áreas de segmentos exclusivamente para instantáneas.  Es probable que ONTAP en configuraciones MetroCluster presenten esto, mientras que otras configuraciones de ONTAP lo presentan en menor medida.
* Utilización: valor porcentual que muestra el mayor porcentaje de ocupación del disco de cualquier disco que aporte capacidad a este grupo de almacenamiento.  La utilización del disco no necesariamente tiene una fuerte correlación con el rendimiento de la matriz: la utilización puede ser alta debido a reconstrucciones de disco, actividades de deduplicación, etc. en ausencia de cargas de trabajo impulsadas por el host.  Además, las implementaciones de replicación de muchas matrices pueden impulsar la utilización del disco sin mostrarse como volumen interno o carga de trabajo de volumen.
* IOPS: la suma de IOPS de todos los discos que aportan capacidad a este grupo de almacenamiento.  Rendimiento: el rendimiento total de todos los discos que aportan capacidad a este grupo de almacenamiento.




=== Nodo de almacenamiento

* Almacenamiento: de qué matriz de almacenamiento forma parte este nodo.  Obligatorio.
* Socio de HA: en plataformas donde un nodo fallará en uno y solo otro nodo, generalmente se verá aquí.
* Estado – salud del nodo.  Solo está disponible cuando la matriz está lo suficientemente saludable como para ser inventariada por una fuente de datos.
* Modelo: nombre del modelo del nodo.
* Versión – nombre de la versión del dispositivo.
* Número de serie: el número de serie del nodo.
* Memoria: memoria base 2 si está disponible.
* Utilización: en ONTAP, este es un índice de estrés del controlador de un algoritmo propietario.  Con cada encuesta de rendimiento, se informará un número entre 0 y 100 %, que es el mayor entre la contención del disco WAFL o la utilización promedio de la CPU.  Si observa valores sostenidos > 50%, esto es indicativo de un tamaño insuficiente: posiblemente un controlador/nodo no lo suficientemente grande o no hay suficientes discos giratorios para absorber la carga de trabajo de escritura.
* IOPS: derivado directamente de las llamadas ZAPI de ONTAP en el objeto de nodo.
* Latencia: se deriva directamente de las llamadas ZAPI de ONTAP en el objeto de nodo.
* Rendimiento: derivado directamente de las llamadas ZAPI de ONTAP en el objeto de nodo.
* Procesadores – Cantidad de CPU.




== Requisitos

Los siguientes son los requisitos para configurar y utilizar este recopilador de datos:

* Debe tener acceso a una cuenta de administrador configurada para llamadas API de solo lectura.
* Los detalles de la cuenta incluyen nombre de usuario y contraseña.
* Requisitos del puerto: 80 o 443
* Permisos de la cuenta:
+
** Nombre del rol de solo lectura para la aplicación ontapi en el Vserver predeterminado
** Es posible que necesite permisos de escritura opcionales adicionales.  Consulte la nota sobre permisos a continuación.


* Requisitos de licencia de ONTAP :
+
** Se requieren licencia FCP y volúmenes mapeados/enmascarados para el descubrimiento del canal de fibra






=== Requisitos de permisos para recopilar métricas de conmutadores ONTAP

Data Infrastructure Insights tiene la capacidad de recopilar datos de conmutadores de clúster de ONTAP como una opción en el recopilador.<<advanced-configuration,Configuración avanzada>> ajustes.  Además de habilitar esto en el recopilador de Data Infrastructure Insights , también debe *configurar el sistema ONTAP * para proporcionarlink:https://docs.netapp.com/us-en/ontap-cli-98/system-switch-ethernet-create.html["información del interruptor"] , y garantizar la correcta<<a-note-about-permissions,permisos>> se configuran para permitir que los datos del conmutador se envíen a Data Infrastructure Insights.



== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| IP de gestión de NetApp | Dirección IP o nombre de dominio completo del clúster de NetApp 


| Nombre de usuario | Nombre de usuario para el clúster de NetApp 


| Password | Contraseña para el clúster de NetApp 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Tipo de conexión | Elija HTTP (puerto predeterminado 80) o HTTPS (puerto predeterminado 443).  El valor predeterminado es HTTPS 


| Anular puerto de comunicación | Especifique un puerto diferente si no desea utilizar el predeterminado 


| Intervalo de sondeo de inventario (min) | El valor predeterminado es 60 minutos. 


| Para TLS para HTTPS | Solo permitir TLS como protocolo cuando se utiliza HTTPS 


| Buscar grupos de red automáticamente | Habilitar las búsquedas automáticas de grupos de redes para las reglas de política de exportación 


| Expansión del grupo de red | Estrategia de expansión de Netgroup.  Elija _archivo_ o _shell_.  El valor predeterminado es _shell_. 


| Tiempo de espera de lectura HTTP en segundos | El valor predeterminado es 30 


| Respuestas de fuerza como UTF-8 | Obliga al código del recopilador de datos a interpretar las respuestas de la CLI como si estuvieran en UTF-8 


| Intervalo de encuesta de rendimiento (seg.) | El valor predeterminado es 900 segundos. 


| Recopilación avanzada de datos de contadores | Habilitar la integración de ONTAP .  Seleccione esta opción para incluir datos del Contador avanzado de ONTAP en las encuestas.  Seleccione los contadores deseados de la lista. 


| Métricas de conmutación de clúster | Permitir que Data Infrastructure Insights recopile datos de conmutación de clúster.  Tenga en cuenta que además de habilitar esto en el lado de Data Infrastructure Insights , también debe configurar el sistema ONTAP para proporcionarlink:https://docs.netapp.com/us-en/ontap-cli-98/system-switch-ethernet-create.html["información del interruptor"] , y garantizar la correcta<<a-note-about-permissions,permisos>> se configuran para permitir que los datos del conmutador se envíen a Data Infrastructure Insights.  Consulte "Una nota sobre los permisos" a continuación. 
|===


== Métricas de potencia de ONTAP

Varios modelos de ONTAP proporcionan métricas de potencia para Data Infrastructure Insights que se pueden usar para monitorear o generar alertas.


NOTE: Estas listas no son exhaustivas y están sujetas a cambios.  En general, si un modelo pertenece a la misma familia que uno de la lista, el soporte debería ser el mismo, pero no se garantiza que lo sea.  Si no está seguro de si su modelo admite métricas de energía, comuníquese con el soporte de ONTAP .

Modelos compatibles:

A200 A220 A250 A300 A320 A400 A700 A700s A800 A900 C190 FAS2240-4 FAS2552 FAS2650 FAS2720 FAS2750 FAS8200 FAS8300 FAS8700 FAS9000

Modelos no compatibles:

FAS2620 FAS3250 FAS3270 FAS500f FAS6280 FAS/ AFF 8020 FAS/ AFF 8040 FAS/ AFF 8060 FAS/ AFF 8080



== Una nota sobre los permisos

Dado que varios paneles ONTAP de Data Infrastructure Insights dependen de contadores ONTAP avanzados, debe habilitar la *Recopilación avanzada de datos de contadores* en la sección Configuración avanzada del recopilador de datos.

También debe asegurarse de que el permiso de escritura en la API de ONTAP esté habilitado.  Normalmente, esto requiere una cuenta en el nivel de clúster con los permisos necesarios.

Para crear una cuenta local para Data Infrastructure Insights a nivel de clúster, inicie sesión en ONTAP con el nombre de usuario y la contraseña del administrador de administración de clúster y ejecute los siguientes comandos en el servidor de ONTAP :

. Antes de comenzar, debe iniciar sesión en ONTAP con una cuenta de _Administrador_ y los _comandos de nivel de diagnóstico_ deben estar habilitados.
. Cree un rol de solo lectura utilizando los siguientes comandos.
+
....
security login role create -role ci_readonly -cmddirname DEFAULT -access readonly
security login role create -role ci_readonly -cmddirname security -access readonly
security login role create -role ci_readonly -access all -cmddirname {cluster application-record create}
....
. Cree el usuario de solo lectura utilizando el siguiente comando.  Una vez que haya ejecutado el comando de creación, se le pedirá que ingrese una contraseña para este usuario.
+
 security login create -username ci_user -application ontapi -authentication-method password -role ci_readonly


Si se utiliza una cuenta AD/LDAP, el comando debe ser

 security login create -user-or-group-name DOMAIN\aduser/adgroup -application ontapi -authentication-method domain -role ci_readonly
Si está recopilando datos de conmutación de clúster:

....
security login rest-role create -role ci_readonly_rest -api /api/network/ethernet -access readonly
security login create -user-or-group-name ci_user -application http -authmethod password -role ci_readonly_rest
....
El rol resultante y el inicio de sesión del usuario se verán así:  El resultado real puede variar:

....
Role Command/ Access
Vserver Name Directory Query Level
---------- ------------- --------- ------------------ --------
cluster1 ci_readonly DEFAULT read only
cluster1 ci_readonly security readonly
....
....
cluster1:security login> show
Vserver: cluster1
Authentication Acct
UserName    Application   Method      Role Name      Locked
---------   -------      ----------- -------------- --------
ci_user     ontapi      password    ci_readonly   no
....

NOTE: Si el control de acceso de ONTAP no está configurado correctamente, las llamadas REST de Data Infrastructure Insights pueden fallar, lo que genera brechas en los datos del dispositivo.  Por ejemplo, si lo ha habilitado en el recopilador de Data Infrastructure Insights pero no ha configurado los permisos en ONTAP, la adquisición fallará.  Además, si el rol está definido previamente en ONTAP y está agregando las capacidades de Rest API, asegúrese de que _http_ esté agregado al rol.



== Solución de problemas

Algunas cosas que puedes probar si encuentras problemas con este recopilador de datos:



=== Inventario

[cols="2*"]
|===
| Problema: | Prueba esto: 


| Reciba la respuesta HTTP 401 o el código de error ZAPI 13003 y ZAPI devuelve "Privilegios insuficientes" o "no autorizado para este comando". | Verifique el nombre de usuario y la contraseña, y los privilegios/permisos del usuario. 


| La versión del clúster es < 8.1 | La versión mínima admitida del clúster es 8.1.  Actualice a la versión mínima compatible. 


| ZAPI devuelve "la función del clúster no es cluster_mgmt LIF" | AU necesita hablar con la IP de gestión del clúster.  Verifique la IP y cámbiela a una IP diferente si es necesario 


| Error: “Los filtros de modo 7 no son compatibles” | Esto puede suceder si utiliza este recopilador de datos para descubrir el archivador de modo 7.  Cambie la IP para que apunte al clúster cdot. 


| El comando ZAPI falla después de reintentarlo | AU tiene un problema de comunicación con el cluster.  Verifique la red, el número de puerto y la dirección IP.  El usuario también debe intentar ejecutar un comando desde la línea de comandos desde la máquina AU. 


| AU no pudo conectarse a ZAPI a través de HTTP | Compruebe si el puerto ZAPI acepta texto sin formato.  Si AU intenta enviar texto sin formato a un socket SSL, la comunicación falla. 


| La comunicación falla con SSLException | AU está intentando enviar SSL a un puerto de texto simple en un archivador.  Compruebe si el puerto ZAPI acepta SSL o utilice un puerto diferente. 


| Errores de conexión adicionales: La respuesta de ZAPI tiene el código de error 13001, “la base de datos no está abierta”. El código de error de ZAPI es 60 y la respuesta contiene “La API no finalizó a tiempo”. La respuesta de ZAPI contiene “initialize_session() devolvió un entorno NULL”. El código de error de ZAPI es 14007 y la respuesta contiene “El nodo no está en buen estado”. | Verifique la red, el número de puerto y la dirección IP.  El usuario también debe intentar ejecutar un comando desde la línea de comandos desde la máquina AU. 
|===


=== Actuación

[cols="2*"]
|===
| Problema: | Prueba esto: 


| Error “No se pudo recopilar el rendimiento de ZAPI” | Generalmente, esto se debe a que la estadística de rendimiento no se está ejecutando.  Pruebe el siguiente comando en cada nodo: > _system node systemshell -node * -command “spmctl -h cmd –stop; spmctl -h cmd –exec”_ 
|===
Información adicional se puede encontrar en ellink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
