---
sidebar: sidebar 
permalink: task_modify_delete_query.html 
summary: Modifica las consultas existentes cambiando los criterios y las columnas, con opciones flexibles de guardado para actualizar, renombrar o crear nuevas versiones, además de opciones para eliminar consultas cuando ya no sean necesarias. 
keywords: query, queries, modify, edit, delete, remove 
---
= Modificar o eliminar una consulta
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Gestiona tus consultas de forma eficaz modificando los criterios de búsqueda, añadiendo o eliminando columnas y eligiendo entre diversas opciones de guardado. Actualiza las consultas existentes, crea nuevas versiones o elimina consultas que ya no necesites para mantener tu biblioteca de consultas organizada y actualizada.



[[modifying-a-query]]
== Modificar una consulta

.Pasos
. Haga clic en *Explorar* y seleccione *Todas las consultas métricas*.
+
Se muestra la página Consultas.

. Haga clic en el nombre de la consulta
. Para agregar un criterio a la consulta, haga clic en el ícono Columnas y seleccione una métrica o atributo de la lista.


Cuando haya realizado todos los cambios necesarios, realice una de las siguientes acciones:

* Haga clic en el botón *Guardar* para guardar la consulta con el nombre utilizado inicialmente.
* Haga clic en el menú desplegable junto al botón *Guardar* y seleccione *Guardar como* para guardar la consulta con otro nombre.  Esto no sobrescribe la consulta original.
* Haga clic en el menú desplegable junto al botón *Guardar* y seleccione *Cambiar nombre* para cambiar el nombre de la consulta que utilizó inicialmente.  Esto sobrescribe la consulta original.
* Haga clic en el menú desplegable junto al botón *Guardar* y seleccione *Descartar cambios* para revertir la consulta a los últimos cambios guardados.




[[deleting-a-query]]
== Eliminar una consulta

Para eliminar una consulta, haga clic en *Consultas* y seleccione *Mostrar todas las consultas*, y realice una de las siguientes acciones:

. Haga clic en el menú de "tres puntos" a la derecha de la consulta y haga clic en *Eliminar*.
. Haga clic en el nombre de la consulta y seleccione *Eliminar* en el menú desplegable *Guardar*.

