---
sidebar: sidebar 
permalink: task_dc_infinidat_infinibox.html 
keywords: data collector, infinidat, InfiniBox 
summary: Configuración del recopilador de datos Infinidat InfiniBox. 
---
= Colector de datos Infinidat InfiniBox
:hardbreaks:
:allow-uri-read: 


[role="lead"]
El recopilador de datos Infinidat InfiniBox (HTTP) se utiliza para recopilar información de inventario del sistema de almacenamiento Infinidat InfiniBox.



== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario del recopilador de datos Infinidat InfiniBox.  Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más común utilizada para este activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Pool de almacenamiento | Pool de almacenamiento 


| Node | Controladora 


| Sistema de archivos | Volumen interno 


| Sistema de archivos | Compartir archivos 


| Exportaciones del sistema de archivos | Compartir 
|===


== Requisitos

Los siguientes son requisitos al configurar este recopilador de datos.

* Dirección IP o FQDN del nodo de administración de InfiniBox
* Nombre de usuario y contraseña de administrador
* Puerto 443 a través de API REST




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Anfitrión de InfiniBox | Dirección IP o nombre de dominio completo del nodo de administración de InfiniBox 


| Nombre de usuario | Nombre de usuario para el nodo de administración de InfiniBox 


| Password | Contraseña para el nodo de administración de InfiniBox 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Puerto TCP | Puerto TCP utilizado para conectarse al servidor InfiniBox.  El valor predeterminado es 443. 


| Intervalo de sondeo de inventario | Intervalo entre sondeos de inventario. El valor predeterminado es 60 minutos. 
|===


== Solución de problemas

Información adicional sobre este recopilador de datos se puede encontrar enlink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
