---
sidebar: sidebar 
permalink: task_dc_emc_unisphere_rest.html 
keywords: data collector, Unisphere, EMC 
summary: Configuración del recopilador de datos REST de Dell EMC Unisphere. 
---
= Configuración del recopilador de datos REST de Dell EMC Unisphere
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Este recopilador de datos adquiere datos de inventario y rendimiento de Dell EMC Unisphere para los sistemas de administración PowerMax/Vmax 3.

Tenga en cuenta que Dell/EMC no introdujo estadísticas por volumen hasta Unisphere 10.0: este recopilador de datos es compatible con 9.2.0+, pero no podrá recopilar estadísticas de volumen porque no existen.

Es posible que una instancia de Unisphere para Vmax/PowerMax administre una o más matrices de almacenamiento Symmetrix Vmax 3 o superiores: este recopilador intentará, de manera predeterminada, descubrir todas las que sean "locales" para esa instancia de Unisphere.  Si una instancia de Unisphere ve matrices "remotas" (es decir, aquellas conectadas a través de la replicación SRDF), se ignorarán y, para descubrirlas, debe crear un recopilador de Unisphere adicional en Data Infrastructure Insights que apunte a cualquier instancia de Unisphere en ese sitio que las vea como locales.

Para la configuración, el recopilador de datos requiere una dirección IP/FQDN del servidor Unisphere, conectividad TCP al puerto 8443 y un nombre de usuario y contraseña.



== Requisitos

* Una dirección IP/nombre de dominio completo del servidor Unisphere
* Nombre de usuario y contraseña
* Puerto 8443.




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP del servidor Unisphere | Dirección IP o nombre de dominio completo del servidor Unisphere 


| Puerto Unisphere | El valor predeterminado es 8443 


| Nombre de usuario | Nombre de usuario para el servidor Unisphere 


| Password | Contraseña utilizada para el servidor Unisphere 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (min) | El valor predeterminado es 40 minutos. 


| Intervalo de encuesta de rendimiento (seg.) | Intervalo entre encuestas de rendimiento. 


| Seleccione “Excluir” o “Incluir” para especificar una lista | Especificar si se deben incluir o excluir las máquinas virtuales 


| Lista de dispositivos de filtro de inventario | Lista de máquinas virtuales para filtrar (separadas por comas o por punto y coma si se utiliza una coma en el valor) para filtrar 


| Intervalo de la encuesta de rendimiento de Unisphere (seg.) | El valor predeterminado es 300 segundos. 
|===


== Solución de problemas

Algunas cosas que puedes probar si encuentras problemas con este recopilador de datos:



=== Inventario

[cols="2*"]
|===
| Problema: | Prueba esto: 


| Error: Error en la autenticación del usuario. | Asegúrese de que sus credenciales para este dispositivo sean correctas. 


| Inventario Estado reciente: Datos inesperados recuperados - Matriz reportada 0 volumen | Generalmente indica un problema de autorización (no de autenticación).  Asegúrese de que sus credenciales sean correctas y que el nombre de usuario tenga el poder de enumerar todos los volúmenes y ver sus atributos. 
|===
Información adicional se puede encontrar en ellink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
