---
sidebar: sidebar 
permalink: task_dc_redhat_virtualization.html 
keywords: data collector, Red Hat Virtualization 
summary: Configuración del recopilador de datos de Red Hat Virtualization. 
---
= Recopilador de datos de virtualización de Red Hat
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utiliza el recopilador de datos de Red Hat Virtualization para reunir datos de inventario de cargas de trabajo virtualizadas de Linux y Microsoft Windows.



== Terminología

Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más común utilizada para el activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Disco | Disco virtual 


| Host | Host 


| Máquina virtual | Máquina virtual 


| Dominio de almacenamiento | Almacén de datos 


| Unidad lógica | LUN 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

* Dirección IP del servidor RHEV a través del puerto 443 mediante API REST
* Nombre de usuario y contraseña de solo lectura
* RHEV Versión 3.0+




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP del servidor RHEV | Dirección IP del sistema de almacenamiento 


| Nombre de usuario | Nombre de usuario con privilegios de administrador 


| Contraseña para la cuenta privilegiada de administrador | Password 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Puerto de comunicación HTTPS | Puerto utilizado para la comunicación HTTPS a RHEV 


| Intervalo de sondeo de inventario (min) | El valor predeterminado es 20 minutos. 
|===


== Solución de problemas

Información adicional sobre este recopilador de datos se puede encontrar enlink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
