---
sidebar: sidebar 
permalink: task_query_copy_table_values.html 
summary: Copia los valores de la tabla al portapapeles usando la selección de texto o la función de copiar con un solo clic para una transferencia de datos eficiente a campos de búsqueda y aplicaciones externas. 
keywords: query, queries, copy, values, clipboard 
---
= Copiar valores de la tabla
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Optimiza tu flujo de trabajo copiando los valores de las tablas directamente al portapapeles para utilizarlos en búsquedas o en aplicaciones externas. Elige entre la selección manual de texto o la cómoda opción de copiar con un solo clic para los campos de un solo valor con enlaces a activos.

.Acerca de esta tarea
Hay dos métodos que puede utilizar para copiar valores de tablas o resultados de consultas al portapapeles.

.Pasos
. Método 1: Resalte el texto deseado con el mouse, cópielo y péguelo en los campos de búsqueda u otras aplicaciones.
. Método 2: Para campos de valor único, pase el cursor sobre el campo y haga clic en el ícono del portapapeles que aparece.  El valor se copia al portapapeles para su uso en campos de búsqueda u otras aplicaciones.
+
Tenga en cuenta que solo se pueden copiar valores que sean vínculos a activos utilizando este método.  Sólo los campos que incluyen valores únicos (es decir, no listas) tienen el ícono de copia.


