---
sidebar: sidebar 
permalink: task_dc_hpe_nimble.html 
keywords: data collector, HP Nimble, HP, HPE, Alletra 6000 
summary: 'Configuración del recopilador de datos de HP Enterprise Alletra 6000 (anteriormente Nimble).' 
---
= Recopilador de datos HPE Alletra 6000
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
El recopilador de datos HP Enterprise Alletra 6000 (anteriormente Nimble) admite datos de inventario y rendimiento de las matrices de almacenamiento Alletra 6000.



== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario de este recopilador. Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más habitual utilizada para este activo. Al ver o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Plazo del proveedor/modelo | Término de información sobre la infraestructura de datos 


| Cabina | Reducida 


| Disco | Disco 


| Volumen | Volumen 


| Pool | Pool de almacenamiento 


| Iniciador | Alias del host de almacenamiento 


| Controladora | Nodo de almacenamiento 


| Interfaz Fibre Channel | Controladora 
|===
Nota: Sólo son asignaciones de terminología comunes y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

Para recoger los datos de inventario y configuración de la cabina de almacenamiento, debe ser lo siguiente:

* La cabina debe estar instalada y configurada, y es posible acceder a ella desde el cliente a través de su nombre de dominio completo (FQDN) o la dirección IP de administración de cabinas.
* El arreglo debe estar ejecutando NimbleOS 2.3.x o posterior.
* Debe tener un nombre de usuario y una contraseña válidos en la matriz con al menos el rol de "operador". El rol "invitado" no tiene acceso suficiente para comprender las configuraciones de iniciadores.
* El puerto 5392 debe estar abierto en la cabina.


Debe tener lo siguiente para recoger datos de rendimiento de la cabina de almacenamiento:

* El arreglo debe estar ejecutando NimbleOS 4.0.0 o posterior
* La cabina debe tener volúmenes configurados. La única API de rendimiento que NimbleOS tiene es para los volúmenes, y cualquier estadística que los informes de Data Infrastructure Insights se deriva de las estadísticas de los volúmenes




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP de administración de cabinas | Nombre de dominio completo (FQDN) o dirección IP de administración de cabinas. 


| Nombre de usuario | Nombre de usuario para la cabina 


| Contraseña | Contraseña para la cabina 
|===


== Configuración avanzada

|===


| Campo | Descripción 


| Puerto | Puerto que utiliza la API DE REST de Nimble. El valor predeterminado es 5392. 


| Intervalo de sondeo de inventario (mín.) | Intervalo entre sondeos de inventario. El valor predeterminado es 60 minutos. 
|===
Nota: El intervalo de sondeo de rendimiento predeterminado es de 300 segundos y no se puede cambiar. Este es el único intervalo admitido por HPE Alletra 6000.
