---
sidebar: sidebar 
permalink: task_io_density_report_no_root.html 
summary: Al consultar una alta densidad de E/S, conviene excluir los volúmenes raíz. 
keywords: NetApp, root volume, high I/O, 
---
= Garantizar que los informes de densidad de E/S describan únicamente los volúmenes de datos internos
:hardbreaks:
:allow-uri-read: 


[role="lead"]
El volumen raíz de NetApp contiene directorios y archivos de configuración para administrar el sistema de almacenamiento.  Al consultar una alta densidad de E/S, conviene excluir estos volúmenes raíz.

Al supervisar su entorno, es más importante determinar qué volúmenes de datos internos están produciendo números de alta densidad de E/S.  Para identificar con precisión solo los volúmenes de datos, debe aislar los volúmenes internos de NetApp de las consultas que utiliza para monitorear la densidad de E/S.

Esta guía describe cómo identificar fácilmente los agregados raíz de NetApp , aislarlos de los resultados de las consultas de volumen internas y crear reglas que excluyan cualquier agregado raíz de NetApp nuevo a medida que se agrega al sistema.  Las siguientes funciones de Insight se utilizan para garantizar que sus informes de densidad de E/S se deriven de volúmenes de datos internos:

* Se crea una consulta para identificar todos los agregados raíz de NetApp que monitorea Insight.
* Se asigna una anotación a cada uno de los agregados raíz de NetApp .
* Se crea una regla de anotación para aplicar la anotación a los nuevos agregados raíz de NetApp .


Los pasos de esta guía también se pueden aplicar a los sistemas de almacenamiento de otros proveedores.  Necesitará identificar los volúmenes que contienen directorios y archivos de configuración para administrar el sistema de almacenamiento y utilizar pasos similares para excluir estos volúmenes.



== Creación de una consulta para identificar agregados raíz de NetApp

Las consultas proporcionan búsqueda a un nivel granular, según criterios seleccionados por el usuario.  El uso de una consulta le permite buscar volúmenes internos en su inquilino que contengan el agregado raíz de NetApp .

.Pasos
. Cree una consulta para identificar agregados raíz de NetApp en su inquilino: haga clic en *Consultas > Nueva consulta > Seleccionar tipo de recurso* (?)
. Haga clic en *Grupo de almacenamiento*
. Introduzca el nombre para el agregado raíz
+
Este ejemplo utiliza "aggr0" para el nombre.  Al crear un agregado, solo se deben cumplir los siguientes requisitos para el nombre:

+
.. Debe comenzar con una letra o un guión bajo (_).
.. Sólo puede contener letras, dígitos y guiones bajos.
.. Puede tener 250 caracteres o menos.  En la mayoría de los casos, el agregado se llama aggr0, aggr_0 o algo similar.  Es posible que se requiera un proceso iterativo para identificar todos los agregados raíz de NetApp en su inquilino.


. Haga clic en *Guardar* e ingrese un nombre para la nueva consulta.
+
Como se mencionó anteriormente, este podría ser un proceso iterativo y requerir múltiples consultas para identificar todos los agregados raíz de NetApp .





== Cree una anotación para los volúmenes raíz devueltos por sus consultas

Las anotaciones son notas especializadas que usted asigna a sus activos, lo que le permite filtrarlos por sus anotaciones.  La anotación que cree se utilizará para identificar los agregados raíz de NetApp en su inquilino y garantizar que no se incluyan en un informe específico.

.Antes de empezar
Debe haber identificado todos los agregados raíz que desea excluir del informe "Alta densidad de E/S".

.Pasos
. En el menú Data Infrastructure Insights , haga clic en *Administrar > Anotaciones*
. Haga clic en *Agregar*
+
.. Introduzca el nombre de la anotación: *RootAggr*
.. Introduzca una descripción de la anotación: *Eliminar el agregado raíz del informe "Alta densidad de E/S"*
.. Introduzca el tipo de anotación: *Booleano*


. Haga clic en *Guardar*




== Cree una regla de anotación para automatizar la exclusión de agregados específicos de su informe de densidad de E/S

Como alternativa a la aplicación manual de anotaciones a activos individuales, puede aplicar anotaciones automáticamente a múltiples activos utilizando reglas de anotación.  Las reglas de anotación se basan en consultas que usted crea y cuando se ejecutan en el sistema, agregan nuevos activos a conjuntos de activos existentes.  Cuando estos conjuntos de activos se excluyen de un informe, los nuevos activos también se excluyen automáticamente.

.Antes de empezar
Debe haber creado y guardado una consulta que identifique los agregados raíz de NetApp que identificó en su inquilino.

.Pasos
. En la barra de herramientas de Data Infrastructure Insights , haga clic en *Administrar > Reglas de anotación*.
. Haga clic en *Agregar*. Se muestra el cuadro de diálogo Agregar regla.
+
.. En el cuadro Nombre, ingrese un nombre único que describa la regla: *"RootAggrExclude"*
.. Haga clic en Consulta y seleccione la consulta que Insight debe usar para aplicar la regla de anotación a: *"Aggregate0"*
.. Haga clic en Anotación y seleccione: *"Excluir agregado raíz"*
.. Haga clic en *Valor* e ingrese *Verdadero*



