---
sidebar: sidebar 
permalink: task_dc_na_amazon_fsx.html 
keywords: 'data collector, stout, fsx, fsx-netapp, Amazon, AWS, cluster, volume, share, LUN"' 
summary: Amazon FSX para el recopilador de datos ONTAP de NetApp 
---
= Recopilador de datos de Amazon FSX para ONTAP de NetApp
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Este recopilador de datos adquiere datos de inventario y rendimiento de Amazon FSX para ONTAP de NetApp. Este recopilador de datos estará disponible de forma incremental en todas las regiones del servicio Data Infrastructure Insights. Póngase en contacto con su vendedor si no ve el icono de este recopilador en su entorno Data Infrastructure Insights.


NOTE: Este recopilador de información de infraestructura de datos requiere un usuario de ONTAP con el rol _Filesystem-scoped_. Consulte link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/roles-and-users.html["Roles y Reglas"]la documentación de AWS para conocer las opciones disponibles. En este momento, AWS solo admite un tipo de rol de usuario con el ámbito del sistema de archivos, que es _fsxadmin_. Este es el rol adecuado que se debe utilizar para el recopilador de Data Infrastructure Insights. El usuario también debe tener las tres aplicaciones asignadas: http, ontapi, ssh.



== Terminología

Información sobre infraestructuras de datos adquiere datos de inventario y rendimiento del recopilador de datos FSx-NetApp. Para cada tipo de activo adquirido, se muestra la terminología más común utilizada para el activo. Al ver o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Plazo del proveedor/modelo | Término de información sobre la infraestructura de datos 


| Clúster | Reducida 


| LUN | Volumen 


| Volumen | Volumen interno 
|===


== Terminología de FSX-NetApp

Los siguientes términos se aplican a objetos o referencias que puede encontrar en las páginas de destino de activos de almacenamiento FSX-NetApp. Muchos de estos términos también se aplican a otros recopiladores de datos.



=== Reducida

* Modelo: Una lista delimitada por comas con los nombres de modelos diferenciados únicos dentro de este clúster.
* Proveedor: AWS
* Número de serie: El número de serie de la cabina.
* IP: Generalmente serán las IP o los hostname tal como están configurados en el origen de datos.
* Capacidad bruta: Suma en base 2 de todo el almacenamiento SSD asignado al sistema de archivos FSX.
* Latencia: Representación de lo que experimentan las cargas de trabajo a las que se enfrentan el host, tanto en lecturas como escrituras. Lo ideal es que Data Infrastructure Insights obtenga este valor directamente pero este no es el caso. En lugar de que la cabina que ofrece esta opción, Data Infrastructure Insights suele realizar un cálculo ponderado por IOPS derivado de las estadísticas de los volúmenes internos individuales.
* Rendimiento: Agregado de volúmenes internos. Administración: Puede contener un hipervínculo para la interfaz de gestión del dispositivo. Creado mediante programación por el origen de datos de Data Infrastructure Insights como parte de los informes de inventario.




=== Pool de almacenamiento

* Almacenamiento: En qué cabina de almacenamiento vive este pool. Obligatorio.
* Tipo: Valor descriptivo de una lista de posibilidades enumeradas. La mayoría de las veces será “agregado” o “grupo RAID”.
* Capacidad: Los valores aquí son los lógicos utilizados, la capacidad utilizable y la capacidad total lógica, así como el porcentaje utilizado en estos.
* IOPS: La suma de IOPS de todos los volúmenes asignados en este pool de almacenamiento.
* Rendimiento: La suma del rendimiento de todos los volúmenes asignados en este pool de almacenamiento.




== Requisitos

A continuación se enumeran los requisitos para configurar y utilizar este recopilador de datos:

* Debe tener acceso a una cuenta con el rol “fsxadmin”, con tres aplicaciones asignadas - ssh, ontapi, http
* Entre los detalles de la cuenta se incluye el nombre de usuario y la contraseña
* Requisitos del puerto: 443




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| IP de gestión de NetApp | La dirección IP o el nombre de dominio completo del clúster de NetApp 


| Nombre de usuario | Nombre de usuario del clúster de NetApp 


| Contraseña | Contraseña para el clúster de NetApp 
|===


== Métricas avanzadas

Este recopilador de datos recopila las siguientes métricas avanzadas de FSX para el almacenamiento ONTAP de NetApp:

* fpolicy
* nfsv3
* nfsv3: nodo
* nfsv4
* nfsv4_1
* nfsv4_1: nodo
* nfsv4: nodo
* policy_group
* qtree
* volumen
* workload_volume


Tenga en cuenta que los comandos de la CLI de FSx y la API recuperan algunos valores de capacidad que ZAPI de Data Infrastructure Insights no recopila, por lo que ciertos valores de capacidad (como los para los pools de almacenamiento) pueden ser diferentes en Información de la infraestructura de datos de los que están en FSx.



== Resolución de problemas

Algunas cosas para intentar si tiene problemas con este recopilador de datos:



=== Inventario

[cols="2*"]
|===
| Problema: | Pruebe lo siguiente: 


| Recibir respuesta HTTP 401 o código de error ZAPI 13003 y ZAPI devuelve “privilegios insuficientes” o “no autorizados para este comando” | Compruebe el nombre de usuario y la contraseña, así como los privilegios y permisos de usuario. 


| ZAPI devuelve "el rol del clúster no es la LIF de gestión_clústeres" | AU necesita hablar con la IP de administración de clústeres. Compruebe la dirección IP y cambie a otra dirección IP si es necesario 


| El comando ZAPI falla después del reintento | AU tiene un problema de comunicación con el clúster. Compruebe la red, el número de puerto y la dirección IP. El usuario también debe intentar ejecutar un comando desde la línea de comandos desde la máquina AU. 


| AU no pudo conectarse a ZAPI a través de HTTP | Compruebe si EL puerto ZAPI acepta texto sin formato. Si AU intenta enviar texto sin formato a un socket SSL, la comunicación falla. 


| La comunicación falla con SSLException | AU está intentando enviar SSL a un puerto de texto sin formato de un archivador. Compruebe si EL puerto ZAPI acepta SSL o utiliza un puerto diferente. 


| Errores de conexión adicionales: La respuesta ZAPI tiene el código de error 13001, “la base de datos no está abierta” el código DE error ZAPI es 60 y la respuesta contiene “la API no terminó a tiempo” la respuesta ZAPI contiene “initialize_Session() devolvió un entorno NULL” el código DE error ZAPI es 14007 y la respuesta contiene “el nodo no está en buen estado” | Compruebe la red, el número de puerto y la dirección IP. El usuario también debe intentar ejecutar un comando desde la línea de comandos desde la máquina AU. 
|===
Puede encontrar información adicional en la link:concept_requesting_support.html["Soporte técnico"] página o en el link:reference_data_collector_support_matrix.html["Matriz de compatibilidad de recopilador de datos"].
