---
sidebar: sidebar 
permalink: task_dc_proxmox_ve.html 
keywords: data collector, Proxmox Virtual Environment, PVE 
summary: Configurando el recopilador de datos de Proxmox Virtual Environment. 
---
= Recopilador de datos del entorno virtual de Proxmox
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El colector DII Proxmox Virtual Environment recopilará datos de inventario y rendimiento de las máquinas virtuales basadas en PVE (no contenedores LXC) y de los hosts/hipervisores. Este es un colector basado en una API de REST HTTPS que necesita comunicarse con la API de REST de Proxmox proporcionada por el servicio/demonio pveproxy, que escucha en el puerto TCP 8006.

Este recopilador de datos utiliza autenticación mediante usuario + token. Deberás crear una cuenta de servicio en cada clúster de Proxmox, asignar los permisos adecuados al usuario y luego generar un token de API con esos mismos derechos. Ten en cuenta que el token de un usuario concreto de Proxmox NO tiene necesariamente los mismos derechos o permisos que el usuario. Por lo general, DII necesitará derechos globales de nivel auditoría/supervisión; si estás creando una cuenta de servicio a través de la interfaz de usuario de Proxmox, para PathPermision comienza en “/”, establece Propagate en “Yes” y desbloquea Datastore Audit, Mapping Audit, Pool Audit, SDN Audit, Sys Audit, VM Audit y VM Monitor como mínimo. Con el usuario creado, puedes generar un token de acceso para él. Te recomendamos encarecidamente que crees el token con una caducidad de 0 para asegurarte de que nunca caduque.



[[terminology]]
== Terminología

Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más común utilizada para el activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="50,50"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Disco | Disco virtual 


| Host | Host 


| Máquina virtual | Máquina virtual 


| Almacenamiento | Almacén de datos 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de este recopilador de datos.



[[configuration]]
== Configuración

[cols="50,50"]
|===
| Campo | Descripción 


| Nombre de host o dirección IP | nombre de host dirección IP del sistema de almacenamiento 


| ID del token de la API | Se requiere un token de API para acceder 


| Secreto del token de API | Secreto para el token anterior 
|===


[[advanced-configuration]]
== Configuración avanzada

[cols="50,50"]
|===
| Campo | Descripción 


| Puerto de comunicación HTTPS | Puerto utilizado para la comunicación HTTPS (por defecto 8006) 


| Intervalo de sondeo de inventario (min) | El valor predeterminado es 20 minutos. 
|===


[[troubleshooting]]
== Solución de problemas

Información adicional sobre este recopilador de datos se puede encontrar enlink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
