---
sidebar: sidebar 
permalink: task_dc_na_amazon_fsx.html 
keywords: 'data collector, stout, fsx, fsx-netapp, Amazon, AWS, cluster, volume, share, LUN"' 
summary: Recopilador de datos de Amazon FSx for NetApp ONTAP 
---
= Recopilador de datos de Amazon FSx for NetApp ONTAP
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Este recopilador de datos adquiere datos de inventario y rendimiento de Amazon FSx for NetApp ONTAP.  Este recopilador de datos estará disponible de forma incremental en todas las regiones de servicio de Data Infrastructure Insights .  Comuníquese con su vendedor si no ve el ícono de este recopilador en su entorno de Data Infrastructure Insights .


NOTE: Este recopilador de Data Infrastructure Insights requiere un usuario de ONTAP con un rol _Filesystem-Scoped_.  Por favor revise el AWSlink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/roles-and-users.html["Roles y reglas"] Documentación de las opciones disponibles.  En este momento, AWS solo admite un tipo de rol de usuario con alcance de sistema de archivos, que es _fsxadmin_.  Esta es la función adecuada que debe utilizarse para el recopilador de Data Infrastructure Insights .  El usuario también debe tener asignadas estas tres aplicaciones: http, ontapi, ssh.



== Terminología

Data Infrastructure Insights adquiere datos de inventario y rendimiento del recopilador de datos FSx- NetApp .  Para cada tipo de activo adquirido, se muestra la terminología más común utilizada para el activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Grupo | Almacenamiento 


| LUN | Volumen 


| Volumen | Volumen interno 
|===


== Terminología de FSx- NetApp

Los siguientes términos se aplican a objetos o referencias que pueda encontrar en las páginas de inicio de activos de almacenamiento de FSx- NetApp .  Muchos de estos términos se aplican también a otros recopiladores de datos.



=== Almacenamiento

* Modelo: una lista delimitada por comas de los nombres de modelos únicos y discretos dentro de este clúster.
* Proveedor – AWS
* Número de serie: el número de serie de la matriz.
* IP: generalmente serán las IP o los nombres de host configurados en la fuente de datos.
* Capacidad bruta: suma en base 2 de todo el almacenamiento SSD asignado al sistema de archivos FSx.
* Latencia: una representación de lo que experimenta el host que enfrenta cargas de trabajo, tanto en lecturas como en escrituras.  Lo ideal sería que Data Infrastructure Insights obtenga este valor directamente, pero a menudo no es así.  En lugar de que la matriz ofrezca esto, Data Infrastructure Insights generalmente realiza un cálculo ponderado por IOP derivado de las estadísticas de los volúmenes internos individuales.
* Rendimiento: agregado a partir de volúmenes internos.  Administración: puede contener un hipervínculo a la interfaz de administración del dispositivo.  Creado programáticamente por la fuente de datos Data Infrastructure Insights como parte del informe de inventario.




=== Pool de almacenamiento

* Almacenamiento: en qué matriz de almacenamiento reside este grupo.  Obligatorio.
* Tipo: un valor descriptivo de una lista de una lista enumerada de posibilidades.  Lo más común será “Agregado” o “Grupo RAID”.
* Capacidad: los valores aquí son la capacidad lógica utilizada, la capacidad utilizable y la capacidad total lógica, y el porcentaje utilizado en estas.
* IOPS: la suma de IOPS de todos los volúmenes asignados en este grupo de almacenamiento.
* Rendimiento: el rendimiento total de todos los volúmenes asignados en este grupo de almacenamiento.




== Requisitos

Los siguientes son los requisitos para configurar y utilizar este recopilador de datos:

* Debe tener acceso a una cuenta con el rol "fsxadmin", con tres aplicaciones asignadas a ella: ssh, ontapi, http
* Los detalles de la cuenta incluyen nombre de usuario y contraseña.
* Requisitos del puerto: 443




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| IP de gestión de NetApp | Dirección IP o nombre de dominio completo del clúster de NetApp 


| Nombre de usuario | Nombre de usuario para el clúster de NetApp 


| Password | Contraseña para el clúster de NetApp 
|===


== Métricas avanzadas

Este recopilador de datos recopila las siguientes métricas avanzadas del almacenamiento FSx para NetApp ONTAP :

* política
* nfsv3
* nfsv3:nodo
* nfsv4
* nfsv4_1
* nfsv4_1:nodo
* nfsv4:nodo
* grupo de políticas
* qtree
* volume
* volumen de carga de trabajo


Tenga en cuenta que los comandos CLI y API de FSx recuperan algunos valores de capacidad que Data Infrastructure Insights ZAPI no recopila, por lo que ciertos valores de capacidad (como los de los grupos de almacenamiento) pueden ser diferentes en Data Infrastructure Insights que en el propio FSx.



== Solución de problemas

Algunas cosas que puedes probar si encuentras problemas con este recopilador de datos:



=== Inventario

[cols="2*"]
|===
| Problema: | Prueba esto: 


| Reciba la respuesta HTTP 401 o el código de error ZAPI 13003 y ZAPI devuelve "Privilegios insuficientes" o "no autorizado para este comando". | Verifique el nombre de usuario y la contraseña, y los privilegios/permisos del usuario. 


| ZAPI devuelve "la función del clúster no es cluster_mgmt LIF" | AU necesita hablar con la IP de gestión del clúster.  Verifique la IP y cámbiela a una IP diferente si es necesario 


| El comando ZAPI falla después de reintentarlo | AU tiene un problema de comunicación con el cluster.  Verifique la red, el número de puerto y la dirección IP.  El usuario también debe intentar ejecutar un comando desde la línea de comandos desde la máquina AU. 


| AU no pudo conectarse a ZAPI a través de HTTP | Compruebe si el puerto ZAPI acepta texto sin formato.  Si AU intenta enviar texto sin formato a un socket SSL, la comunicación falla. 


| La comunicación falla con SSLException | AU está intentando enviar SSL a un puerto de texto simple en un archivador.  Compruebe si el puerto ZAPI acepta SSL o utilice un puerto diferente. 


| Errores de conexión adicionales: La respuesta de ZAPI tiene el código de error 13001, “la base de datos no está abierta”. El código de error de ZAPI es 60 y la respuesta contiene “La API no finalizó a tiempo”. La respuesta de ZAPI contiene “initialize_session() devolvió un entorno NULL”. El código de error de ZAPI es 14007 y la respuesta contiene “El nodo no está en buen estado”. | Verifique la red, el número de puerto y la dirección IP.  El usuario también debe intentar ejecutar un comando desde la línea de comandos desde la máquina AU. 
|===
Información adicional se puede encontrar en ellink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
