---
sidebar: sidebar 
permalink: task_dc_emc_datadomain.html 
keywords: data collector, Data Domain, EMC, DELL 
summary: Configuración del recopilador de datos de DELL EMC Data Domain. 
---
= Recopilador de datos de DELL EMC Data Domain
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Este recopilador de datos reúne información de inventario y rendimiento de los sistemas de almacenamiento con deduplicación DELL EMC Data Domain.  Para configurar este recopilador de datos, existen instrucciones de configuración específicas y recomendaciones de uso que debe seguir.



== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario del recopilador de datos Data Domain.  Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más común utilizada para este activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Disco | Disco 


| Formación | Almacenamiento 


| Puerto FC | Puerto 


| Sistema de archivos | Volumen interno 


| Cuota | Cuota 


| Compartir NFS y CIFS | Compartir archivos 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

Necesita la siguiente información para configurar este recopilador de datos:

* Dirección IP del dispositivo Data Domain
* Nombre de usuario y contraseña de solo lectura para el almacenamiento de Data Domain
* Puerto SSH 22




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP | La dirección IP o el nombre de dominio completo de la matriz de almacenamiento de Data Domain 


| Nombre de usuario | El nombre de usuario para la matriz de almacenamiento Data Domain 


| Password | La contraseña para la matriz de almacenamiento de Data Domain 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (min) | Intervalo entre sondeos de inventario.  El valor predeterminado es 20. 


| Puerto SSH | Puerto de servicio SSH 
|===


== Solución de problemas

Información adicional sobre este recopilador de datos se puede encontrar enlink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
