---
sidebar: sidebar 
permalink: task_dc_emc_unity.html 
keywords: data collector, VNXe, EMC, Unity 
summary: Configuración del recopilador de datos de VNXe. 
---
= Configuración del recopilador de datos de EMC Unity
:hardbreaks:
:allow-uri-read: 


[role="lead"]
El recopilador de datos de DELL EMC Unity (anteriormente VNXe) proporciona soporte de inventario para matrices de almacenamiento unificadas VNXe.  Data Infrastructure Insights actualmente admite los protocolos iSCSI y NAS.



== Requisitos

* El recopilador de datos de Unity se basa en CLI; debe instalar la CLI de Unisphere para Unity (uemcli.exe) en la unidad de adquisición donde reside el recopilador de datos de VNXe.
* uemcli.exe utiliza HTTPS como protocolo de transporte, por lo que la unidad de adquisición deberá poder iniciar conexiones HTTPS a Unity.
* Dirección IP o nombre de dominio completo del dispositivo Unity
* Debe tener al menos un usuario de solo lectura para que lo utilice el recopilador de datos.
* Se requiere HTTPS en el puerto 443
* El recopilador de datos de EMC Unity proporciona compatibilidad con NAS e iSCSI para el inventario; se descubrirán volúmenes de canal de fibra, pero Data Infrastructure Insights no informa sobre el mapeo, el enmascaramiento ni los puertos de almacenamiento de FC.




== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario del recopilador de datos de Unity.  Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más común utilizada para este activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Disco | Disco 


| Matriz de almacenamiento | Almacenamiento 


| Procesador | Nodo de almacenamiento 


| Pool de almacenamiento | Pool de almacenamiento 


| Información general del bloque iSCSI, VMware VMFS | Compartir 


| Sistema remoto de replicación | Sincronización 


| Nodo iSCSI | Nodo de destino iSCSI 


| Iniciador iSCSI | Iniciador de destino iSCSI 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de esta fuente de datos.



== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Almacenamiento de Unity | Dirección IP o nombre de dominio completo del dispositivo Unity 


| Nombre de usuario | Nombre de usuario para el dispositivo Unity 


| Password | Contraseña para el dispositivo Unity 


| Ruta completa al ejecutable UEMCLI | Ruta completa a la carpeta que contiene el ejecutable _uemcli.exe_ 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (min) | Intervalo entre sondeos de inventario.  El valor predeterminado es 40 minutos. 


| Puerto CLI de Unity | Puerto utilizado para la CLI de Unity 


| Intervalo de sondeo de rendimiento (seg.) | El valor predeterminado es 300. 
|===


== Solución de problemas

Algunas cosas que puedes probar si encuentras problemas con este recopilador de datos:



=== Inventario

[cols="2*"]
|===
| Problema: | Prueba esto: 


| "Error al ejecutar la utilidad externa" con mensajes de error "Error al encontrar el ejecutable de Unisphere uemcli" | * Verifique que la dirección IP, el nombre de usuario y la contraseña sean correctos * Confirme que Unisphere CLI esté instalado en la unidad de adquisición de Data Infrastructure Insights * Confirme que el directorio de instalación de Unisphere CLI sea correcto en la configuración de la fuente de datos * Confirme que la IP de VNXe sea correcta en la configuración de la fuente de datos.  Desde la Unidad de adquisición de Data Infrastructure Insights , abra un CMD y cambie al directorio de instalación configurado: ${INSTALLDIR.  Intente establecer una conexión con el dispositivo VNXe escribiendo: uemcli -d <Su IP> -u <Su ID> /sys/general show 
|===
Información adicional se puede encontrar en ellink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
