---
sidebar: sidebar 
permalink: task_dc_ibm_svc.html 
keywords: IBM, SVC,SAN 
summary: Configuración del recopilador de datos de IBM SAN Volume Controller. 
---
= Configuración del recopilador de datos de IBM SAN Volume Controller
:hardbreaks:
:allow-uri-read: 


[role="lead"]
El recopilador de datos de IBM SAN Volume Controller (SVC) recopila datos de inventario y rendimiento mediante SSH y admite una variedad de dispositivos que ejecutan el sistema operativo SVC.

La lista de dispositivos compatibles incluye modelos como el SVC, el v7000, el v5000 y el v3700.  Consulte la matriz de soporte de Data Infrastructure Insights para conocer los modelos y versiones de firmware compatibles.



== Terminología

Data Infrastructure Insights adquiere la siguiente información de inventario del recopilador de datos de IBM SVC.  Para cada tipo de activo adquirido por Data Infrastructure Insights, se muestra la terminología más común utilizada para este activo.  Al visualizar o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Término de proveedor/modelo | Data Infrastructure Insights 


| Conducir | Disco 


| Grupo | Almacenamiento 


| Node | Nodo de almacenamiento 


| Grupo Mdisk | Pool de almacenamiento 


| Disco virtual | Volumen 


| Disco duro virtual | LUN y rutas de backend 
|===
Nota: Estas son solo asignaciones de terminología común y es posible que no representen todos los casos de este recopilador de datos.



=== Requisitos de inventario

* Dirección IP de cada clúster SVC
* Puerto 22 disponible
* Nombre de usuario y contraseña de solo lectura




=== Requisitos de desempeño

* Consola SVC, que es obligatoria para cualquier clúster SVC y necesaria para el paquete de base de descubrimiento SVC.
* Las credenciales requerirán un nivel de acceso administrativo solo para copiar archivos de rendimiento de los nodos del clúster al nodo de configuración.
* Habilite la recopilación de datos conectándose al clúster SVC mediante SSH y ejecutando: _svctask startstats -interval 1_
+
Nota: Alternativamente, habilite la recopilación de datos utilizando la interfaz de usuario de administración de SVC.





== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Direcciones IP del clúster | Direcciones IP o nombres de dominio completos del almacenamiento SVC 


| Nombre de usuario del inventario | Nombre de usuario para la CLI de SVC 


| Contraseña de inventario | Contraseña para la CLI de SVC 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (min) | Intervalo entre sondeos de inventario. El valor predeterminado es 40 minutos. 


| Intervalo de encuesta de rendimiento (seg.) | Intervalo entre encuestas de rendimiento. El valor predeterminado es 300 segundos. 


| Para limpiar archivos de estadísticas volcados | Seleccione esta casilla de verificación para limpiar los archivos de estadísticas volcados 
|===


== Solución de problemas

Algunas cosas que puedes probar si encuentras problemas con este recopilador de datos:

[cols="2*"]
|===
| Problema: | Prueba esto: 


| Error: "No se puede iniciar el comando porque no se ejecutó en el nodo de configuración". | El comando debe ejecutarse en el nodo de configuración. 
|===
Algunas cosas que puedes probar si encuentras problemas con este recopilador de datos:

[cols="2*"]
|===
| Problema: | Prueba esto: 


| Error: "No se puede iniciar el comando porque no se ejecutó en el nodo de configuración". | El comando debe ejecutarse en el nodo de configuración. 
|===
Información adicional sobre este recopilador de datos se puede encontrar enlink:concept_requesting_support.html["Soporte"] página o en ellink:reference_data_collector_support_matrix.html["Matriz de soporte del recopilador de datos"] .
